Repository redis/docs, pull requests merged in 2024-11, with the labels that each got.

#830 Quick fix for LDAP link in glossary
  content/glossary/_index.md
Labels: bug

#758 K8s: architecture rewrite
  content/operate/kubernetes/architecture/_index.md
  content/operate/kubernetes/architecture/deployment-options.md
  content/operate/kubernetes/architecture/operator.md
  content/operate/kubernetes/deployment/_index.md
  content/operate/kubernetes/faqs/_index.md
  content/operate/kubernetes/re-clusters/multi-namespace.md
  content/operate/kubernetes/re-databases/db-controller.md
  static/images/k8s/k8s-arch-v4.png
  static/images/k8s/k8s-node-arch.png
Labels: k8s

#832 RC: Make sure "connect to database" and "Default user" pages are up-to-date
  content/operate/rc/databases/connect.md
  content/operate/rc/rc-quickstart.md
  content/operate/rc/security/access-control/data-access-control/default-user.md
  static/images/rc/connection-wizard-clients.png
  static/images/rc/connection-wizard.png
Labels: rc

#828 Update frontmatter helper script
  insert_url_frontmatter.bash
  version_frontmatter_helper.bash
Labels: infrastructure

#680 DOC-4274 Add support for versioned products in prod bucket
  .github/workflows/main.yml
Labels: do not merge yet

#819 DEV: flesh out FT.PROFILE page
  content/commands/ft.profile/index.md
Labels: dev

#816 RS: Check DB availability
  content/operate/rs/databases/durability-ha/db-availability.md
Labels: rs

#732 RS: Add failover REST API reference
  content/operate/rs/references/rest-api/permissions.md
  content/operate/rs/references/rest-api/requests/shards/actions/failover.md
Labels: rs

#838 K8s: typo
  content/operate/kubernetes/release-notes/7-4-6-releases/7-4-6-2-october24.md
Labels: bug

#831 RS: New CM UI instructions to flush Active-Active DB
  content/operate/rs/databases/import-export/flush.md
Labels: rs

#844 Add HFE commands to compat. page
  content/operate/rs/references/compatibility/commands/data-types.md
Labels: release-branch, rs

#750 RS: Add DB stop_traffic & resume_traffic REST API request references
  content/operate/rs/references/rest-api/requests/bdbs/actions/_index.md
  content/operate/rs/references/rest-api/requests/bdbs/actions/resume_traffic.md
  content/operate/rs/references/rest-api/requests/bdbs/actions/stop_traffic.md
Labels: rs

#813 RS: User manager role
  content/operate/rs/references/rest-api/objects/role.md
  content/operate/rs/references/rest-api/objects/user.md
  content/operate/rs/references/rest-api/permissions.md
  content/operate/rs/references/rest-api/requests/bdbs/_index.md
  content/operate/rs/references/rest-api/requests/bdbs/actions/optimize_shards_placement.md
  content/operate/rs/references/rest-api/requests/bdbs/availability.md
  content/operate/rs/references/rest-api/requests/bdbs/peer_stats.md
  content/operate/rs/references/rest-api/requests/bdbs/stats/_index.md
  content/operate/rs/references/rest-api/requests/bdbs/stats/last.md
  content/operate/rs/references/rest-api/requests/bdbs/sync_source_stats.md
  content/operate/rs/references/rest-api/requests/bdbs/syncer_state/_index.md
  content/operate/rs/references/rest-api/requests/bdbs/syncer_state/crdt.md
  content/operate/rs/references/rest-api/requests/bdbs/syncer_state/replica.md
  content/operate/rs/references/rest-api/requests/cluster/stats/_index.md
  content/operate/rs/references/rest-api/requests/cm_settings/_index.md
  content/operate/rs/references/rest-api/requests/modules/_index.md
  content/operate/rs/references/rest-api/requests/nodes/_index.md
  content/operate/rs/references/rest-api/requests/nodes/actions.md
  content/operate/rs/references/rest-api/requests/nodes/snapshots.md
  content/operate/rs/references/rest-api/requests/proxies/_index.md
  content/operate/rs/references/rest-api/requests/redis_acls/_index.md
  content/operate/rs/references/rest-api/requests/roles/_index.md
  content/operate/rs/references/rest-api/requests/users/_index.md
  content/operate/rs/security/access-control/create-cluster-roles.md
Labels: rs

#846 RS: Enable TLS updates for new CM UI
  content/operate/rs/security/encryption/tls/enable-tls.md
  static/images/rs/screenshots/databases/active-active-databases/enable-tls-for-active-active-db.png
  static/images/rs/screenshots/databases/security-mtls-clients-7-8-2.png
Labels: rs

#847 RS: RHEL 9 FIPS mode support
  content/embeds/supported-platforms-embed.md
  content/operate/rs/release-notes/rs-7-8-releases/_index.md
  content/operate/rs/release-notes/rs-7-8-releases/rs-7-8-2-28.md
Labels: rs

#842 DOC-4519 fixed bugs in config folder diagram
  static/images/rdi/ingest/ingest-config-folders.svg
Labels: rdi

#852 Update _index.md
  content/operate/rs/clusters/monitoring/_index.md
Labels: rs

#858 DEV: correct errant FILTER on FT.CREATE page
  content/commands/ft.create/index.md
Labels: bug, dev

#540 RS: v2 Prometheus metrics
  content/integrate/prometheus-with-redis-enterprise/prometheus-metrics-definitions.md
  content/integrate/prometheus-with-redis-enterprise/prometheus-metrics-v1-to-v2.md
Labels: rs

#837 K8s Viking - supported distributions updates
  content/operate/kubernetes/7.4.6/reference/supported_k8s_distributions.md
  content/operate/kubernetes/reference/supported_k8s_distributions.md
Labels: k8s, next release

#868 Fix Relrefs
  content/operate/rc/compatibility.md
  content/operate/rs/7.4/clusters/_index.md
  content/operate/rs/7.4/clusters/configure/_index.md
  content/operate/rs/7.4/databases/_index.md
  content/operate/rs/7.4/databases/configure/_index.md
  content/operate/rs/7.4/databases/connect/_index.md
  content/operate/rs/7.4/databases/connect/supported-clients-browsers.md
  content/operate/rs/7.4/databases/connect/test-client-connectivity.md
  content/operate/rs/7.4/references/cli-utilities/redis-cli/_index.md
  content/operate/rs/7.4/references/client_references/_index.md
  content/operate/rs/7.4/security/access-control/ldap/migrate-to-role-based-ldap.md
  content/operate/rs/databases/memory-performance/_index.md
  content/operate/rs/references/compatibility/_index.md
  content/operate/rs/references/compatibility/client-side-caching.md
  content/operate/rs/release-notes/rs-7-8-releases/rs-7-8-2-34.md
Labels: bug

#869 RC: Fix Easy create settings
  content/operate/rc/databases/create-database/create-essentials-database.md
  content/operate/rc/databases/create-database/create-pro-database-existing.md
  content/operate/rc/databases/create-database/create-pro-database-new.md
  static/images/rc/pro-easy-create-optimal-settings.png
  static/images/rc/pro-easy-create-size-throughput.png
Labels: rc

#783 RS: Reconnect clients to apply OSS Cluster API config changes
  content/operate/rs/databases/configure/oss-cluster-api.md
Labels: rs

#887 DEV: add definition for NOSTOPWORDS to FT.SEARCH command page
  content/commands/ft.search/index.md
Labels: bug, dev

#890 RS: Update old download links to avoid redirects
  content/integrate/redisvl/overview/install.md
  content/operate/rs/7.4/installing-upgrading/quickstarts/redis-enterprise-software-quickstart.md
  content/operate/rs/7.4/references/rest-api/requests/modules/_index.md
  content/operate/rs/installing-upgrading/quickstarts/redis-enterprise-software-quickstart.md
  content/operate/rs/references/rest-api/requests/modules/_index.md
  content/operate/rs/release-notes/rs-6-2-18-releases/rs-6-2-18-49.md
  content/operate/rs/release-notes/rs-6-2-18-releases/rs-6-2-18-58.md
  content/operate/rs/release-notes/rs-6-2-18-releases/rs-6-2-18-65.md
  content/operate/rs/release-notes/rs-6-2-18-releases/rs-6-2-18-70.md
  content/operate/rs/release-notes/rs-6-4-2-releases/_index.md
  content/operate/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-103.md
  content/operate/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-110.md
  content/operate/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-115.md
  content/operate/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-30.md
  content/operate/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-43.md
  content/operate/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-61.md
  content/operate/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-69.md
  content/operate/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-81.md
  content/operate/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-94.md
  content/operate/rs/release-notes/rs-7-2-4-releases/_index.md
  content/operate/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-105.md
  content/operate/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-109.md
  content/operate/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-52.md
  content/operate/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-64.md
  content/operate/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-72.md
  content/operate/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-92.md
  content/operate/rs/release-notes/rs-7-4-2-releases/_index.md
  content/operate/rs/release-notes/rs-7-4-2-releases/rs-7-4-2-104.md
  content/operate/rs/release-notes/rs-7-4-2-releases/rs-7-4-2-126.md
  content/operate/rs/release-notes/rs-7-4-2-releases/rs-7-4-2-129.md
  content/operate/rs/release-notes/rs-7-4-2-releases/rs-7-4-2-169.md
  content/operate/rs/release-notes/rs-7-4-2-releases/rs-7-4-2-216.md
  content/operate/rs/release-notes/rs-7-4-2-releases/rs-7-4-2-54.md
  content/operate/rs/release-notes/rs-7-4-2-releases/rs-7-4-6-102.md
  content/operate/rs/release-notes/rs-7-4-2-releases/rs-7-4-6-22.md
  content/operate/rs/release-notes/rs-7-4-2-releases/rs-7-4-6-77.md
  content/operate/rs/release-notes/rs-7-8-releases/_index.md
  content/operate/rs/release-notes/rs-7-8-releases/rs-7-8-2-34.md
Labels: rs

#829 DOC-4510 RDI add_field and remove_field job file examples
  content/integrate/redis-data-integration/data-pipelines/transform-examples/redis-add-field-example.md
  content/integrate/redis-data-integration/data-pipelines/transform-examples/redis-remove-field-example.md
Labels: rdi

#882 DOC-4561 fixes for RDI Helm docs
  content/integrate/redis-data-integration/installation/install-k8s.md
Labels: rdi

#897 DOC-4568 added map transform example page
  content/integrate/redis-data-integration/data-pipelines/transform-examples/map-example.md
Labels: rdi

#892 K8s: Relref fixes
  content/operate/kubernetes/7.4.6/faqs/_index.md
  content/operate/kubernetes/7.4.6/re-clusters/multi-namespace.md
  content/operate/kubernetes/7.4.6/re-databases/db-controller.md
  content/operate/kubernetes/upgrade/_index.md
Labels: bug

#898 DEV: add axes to pipeline chart
  content/develop/use/pipelining/pipeline_iops.png
Labels: dev

#899 DOC-4578 fixed broken links
  content/integrate/redis-data-integration/data-pipelines/transform-examples/redis-add-field-example.md
  content/integrate/redis-data-integration/data-pipelines/transform-examples/redis-remove-field-example.md
Labels: rdi

#884 Update connect.md
  content/develop/clients/lettuce/connect.md
Labels: dev

#896 RS: Fix DB names in rladmin upgrade examples to correctly follow DB naming rules
  content/operate/oss_and_stack/stack-with-enterprise/install/upgrade-module.md
Labels: rs

#875 Add infra for lettuce examples
  build/components/component.py
  config.toml
  data/components/go_redis.json
  data/components/index.json
  data/components/jedis.json
  data/components/lettuce_async.json
  data/components/lettuce_reactive.json
  data/components/node_redis.json
  data/components/nredisstack.json
  data/components/redis_py.json
  data/components/redis_vl.json
  layouts/partials/tabbed-clients-example.html
Labels: infrastructure

#904 DOC-4579 RDI: improve hardware sizing info
  content/integrate/redis-data-integration/installation/install-vm.md
Labels: rdi

#903 Update supported-platforms-embed.md
  content/embeds/supported-platforms-embed.md
Labels: rs

#872 flush-commands-docs
  content/commands/flushall/index.md
  content/commands/flushdb/index.md
Labels: dev

#895 RS: Add banner to RS 7.4 versioned docs
  content/operate/rs/7.4/_index.md
Labels: rs

#900 RS: Fix replication description
  content/operate/rs/databases/durability-ha/_index.md
Labels: rs

#901 RS: Explain *node's meaning in rladmin status output
  content/operate/rs/references/cli-utilities/rladmin/status.md
Labels: rs

#910 RS: Clarify Prometheus v1 metrics are still available
  content/integrate/prometheus-with-redis-enterprise/prometheus-metrics-v1-to-v2.md
  content/operate/rs/release-notes/rs-7-8-releases/_index.md
  content/operate/rs/release-notes/rs-7-8-releases/rs-7-8-2-34.md
Labels: rs

#914 DOC-4586 added K8s commands to set secrets
  content/integrate/redis-data-integration/data-pipelines/deploy.md
Labels: rdi

#916 DOC-4588 fixed layout links to old develop/connect section
  layouts/home.html
  layouts/partials/tabs/wrapper.html
Labels: bug

#889 RC: Version Management Phase A
  content/embeds/rc-version-upgrade.md
  content/operate/rc/changelog/july-2024.md
  content/operate/rc/changelog/november-2024.md
  content/operate/rc/subscriptions/view-pro-subscription.md
  static/images/rc/button-version-upgrade.png
  static/images/rc/version-upgrade-request.png
Labels: rc

#908 DEV: add new what's new page
  content/develop/whats-new/index.md
Labels: dev

#917 DEV: add db analysis caveat
  content/develop/tools/insight/_index.md
Labels: dev, ri

#918 RS: Fix crdb-cli task cancel syntax
  content/operate/rs/7.4/references/cli-utilities/crdb-cli/task/cancel.md
  content/operate/rs/references/cli-utilities/crdb-cli/task/cancel.md
Labels: rs

#923 RS: Add Sentinel known issue to 7.8.2-34 release notes
  content/operate/rs/release-notes/rs-7-8-releases/_index.md
  content/operate/rs/release-notes/rs-7-8-releases/rs-7-8-2-34.md
Labels: rs

#921 K8s: add versioning banner
  content/operate/kubernetes/7.4.6/_index.md
  content/operate/kubernetes/deployment/_index.md
  content/operate/kubernetes/upgrade/_index.md
Labels: k8s

#907 DOC-4560 pipeline/transaction examples page
  content/develop/clients/redis-py/transpipe.md
Labels: do not merge yet

#927 DOC-4598 updated K8s secrets commands based on feedback
  content/integrate/redis-data-integration/data-pipelines/deploy.md
Labels: bug, rdi

#928 DOC-4597 removed obsolete bits about automatic RDI DB creation
  content/integrate/redis-data-integration/installation/install-k8s.md
  content/integrate/redis-data-integration/installation/install-vm.md
  content/integrate/redis-data-integration/quick-start-guide.md
Labels: bug, rdi
