Repository redis/docs, pull requests merged in 2024-08, with the labels that each got.

#505 DEV: fix headings in indexing page
  content/develop/use/patterns/indexes/index.md
Labels: bug

#506 DEV: update RediSearch release notes
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.6-release-notes.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.8-release-notes.md
Labels: bug

#508 RS: REST API reference to change CM UI time zone
  content/operate/rs/references/rest-api/objects/cm_settings.md
  content/operate/rs/references/rest-api/requests/cm_settings/_index.md
Labels: rs

#511 RS: Change 7.4.2 to 7.4 on release notes index page
  content/operate/rs/release-notes/rs-7-4-2-releases/_index.md
Labels: rs

#524 DEV: add note about Redis Copilot to main search page
  content/develop/interact/search-and-query/_index.md
Labels: dev

#525 DEV: fix toc issue on several pages
  content/develop/connect/cli.md
  content/develop/reference/modules/modules-native-types.md
  content/develop/reference/sentinel-clients.md
  content/develop/use/patterns/indexes/index.md
Labels: bug

#528 DEV/RI: add note about INFO access requirement
  content/develop/connect/insight/_index.md
Labels: dev, ri

#536 RS: Update EOL in supported platforms table
  content/embeds/supported-platforms-embed.md
Labels: rs

#537 DOC-4067 added FAQ and note about harmless OOM message
  content/integrate/redis-data-integration/ingest/_index.md
  content/integrate/redis-data-integration/ingest/architecture.md
  content/integrate/redis-data-integration/ingest/faq.md
Labels: rdi

#539 DEV: add annotations for RediSearch v2.10
  content/commands/ft.create/index.md
  content/commands/ft.search/index.md
  content/develop/interact/search-and-query/advanced-concepts/stemming.md
  content/develop/interact/search-and-query/advanced-concepts/vectors.md
  content/develop/interact/search-and-query/indexing/_index.md
  content/develop/interact/search-and-query/query/exact-match.md
  content/develop/interact/search-and-query/query/geo-spatial.md
Labels: dev

#507 RS: Update log rotation default config to reduce filling disk space with logs
  content/operate/rs/clusters/logging/log-security.md
Labels: rs

#512 RS: Clarify upgrade paths note in release notes
  content/operate/rs/release-notes/rs-7-4-2-releases/_index.md
  content/operate/rs/release-notes/rs-7-4-2-releases/rs-7-4-6-22.md
Labels: rs

#544 RS: Add cluster_wd exporter port 3349 to reserved ports
  content/operate/rs/networking/port-configurations.md
Labels: rs

#500 DEV: add new docs for RDI in Redis Insight feature
  content/develop/connect/insight/_index.md
  content/develop/connect/insight/copilot-faq.md
  content/develop/connect/insight/debugging.md
  content/develop/connect/insight/images/ri-rdi-add-endpoint1.png
  content/develop/connect/insight/images/ri-rdi-add-endpoint2.png
  content/develop/connect/insight/images/ri-rdi-endpoint-added.png
  content/develop/connect/insight/images/ri-rdi-job-editor-template.png
  content/develop/connect/insight/images/ri-rdi-pl-dl.png
  content/develop/connect/insight/images/ri-rdi-pl-dryrun.png
  content/develop/connect/insight/images/ri-rdi-pl-editor-autoc.png
  content/develop/connect/insight/images/ri-rdi-pl-editor-dlg.png
  content/develop/connect/insight/images/ri-rdi-pl-editor-errs.png
  content/develop/connect/insight/images/ri-rdi-pl-editor-minibuttons.png
  content/develop/connect/insight/images/ri-rdi-pl-editor-sql-minie.png
  content/develop/connect/insight/images/ri-rdi-pl-editor-template.png
  content/develop/connect/insight/images/ri-rdi-pl-start.png
  content/develop/connect/insight/images/ri-rdi-pl-test-cxn.png
  content/develop/connect/insight/images/ri-rdi-pl-unsaved.png
  content/develop/connect/insight/images/ri-rdi-stats-view.png
  content/develop/connect/insight/rdi-connector.md
  content/develop/connect/insight/release-notes/_index.md
  content/develop/connect/insight/tutorials/insight-stream-consumer.md
Labels: ri

#492 Create v.2.54.0.md
  content/develop/connect/insight/release-notes/v.2.54.0.md
Labels: ri

#538 K8s: Roosevelt maint 2 release notes
  content/operate/kubernetes/release-notes/7-2-4-releases/7-2-4-12-08-2024.md
Labels: k8s, release-branch

#548 RS: Add default_oss_sharding policy to REST API and rladmin references
  content/operate/rs/references/cli-utilities/rladmin/tune.md
  content/operate/rs/references/rest-api/objects/cluster_settings.md
Labels: rs

#552 K8s: release notes fix -105 corrected to -109
  content/operate/kubernetes/release-notes/7-2-4-releases/7-2-4-12-08-2024.md
Labels: bug

#551 DOC-4130 added warning about nm-cloud-setup.service to installer page
  content/integrate/redis-data-integration/ingest/installation/_index.md
Labels: rdi

#559 Broken links k8s
  content/operate/kubernetes/active-active/create-aa-crdb-cli.md
  content/operate/kubernetes/deployment/openshift/openshift-cli.md
  content/operate/kubernetes/re-clusters/auto-tiering.md
  content/operate/kubernetes/re-databases/db-controller.md
  content/operate/kubernetes/security/manage-rec-credentials.md
  content/operate/kubernetes/upgrade/openshift-cli.md
  content/operate/kubernetes/upgrade/upgrade-redis-cluster.md
Labels: bug

#555 RS: Database tags in CM UI
  content/operate/rs/databases/configure/db-tags.md
  static/images/rs/buttons/edit-db-tags-button.png
  static/images/rs/screenshots/databases/add-db-tags-button.png
  static/images/rs/screenshots/databases/edit-db-tags-button-location.png
  static/images/rs/screenshots/databases/manage-db-tags-dialog-suggestions.png
  static/images/rs/screenshots/databases/view-db-list-tags.png
Labels: rs

#569 OP: add RediSearch v2.10.6 release notes
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.10-release-notes.md
Labels: dev

#567 DOC-4140 add release notes for RDI v1.2.8
  content/integrate/redis-data-integration/ingest/release-notes/rdi-1-2-8.md
Labels: rdi

#573 DOC-4140 updated file weight to bring latest to top
  content/integrate/redis-data-integration/ingest/release-notes/rdi-1-2-8.md
Labels: rdi

#568 DEV: update Ubuntu/Debian installation instructions
  content/operate/oss_and_stack/install/install-redis/_index.md
  content/operate/oss_and_stack/install/install-redis/install-redis-on-linux.md
  content/operate/oss_and_stack/install/install-stack/linux.md
Labels: bug

#581 OP: add RediSearch v2.10.6 release notes
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.8-release-notes.md
Labels: dev

#595 OP: update RediSearch release notes for 2.8.17
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.8-release-notes.md
Labels: dev

#601 add query performance factor screenshot
  content/operate/rc/databases/configuration/advanced-capabilities.md
  static/images/rc/database-details-query-performance-factor-pro.png
Labels: rc

#586 DOC-4169 add usage examples of secret config props
  content/integrate/redis-data-integration/ingest/data-pipelines/data-pipelines.md
Labels: rdi

#602 RC: Replace app.redislabs.com with cloud.redis.io
  content/embeds/rc-create-db-first-steps.md
  content/integrate/amazon-bedrock/create-knowledge-base.md
  content/integrate/amazon-bedrock/set-up-redis.md
  content/integrate/confluent-with-redis-cloud/_index.md
  content/integrate/prometheus-with-redis-cloud/_index.md
  content/integrate/pulumi-provider-for-redis-cloud/get-started.md
  content/integrate/redis-data-integration/ingest/installation/_index.md
  content/integrate/terraform-provider-for-redis-cloud/get-started.md
  content/operate/rc/_index.md
  content/operate/rc/accounts/account-settings.md
  content/operate/rc/accounts/user-profile.md
  content/operate/rc/api/examples/audit-system-logs.md
  content/operate/rc/api/get-started/enable-the-api.md
  content/operate/rc/api/get-started/manage-api-keys.md
  content/operate/rc/billing-and-payments.md
  content/operate/rc/changelog/january-2024.md
  content/operate/rc/cloud-integrations/aws-cloud-accounts/_index.md
  content/operate/rc/cloud-integrations/aws-cloud-accounts/subscription-whitelist.md
  content/operate/rc/cloud-integrations/aws-marketplace/_index.md
  content/operate/rc/cloud-integrations/gcp-marketplace/_index.md
  content/operate/rc/databases/_index.md
  content/operate/rc/databases/back-up-data.md
  content/operate/rc/databases/configuration/advanced-capabilities.md
  content/operate/rc/databases/delete-database.md
  content/operate/rc/databases/import-data.md
  content/operate/rc/databases/migrate-databases.md
  content/operate/rc/databases/monitor-performance.md
  content/operate/rc/databases/tag-database.md
  content/operate/rc/databases/view-edit-database.md
  content/operate/rc/logs-reports/system-logs.md
  content/operate/rc/rc-quickstart.md
  content/operate/rc/security/access-control/data-access-control/configure-acls.md
  content/operate/rc/security/access-control/data-access-control/create-assign-users.md
  content/operate/rc/security/access-control/data-access-control/create-roles.md
  content/operate/rc/security/access-control/social-login.md
  content/operate/rc/security/aws-transit-gateway.md
  content/operate/rc/security/cidr-whitelist.md
  content/operate/rc/security/database-security/tls-ssl.md
  content/operate/rc/security/private-service-connect.md
  content/operate/rc/security/vpc-peering.md
  content/operate/rc/subscriptions/maintenance/set-maintenance-windows.md
  content/operate/rc/subscriptions/view-essentials-subscription/_index.md
  content/operate/rc/subscriptions/view-pro-subscription.md
Labels: rc

#604 RC: Add Transit Gateway attachment resource to Terraform
  content/integrate/terraform-provider-for-redis-cloud/_index.md
Labels: rc

#611 DEV: fix typo in HFE example
  content/develop/data-types/hashes.md
Labels: bug, dev

#612 DEV: document the ADDSCORES option to FT.AGGREGATE
  content/commands/ft.aggregate/index.md
Labels: dev

#553 RC: resilient apps tip
  content/operate/rc/subscriptions/maintenance/_index.md
Labels: rc

#615 DOC-4206 add section about contexts
  content/integrate/redis-data-integration/ingest/quick-start-guide.md
Labels: rdi

#605 RC: Vercel integration
  content/operate/rc/cloud-integrations/vercel.md
  static/images/rc/vercel-connect-project-button.png
  static/images/rc/vercel-connect-project.png
  static/images/rc/vercel-create-db-select-plan.png
  static/images/rc/vercel-open-in-redis-cloud.png
  static/images/rc/vercel-redis-cloud-partners.png
  static/images/rc/vercel-status-available.png
  static/images/rc/vercel-storage-create-database-button.png
Labels: rc

#618 DOC-4210 added baseURL to client quickstart links
  layouts/partials/tabs/wrapper.html
Labels: bug

#621 K8s: change scaling note to warning
  content/operate/kubernetes/recommendations/sizing-on-kubernetes.md
Labels: k8s

#609 DOC-4131 added note about localhost IP change
  content/integrate/redis-data-integration/ingest/data-pipelines/data-pipelines.md
  content/integrate/redis-data-integration/ingest/installation/_index.md
Labels: rdi

#622 RS: Fix broken relref
  content/operate/rs/databases/configure/_index.md
Labels: rs

#623 RC: Update first sentence of landing page to remove redundant text
  content/operate/rc/_index.md
Labels: rc
