Repository redis/docs, pull requests merged in 2024-06, with the labels that each got.

#274 K8s: DOC-2573 AA upgrade notes
  content/operate/kubernetes/upgrade/upgrade-redis-cluster.md
Labels: k8s

#282 Remove duplicate starting sentence
  content/operate/rc/api/get-started/manage-tasks.md
Labels: rc

#283 DEV: delete bad link from sorted set page
  content/develop/data-types/sorted-sets.md
Labels: bug

#289 DEV triggers and functions deprecation
  content/apis/_index.md
  content/commands/tfcall/index.md
  content/commands/tfcall/syntax.svg
  content/commands/tfcallasync/index.md
  content/commands/tfcallasync/syntax.svg
  content/commands/tfunction-delete/index.md
  content/commands/tfunction-delete/syntax.svg
  content/commands/tfunction-list/index.md
  content/commands/tfunction-list/syntax.svg
  content/commands/tfunction-load/index.md
  content/commands/tfunction-load/syntax.svg
  content/develop/interact/programmability/triggers-and-functions/concepts/_index.md
  content/develop/interact/programmability/triggers-and-functions/concepts/triggers/_index.md
  content/operate/oss_and_stack/stack-with-enterprise/deprecated-features/triggers-and-functions/Configuration.md
  content/operate/oss_and_stack/stack-with-enterprise/deprecated-features/triggers-and-functions/Debugging.md
  content/operate/oss_and_stack/stack-with-enterprise/deprecated-features/triggers-and-functions/Development.md
  content/operate/oss_and_stack/stack-with-enterprise/deprecated-features/triggers-and-functions/Examples.md
  content/operate/oss_and_stack/stack-with-enterprise/deprecated-features/triggers-and-functions/Known_Limitations.md
  content/operate/oss_and_stack/stack-with-enterprise/deprecated-features/triggers-and-functions/Quick_Start_CLI.md
  content/operate/oss_and_stack/stack-with-enterprise/deprecated-features/triggers-and-functions/Quick_Start_RI.md
  content/operate/oss_and_stack/stack-with-enterprise/deprecated-features/triggers-and-functions/_index.md
  content/operate/oss_and_stack/stack-with-enterprise/deprecated-features/triggers-and-functions/concepts/Binary_Data.md
  content/operate/oss_and_stack/stack-with-enterprise/deprecated-features/triggers-and-functions/concepts/Cluster_Support.md
  content/operate/oss_and_stack/stack-with-enterprise/deprecated-features/triggers-and-functions/concepts/Function_Flags.md
  content/operate/oss_and_stack/stack-with-enterprise/deprecated-features/triggers-and-functions/concepts/JavaScript_API.md
  content/operate/oss_and_stack/stack-with-enterprise/deprecated-features/triggers-and-functions/concepts/Library_Configuration.md
  content/operate/oss_and_stack/stack-with-enterprise/deprecated-features/triggers-and-functions/concepts/RESP_JS_Conversion.md
  content/operate/oss_and_stack/stack-with-enterprise/deprecated-features/triggers-and-functions/concepts/Sync_Async.md
  content/operate/oss_and_stack/stack-with-enterprise/deprecated-features/triggers-and-functions/concepts/_index.md
  content/operate/oss_and_stack/stack-with-enterprise/deprecated-features/triggers-and-functions/concepts/triggers/KeySpace_Triggers.md
  content/operate/oss_and_stack/stack-with-enterprise/deprecated-features/triggers-and-functions/concepts/triggers/Stream_Triggers.md
  content/operate/oss_and_stack/stack-with-enterprise/deprecated-features/triggers-and-functions/concepts/triggers/User_Functions.md
  content/operate/oss_and_stack/stack-with-enterprise/deprecated-features/triggers-and-functions/concepts/triggers/_index.md
  content/operate/oss_and_stack/stack-with-enterprise/deprecated-features/triggers-and-functions/images/tf-rdi-0.png
  content/operate/oss_and_stack/stack-with-enterprise/deprecated-features/triggers-and-functions/images/tf-rdi-1.png
  content/operate/oss_and_stack/stack-with-enterprise/deprecated-features/triggers-and-functions/images/tf-rdi-2.png
  content/operate/oss_and_stack/stack-with-enterprise/deprecated-features/triggers-and-functions/images/tf-rdi-3.png
  content/operate/oss_and_stack/stack-with-enterprise/deprecated-features/triggers-and-functions/images/tf-rdi-3a.png
  content/operate/oss_and_stack/stack-with-enterprise/deprecated-features/triggers-and-functions/images/tf-rdi-4.png
  content/operate/oss_and_stack/stack-with-enterprise/deprecated-features/triggers-and-functions/images/tf-rdi-5.png
  content/operate/oss_and_stack/stack-with-enterprise/enterprise-capabilities.md
  content/operate/oss_and_stack/stack-with-enterprise/triggers-functions/_index.md
  content/operate/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-52.md
  layouts/commands/list.html
Labels: do not merge yet, SAR 7.4

#265 DEV: time series changes for 7.4 RC1
  content/commands/ts.add/index.md
  content/commands/ts.alter/index.md
  content/commands/ts.create/index.md
  content/commands/ts.decrby/index.md
  content/commands/ts.incrby/index.md
  content/commands/ts.madd/index.md
  content/develop/data-types/timeseries/configuration.md
Labels: do not merge yet, SAR 7.4

#238 DEV: update keyspace notifications page for new hash commands
  content/commands/info/index.md
  content/develop/use/keyspace-notifications.md
Labels: do not merge yet, SAR 7.4

#217 DEV: new hash pages
  content/commands/hexpire/index.md
  content/commands/hexpire/syntax.svg
  content/commands/hexpireat/index.md
  content/commands/hexpireat/syntax.svg
  content/commands/hexpiretime/index.md
  content/commands/hexpiretime/syntax.svg
  content/commands/hpersist/index.md
  content/commands/hpersist/syntax.svg
  content/commands/hpexpire/index.md
  content/commands/hpexpire/syntax.svg
  content/commands/hpexpireat/index.md
  content/commands/hpexpireat/syntax.svg
  content/commands/hpexpiretime/index.md
  content/commands/hpexpiretime/syntax.svg
  content/commands/hpttl/index.md
  content/commands/hpttl/syntax.svg
  content/commands/httl/index.md
  content/commands/httl/syntax.svg
  content/develop/data-types/hashes.md
  data/commands.json
  data/resp2_replies.json
  data/resp3_replies.json
Labels: do not merge yet, SAR 7.4

#287 DEV: last minute 7.4 RC1 updates
  content/develop/connect/cli.md
  content/develop/reference/modules/modules-api-ref.md
  content/operate/oss_and_stack/management/config-file.md
  content/operate/oss_and_stack/management/config.md
Labels: do not merge yet, SAR 7.4

#286 RC Triggers and Functions deprecation
  content/operate/rc/changelog/august-2023.md
  content/operate/rc/changelog/may-2024.md
  content/operate/rc/subscriptions/upgrade-essentials-pro.md
Labels: do not merge yet

#304 Sundry link fixes
  content/develop/data-types/hashes.md
  content/develop/use/keyspace-notifications.md
  content/operate/rc/changelog/august-2023.md
  content/operate/rs/security/certificates/ocsp-stapling.md
Labels: bug

#303 DEV: add new quick start guide for RAG
  content/develop/get-started/rag.md
Labels: documentation, dev

#314 DEV: update link in JSON section
  content/operate/oss_and_stack/stack-with-enterprise/json/_index.md
Labels: bug

#318 DOC-3887 fixed endpoint URL bug
  content/integrate/redis-data-integration/ingest/observability.md
Labels: documentation

#324 RC: Mention that target db gets flushed during initial A/P sync
  content/operate/rc/databases/migrate-databases.md
Labels: bug, rc

#317 RC: Update View RedisLabsInstanceRolePolicy.json
  content/operate/rc/cloud-integrations/aws-cloud-accounts/iam-resources/aws-console.md
Labels: bug, rc

#312 K8s: change pvc warning to link to new feature
  content/operate/kubernetes/re-clusters/expand-pvc.md
  content/operate/kubernetes/recommendations/persistent-volumes.md
  content/operate/kubernetes/recommendations/sizing-on-kubernetes.md
Labels: bug, k8s

#315 DEV(RI): add documentation for Redis Copilot
  content/develop/connect/insight/_index.md
  content/develop/connect/insight/copilot-faq.md
  content/develop/connect/insight/images/copilot-example.png
Labels: ri

#268 DEV: updated search content
  content/commands/ft.config-get/index.md
  content/commands/ft.create/index.md
  content/commands/ft.search/index.md
  content/develop/interact/search-and-query/advanced-concepts/dialects.md
  content/develop/interact/search-and-query/advanced-concepts/query_syntax.md
  content/develop/interact/search-and-query/advanced-concepts/stemming.md
  content/develop/interact/search-and-query/advanced-concepts/vectors.md
  content/develop/interact/search-and-query/basic-constructs/configuration-parameters.md
  content/develop/interact/search-and-query/basic-constructs/field-and-type-options.md
  content/develop/interact/search-and-query/query/combined.md
  content/develop/interact/search-and-query/query/exact-match.md
  content/develop/interact/search-and-query/query/geo-spatial.md
  content/operate/oss_and_stack/stack-with-enterprise/search/config.md
Labels: Search 2.10-rc1

#199 MOD-7009: Search and Query - Empty indexing
  content/commands/ft.create/index.md
  content/develop/interact/search-and-query/query/combined.md
Labels: Search 2.10-rc1

#331 DEV: fix broken link on RI page
  content/develop/connect/insight/_index.md
Labels: bug, dev

#316 RC: Terraform now supports Essentials
  content/integrate/terraform-provider-for-redis-cloud/_index.md
  content/operate/rc/changelog/june-2024.md
Labels: rc

#329 DOC-3901 add advanced props section to config.yaml docs
  content/integrate/redis-data-integration/ingest/data-pipelines/data-pipelines.md
Labels: documentation

#333 K8s: fix relref
  content/operate/kubernetes/recommendations/sizing-on-kubernetes.md
Labels: bug, k8s

#332 DEV: fix link on Redis Stack and Redis Enterprise page
  content/operate/oss_and_stack/stack-with-enterprise/_index.md
Labels: bug, dev

#337 DOC-3907 added transform info lost from the old docs
  content/integrate/redis-data-integration/ingest/data-pipelines/data-pipelines.md
Labels: documentation

#336 K8s: add K8s category to relevant RS pages
  content/operate/kubernetes/active-active/create-reaadb.md
  content/operate/kubernetes/re-clusters/connect-prometheus-operator.md
  content/operate/rs/clusters/configure/rack-zone-awareness.md
  content/operate/rs/clusters/monitoring/_index.md
  content/operate/rs/databases/active-active/_index.md
  content/operate/rs/databases/memory-performance/eviction-policy.md
  content/operate/rs/databases/recover.md
  content/operate/rs/installing-upgrading/install/plan-deployment/hardware-requirements.md
  content/operate/rs/installing-upgrading/install/plan-deployment/persistent-ephemeral-storage.md
Labels: k8s

#334 RC: Supported Cloud providers regions
  content/operate/rc/cloud-archive.md
  content/operate/rc/supported-regions.md
Labels: rc

#343 RC: Add new Data sources and resources to Terraform doc
  content/integrate/terraform-provider-for-redis-cloud/_index.md
Labels: rc

#347 RC: Add private offer step to AWS marketplace docs
  content/operate/rc/cloud-integrations/aws-marketplace/_index.md
Labels: rc

#335 DEV: add some PM content to the hash page
  content/develop/data-types/hashes.md
Labels: dev

#342 Convert step names in code examples to lowercase
  build/components/example.py
Labels: dev

#357 DEV: add link from FT.AGGREGATE page to APPLY expressions reference page
  content/commands/ft.aggregate/index.md
Labels: dev

#358 DEV: change sub-title on JSON main page
  content/develop/data-types/json/_index.md
Labels: dev

#352 fix: commands pages take up full width available
  layouts/commands/list.html
  layouts/commands/single.html
Labels: ui

#366 SITE-WIDE: fix bug that prevented Node.js examples from displaying
  config.toml
Labels: bug

#361 DEV: update keyspace notifications for HFE commands
  content/develop/use/keyspace-notifications.md
Labels: do not merge yet, CE 7.4

#360 DEV: update modules-api-ref.md for 7.4-rc2
  content/develop/reference/modules/modules-api-ref.md
Labels: do not merge yet, CE 7.4

#359 DEV: modify return values for HFE commands
  content/commands/hexpire/index.md
  content/commands/hexpireat/index.md
  content/commands/hexpiretime/index.md
  content/commands/hpersist/index.md
  content/commands/hpexpire/index.md
  content/commands/hpexpireat/index.md
  content/commands/hpexpiretime/index.md
  content/commands/hpttl/index.md
  content/commands/httl/index.md
Labels: do not merge yet, CE 7.4

#373 doc: add "recorded-first-entry-id" to xinfo stream documentation examples
  content/commands/xinfo-stream/index.md
Labels: bug, dev

#353 Doc 3910 db specific connect properties
  content/integrate/redis-data-integration/ingest/data-pipelines/data-pipelines.md
  content/integrate/redis-data-integration/ingest/installation/_index.md
Labels: documentation

#376 DOC-3917 added silent install docs
  content/integrate/redis-data-integration/ingest/installation/_index.md
  content/integrate/redis-data-integration/ingest/reference/cli/redis-di-install.md
Labels: documentation

#374 Update vector db quickstart guide
  content/develop/get-started/vector-database.md
Labels: enhancement, dev

#375 AWS and GCP Marketplace integrations private offer fixes
  content/operate/rc/cloud-integrations/aws-marketplace/_index.md
  content/operate/rc/cloud-integrations/gcp-marketplace/_index.md
Labels: rc

#378 DEV: fix two minor bugs in dev docs
  content/commands/ft.aliasadd/index.md
  content/develop/interact/search-and-query/advanced-concepts/vectors.md
Labels: bug, dev
