Repository redis/docs, pull requests merged in 2024-04, with the labels that each got.

#20 LRC-160: cleanup build process
  build/components/component.py
Labels: do not merge yet

#140 RC: Replace API lifecycle diagram and RC: Replace OSS/open-source Redis in RC docs
  content/embeds/oss-cluster-api-intro.md
  content/embeds/rc-rs-oss-compatibility.md
  content/operate/rc/compatibility.md
  content/operate/rc/databases/configuration/clustering.md
  content/operate/rc/databases/connect.md
  content/operate/rc/databases/create-database/create-pro-database-existing.md
  content/operate/rc/databases/create-database/create-pro-database-new.md
  content/operate/rc/databases/view-edit-database.md
  content/operate/rc/security/access-control/data-access-control/configure-acls.md
  content/operate/rc/security/access-control/data-access-control/role-based-access-control.md
  content/operate/rc/security/private-service-connect.md
  static/images/rv/api/processing-and-provisioning.png
Labels: rc

#143 RC: Remove subscription name from Create Pro subscription
  content/operate/rc/databases/create-database/create-pro-database-new.md
  static/images/rc/create-flexible-sub-active-active-on.png
  static/images/rc/subscription-new-flexible-review.png
  static/images/rc/subscription-new-flexible-setup-general.png
Labels: rc

#147 RC: SAML Domain Verification - integration guides
  content/operate/rc/security/access-control/saml-sso/saml-integration-auth0.md
  content/operate/rc/security/access-control/saml-sso/saml-integration-aws-identity-center.md
  content/operate/rc/security/access-control/saml-sso/saml-integration-azure-ad.md
  content/operate/rc/security/access-control/saml-sso/saml-integration-google.md
  content/operate/rc/security/access-control/saml-sso/saml-integration-okta-generic.md
  content/operate/rc/security/access-control/saml-sso/saml-integration-okta-org2org.md
  content/operate/rc/security/access-control/saml-sso/saml-integration-ping-identity.md
  static/images/rc/saml/sm_saml_3.png
  static/images/rc/saml/sm_saml_8.png
  static/images/rc/saml/sm_saml_9.png
Labels: rc

#145 RC Security reorg: Split CIDR allow list into a Database CIDIR allow list and Subscription CIDR allow list
  content/operate/rc/cloud-integrations/aws-cloud-accounts/subscription-whitelist.md
  content/operate/rc/security/cidr-whitelist.md
Labels: rc

#153 Changed #dataset-size to link to the memory limit section
  content/operate/rc/databases/configuration/clustering.md
Labels: bug, rc

#131 RC: Nano billing unit
  content/embeds/rc-pro-use-cases-billing-units.md
  content/operate/rc/changelog/april-2024.md
Labels: do not merge yet, rc
