Repository redis/docs, pull requests merged in 2024-12, with the labels that each got.

#933 DOC-4605 added ingress controller details
  content/integrate/redis-data-integration/installation/install-k8s.md
Labels: rdi

#935 DOC-4607 added debezium_lob_encoded_placeholder prop to config.yaml
  content/integrate/redis-data-integration/data-pipelines/data-pipelines.md
Labels: rdi

#931 Create v.2.62.0.md
  content/develop/tools/insight/release-notes/v.2.62.0.md
Labels: ri

#939 Revert "RS: Add Sentinel known issue to 7.8.2-34 release notes"
  content/operate/rs/release-notes/rs-7-8-releases/_index.md
  content/operate/rs/release-notes/rs-7-8-releases/rs-7-8-2-34.md
Labels: rs

#350 Update config.md
  content/operate/oss_and_stack/stack-with-enterprise/timeseries/config.md
Labels: rs

#920 K8s: correct version number in supported distro page
  content/operate/kubernetes/reference/supported_k8s_distributions.md
Labels: bug, k8s

#925 RC: Change Connection wizard docs to include updated code examples
  content/operate/rc/databases/connect.md
  content/operate/rc/rc-quickstart.md
  static/images/rc/connection-wizard-clients.png
Labels: do not merge yet, rc

#919 RC: Logs viewer role
  content/operate/rc/api/get-started/_index.md
  content/operate/rc/api/get-started/enable-the-api.md
  content/operate/rc/api/get-started/manage-api-keys.md
  content/operate/rc/changelog/december-2024.md
  content/operate/rc/security/access-control/access-management.md
Labels: do not merge yet

#948 RS: 7.8.2 Dec maintenance release docs
  content/operate/rs/release-notes/rs-7-8-releases/rs-7-8-2-34.md
  content/operate/rs/release-notes/rs-7-8-releases/rs-7-8-2-60.md
Labels: rs

#955 RC: Fixing new Active-Active location
  content/operate/rc/databases/create-database/create-active-active-database.md
  content/operate/rc/databases/create-database/create-pro-database-new.md
  static/images/rc/create-flexible-sub-active-active-on.png
  static/images/rc/create-sub-active-active-regions.png
  static/images/rc/subscription-new-flexible-setup-advanced.png
  static/images/rc/subscription-new-flexible-setup-general.png
Labels: rc

#944 RS: Add static IP requirement
  content/embeds/hardware-requirements-embed.md
Labels: rs

#962 Fix Bloom documented formulas
  content/commands/bf.reserve/index.md
  content/develop/data-types/probabilistic/bloom-filter.md
Labels: bug, dev

#961 DEV: fix FT.SEARCH syntax
  content/commands/ft.search/index.md
Labels: bug, dev

#967 RC: Members can't create databases
  content/operate/rc/security/access-control/access-management.md
Labels: bug, rc

#960 DOC-4610 updated K8s install instructions
  content/integrate/redis-data-integration/installation/install-k8s.md
Labels: rdi

#954 DOC-4635 RDI release notes for v1.4.3
  content/integrate/redis-data-integration/release-notes/rdi-1-4-3.md
Labels: rdi

#971 DOC-4643 added warnings about clustered RDI DBs
  content/integrate/redis-data-integration/installation/install-k8s.md
  content/integrate/redis-data-integration/installation/install-vm.md
  content/integrate/redis-data-integration/quick-start-guide.md
Labels: rdi

#776 RS: Add umask requirements to install docs
  content/operate/rs/installing-upgrading/install/_index.md
Labels: rs

#938 DOC-4600 RDI instructions to prepare AWS Aurora PostgreSQL DB
  content/integrate/redis-data-integration/data-pipelines/prepare-dbs/aws-aur-pgsql.md
  static/images/rdi/ingest/prepsrc/aurora-pgsql/CreateDB6.jpg
  static/images/rdi/ingest/prepsrc/aurora-pgsql/CreateParamGroup.jpg
  static/images/rdi/ingest/prepsrc/aurora-pgsql/EditParamGroup.jpg
Labels: rdi

#775 RS: Fix comment out swap partitions example
  content/operate/rs/installing-upgrading/configuring/linux-swap.md
Labels: rs

#943 RS: Recommend different mount points for data & log files
  content/operate/rs/installing-upgrading/install/customize-install-directories.md
  content/operate/rs/installing-upgrading/install/plan-deployment/_index.md
Labels: rs

#978 OP: add gears v1.2.12 rns & fix link warning
  content/integrate/prometheus-with-redis-enterprise/observability.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisgears/redisgears-1.2-release-notes.md
Labels: bug, dev

#981 DEV: correct latency range
  content/commands/latency-histogram/index.md
Labels: bug, dev

#974 DOC-4647 updated supported sources table with AWS RDS details
  content/embeds/rdi-supported-source-versions.md
  content/integrate/redis-data-integration/_index.md
  content/integrate/redis-data-integration/architecture.md
Labels: rdi

#985 DEV: Add missing field definitions to CLIENT LIST page
  content/commands/client-list/index.md
Labels: bug, dev

#994 K8s: Fix links pointing to old commit
  content/operate/kubernetes/7.4.6/security/manage-rec-credentials.md
  content/operate/kubernetes/security/manage-rec-credentials.md
Labels: bug, k8s

#995 DEV: fix bug on BITPOS command page
  content/commands/bitpos/index.md
Labels: bug, dev

#950 RC: Redis Flex on Essentials Preview
  content/embeds/rc-create-db-first-steps.md
  content/embeds/rc-create-db-use-cases.md
  content/operate/rc/changelog/december-2024.md
  content/operate/rc/databases/create-database/_index.md
  content/operate/rc/databases/create-database/create-active-active-database.md
  content/operate/rc/databases/create-database/create-essentials-database.md
  content/operate/rc/databases/create-database/create-flex-database.md
  content/operate/rc/databases/create-database/create-pro-database-existing.md
  content/operate/rc/databases/create-database/create-pro-database-new.md
  content/operate/rc/subscriptions/view-essentials-subscription/essentials-plan-details.md
  static/images/rc/create-database-flex-cloud-vendor.png
  static/images/rc/create-database-subscription-essentials.png
  static/images/rc/create-database-subscription-flex.png
  static/images/rc/create-database-subscription-pro-new.png
  static/images/rc/subscription-new-flex-tiers.png
Labels: do not merge yet, rc

#982 Release notes for Redis Insight v.2.64.0.md
  content/develop/tools/insight/release-notes/v.2.64.0.md
Labels: ri

#990 RS: Remove patch number from bundled module versions in recent release notes
  content/operate/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-115.md
  content/operate/rs/release-notes/rs-7-4-2-releases/rs-7-4-6-102.md
  content/operate/rs/release-notes/rs-7-4-2-releases/rs-7-4-6-77.md
  content/operate/rs/release-notes/rs-7-8-releases/rs-7-8-2-34.md
  content/operate/rs/release-notes/rs-7-8-releases/rs-7-8-2-60.md
Labels: rs

#996 RC: Clarify that monthly network cap applies over all databases in the plan
  content/operate/rc/subscriptions/view-essentials-subscription/essentials-plan-details.md
Labels: rc

#1000 CAPI: Consolidate database examples and add Essentials information
  content/operate/rc/api/_index.md
  content/operate/rc/api/examples/create-database.md
  content/operate/rc/api/examples/manage-subscriptions.md
  content/operate/rc/api/examples/update-database.md
Labels: rc

#980 RS: Add step to avoid removing a primary node last during rolling upgrade
  content/operate/rs/installing-upgrading/upgrading/upgrade-os.md
Labels: rs

#1006 RS: Add more info about viewing & managing slow log
  content/operate/rs/clusters/logging/redis-slow-log.md
Labels: rs

#986 DEV+RS: hash field limitation in RediSearch v2.10
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.10-release-notes.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisstack/redisstack-7.4-release-notes.md
  content/operate/rs/release-notes/rs-7-8-releases/_index.md
  content/operate/rs/release-notes/rs-7-8-releases/rs-7-8-2-34.md
  content/operate/rs/release-notes/rs-7-8-releases/rs-7-8-2-60.md
Labels: dev, rs

#1005 RS: 7.8.4 release docs
  content/operate/rs/references/rest-api/objects/cluster/_index.md
  content/operate/rs/references/rest-api/objects/user.md
  content/operate/rs/release-notes/rs-7-8-releases/_index.md
  content/operate/rs/release-notes/rs-7-8-releases/rs-7-8-4-18.md
Labels: do not merge yet, rs

#1011 RS: Add dry_run option for Redis ACL REST API to reference & 7.8.4 release notes
  content/operate/rs/references/rest-api/requests/redis_acls/_index.md
  content/operate/rs/release-notes/rs-7-8-releases/rs-7-8-4-18.md
Labels: rs

#1010 RS: Add missing filename option & examples to import DB REST API references
  content/operate/rs/references/rest-api/objects/bdb/dataset_import_sources.md
  content/operate/rs/references/rest-api/requests/bdbs/actions/import.md
Labels: rs

#991 K8s: Unicorn maintenance 3 release
  content/operate/kubernetes/release-notes/7-4-6-releases/7-4-6-6-dec24.md
Labels: k8s, next release

#1012 RS: Fix shard_key_regex format in REST API reference
  content/operate/rs/7.4/references/rest-api/objects/bdb/_index.md
  content/operate/rs/7.4/references/rest-api/objects/crdb/database_config.md
  content/operate/rs/references/rest-api/objects/bdb/_index.md
  content/operate/rs/references/rest-api/objects/crdb/database_config.md
Labels: rs
