Repository redis/docs, pull requests merged in 2024-10, with the labels that each got.

#722 DEV: add attribute type to the RESP3 spec.
  content/develop/reference/protocol-spec.md
Labels: dev

#700 Create v.2.58.0.md
  content/develop/connect/insight/release-notes/v.2.58.0.md
Labels: do not merge yet, ri

#724 DEV: redis search > redis query engine changes (first round)
  content/develop/connect/clients/client-side-caching.md
  content/develop/connect/insight/release-notes/v.2.56.0.md
  content/develop/data-types/json/_index.md
  content/develop/data-types/json/indexing_JSON.md
  content/develop/data-types/json/use_cases.md
  content/develop/data-types/sets.md
  content/develop/data-types/sorted-sets.md
  content/develop/get-started/document-database.md
  content/develop/get-started/vector-database.md
  content/develop/interact/_index.md
  content/develop/interact/search-and-query/_index.md
  content/develop/interact/search-and-query/administration/_index.md
  content/develop/interact/search-and-query/advanced-concepts/_index.md
  content/develop/interact/search-and-query/advanced-concepts/dialects.md
  content/develop/interact/search-and-query/advanced-concepts/query_syntax.md
  content/develop/interact/search-and-query/deprecated/development.md
  content/develop/interact/search-and-query/query-use-cases/_index.md
  content/integrate/redisvl/overview/cli.md
  content/integrate/redisvl/overview/install.md
  content/integrate/redisvl/user-guide/get-started.md
  content/integrate/redisvl/user-guide/json-v-hashes.md
  content/integrate/redisvl/user-guide/query-filter.md
  content/integrate/redisvl/user-guide/semantic-caching.md
  content/integrate/redisvl/user-guide/vectorizers.md
  content/operate/oss_and_stack/stack-with-enterprise/stack-quickstart.md
  layouts/commands/list.html
  layouts/home.html
Labels: dev

#726 DEV: fix Lua API right-side nav
  content/develop/interact/programmability/lua-api.md
Labels: bug, dev

#731 K8s: RN toc fix
  content/operate/kubernetes/release-notes/7-4-2-releases/7-4-2-12.md
  content/operate/kubernetes/release-notes/7-4-6-releases/_index.md
Labels: bug, k8s

#721 RC: Remove Graph from Redis Cloud Pro
  content/operate/rc/databases/configuration/advanced-capabilities.md
  content/operate/rc/databases/create-database/create-pro-database-existing.md
  content/operate/rc/databases/create-database/create-pro-database-new.md
  static/images/rc/database-details-modules-stack-free.png
  static/images/rc/database-details-redis-module-select-flexible.png
  static/images/rc/database-new-flexible.png
  static/images/rc/flexible-add-database-basic.png
Labels: do not merge yet, rc

#725 RC: Update tag minimum to 1 character
  content/embeds/rc-tags-tag-module.md
Labels: do not merge yet, rc

#727 DOC-4305 added opcode example
  content/integrate/redis-data-integration/data-pipelines/transform-examples/redis-opcode-example.md
Labels: rdi

#736 DOC-4352 removed mention of DB2
  content/integrate/redis-data-integration/faq.md
Labels: rdi

#694 RC: Cloud Search and Query changes
  content/operate/rc/databases/configuration/advanced-capabilities.md
  content/operate/rc/databases/create-database/create-pro-database-existing.md
  content/operate/rc/databases/create-database/create-pro-database-new.md
  static/images/rc/create-pro-db-settings-custom.png
Labels: rc

#744 DEV: amend Ubuntu install docs
  content/operate/oss_and_stack/install/install-redis/install-redis-on-linux.md
Labels: bug, dev

#689 DEV: add TCEs to query > aggregation page
  content/develop/interact/search-and-query/query/aggregation.md
Labels: do not merge yet, dev

#753 DEV: add Redis CE 7.4.x relnotes to site
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisce/_index.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisce/redisce-7.4-release-notes.md
Labels: dev

#749 DEV: replace hackers with racers on sorted sets page
  content/develop/data-types/sorted-sets.md
Labels: bug, dev

#747 Add PHP Redis extension
  content/develop/connect/clients/_index.md
Labels: dev

#730 RC: Add note to upgrade terraform provider to 1.8.1
  content/integrate/terraform-provider-for-redis-cloud/_index.md
Labels: do not merge yet, rc

#751 RC: CVE mention in changelog
  content/operate/rc/changelog/october-2024.md
Labels: rc

#752 RS: Update SELECT command compatibility notes
  content/operate/rs/references/compatibility/commands/connection.md
Labels: rs

#746 DEV: doc changes per RED-137284
  content/commands/info/index.md
  content/commands/memory-usage/index.md
Labels: dev

#711 RS: Configure query performance factor with CM UI
  content/operate/oss_and_stack/stack-with-enterprise/search/query-performance-factor.md
  static/images/rs/screenshots/databases/rs-config-query-performance-factor.png
Labels: rs

#702 RC: Restore 7.4 Pro Preview
  content/integrate/amazon-bedrock/set-up-redis.md
  content/operate/rc/changelog/october-2024.md
  content/operate/rc/databases/create-database/create-pro-database-new.md
  static/images/rc/subscription-new-flexible-version-section.png
Labels: do not merge yet, rc

#760 DOC: typo for __vec_score sortby field
  content/develop/interact/search-and-query/advanced-concepts/vectors.md
Labels: bug

#762 FLUSH commands and functions
  content/commands/flushall/index.md
  content/commands/flushdb/index.md
Labels: dev

#766 OP: update RedisGears release notes for 1.2.10
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisgears/redisgears-1.2-release-notes.md
Labels: dev

#767 RS 7.4.6-102 release notes
  content/operate/rs/release-notes/rs-7-4-2-releases/rs-7-4-6-102.md
Labels: rs

#765 RS 6.4.2-115 release notes
  content/operate/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-115.md
Labels: rs

#770 RS: Add alias to docker-quickstart.md
  content/operate/rs/installing-upgrading/quickstarts/docker-quickstart.md
Labels: rs

#764 K8s: 6.4.2-8 maint 3
  content/operate/kubernetes/release-notes/6-4-2-releases/6-4-2-8-oct24.md
Labels: k8s

#686 DEV: add TCEs to query > combined page
  content/develop/interact/search-and-query/query/combined.md
Labels: do not merge yet, dev

#781 K8s: fix admission controller bug
  content/embeds/k8s-admission-webhook-cert.md
Labels: bug

#779 Fix broken links
  content/glossary/_index.md
  content/integrate/write-behind/data-transformation/data-transformation-pipeline.md
  content/operate/kubernetes/release-notes/previous-releases/k8s-5-4-10-8.md
  content/operate/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-52.md
Labels: bug

#787 DOC-4384 removed spurious info on RDI Oracle prep page
  content/integrate/redis-data-integration/data-pipelines/prepare-dbs/oracle.md
Labels: rdi

#785 RS: Mention/link to Redis Cloud free trial
  content/operate/rs/_index.md
  content/operate/rs/installing-upgrading/_index.md
Labels: rs

#789 K8s: Roosevelt maint 3 release notes
  content/operate/kubernetes/release-notes/7-2-4-releases/7-2-4-12-10-24.md
Labels: k8s

#790 DEV: fix attribute type examples on the protocol page
  content/develop/reference/protocol-spec.md
Labels: bug, dev

#494 DOC-4014 added RDI string job config example
  content/integrate/redis-data-integration/ingest/data-pipelines/transform-examples/redis-string-example.md
Labels: rdi

#798 DOC-4403 rehomed RDI string example
  content/integrate/redis-data-integration/data-pipelines/transform-examples/redis-string-example.md
Labels: rdi

#799 Fix Relrefs
  content/integrate/redis-data-integration/data-pipelines/transform-examples/redis-string-example.md
  content/integrate/write-behind/data-transformation/data-transformation-pipeline.md
  content/operate/kubernetes/release-notes/6-2-18-releases/k8s-6-2-18-3.md
  content/operate/kubernetes/release-notes/6-2-18-releases/k8s-6-2-18-41-jan-2023.md
  content/operate/kubernetes/release-notes/6-2-18-releases/k8s-6-2-18-41.md
  content/operate/kubernetes/release-notes/7-4-6-releases/7-4-6-2-oct24.md
  content/operate/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-52.md
Labels: bug

#800 K8s: multi-ns warning for REAADB
  content/operate/kubernetes/deployment/deployment-options.md
  content/operate/kubernetes/re-clusters/multi-namespace.md
Labels: bug, k8s

#784 RC: Added cluster API limitations
  content/operate/rc/databases/configuration/clustering.md
Labels: rc

#801 K8s: fix RN weights
  content/operate/kubernetes/release-notes/7-2-4-releases/7-2-4-12-08-2024.md
  content/operate/kubernetes/release-notes/7-2-4-releases/7-2-4-12-10-24.md
Labels: bug, k8s

#802 K8s: new csv numbers
  content/operate/kubernetes/release-notes/6-4-2-releases/6-4-2-8-oct24.md
  content/operate/kubernetes/release-notes/7-2-4-releases/7-2-4-12-10-24.md
Labels: k8s

#807 RS: Fix anchor style for REST API permissions tables & add missing view_crdb_task permissions
  content/operate/rs/references/rest-api/permissions.md
Labels: rs

#778 RS: Fix contradictory statements about internal IP changes
  content/operate/rs/networking/multi-ip-ipv6.md
Labels: rs

#782 RS: Fix rladmin tune db typo & describe replica buffer options
  content/operate/rs/references/cli-utilities/rladmin/tune.md
Labels: rs

#815 DEV: quick fix for incorrect link
  content/commands/ft.config-set/index.md
Labels: bug, dev

#203 RS: Support package contents
  content/operate/rs/installing-upgrading/creating-support-package.md
Labels: do not merge yet, rs

#822 RC: Make the edit payment method button easier to see
  content/operate/rc/subscriptions/view-pro-subscription.md
  static/images/rc/icon-subscription-detail-change-payment-flexible.png
Labels: rc

#823 OP: add Redis Stack v7.2.x release notes
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisstack/redisstack-7.2-release-notes.md
Labels: dev

#817 DOC-4367 RDI K8s docs
  content/integrate/redis-data-integration/architecture.md
  content/integrate/redis-data-integration/data-pipelines/data-pipelines.md
  content/integrate/redis-data-integration/data-pipelines/deploy.md
  content/integrate/redis-data-integration/data-pipelines/prepare-dbs/my-sql-mariadb.md
  content/integrate/redis-data-integration/installation/_index.md
  content/integrate/redis-data-integration/installation/install-k8s.md
  content/integrate/redis-data-integration/installation/install-vm.md
  content/integrate/redis-data-integration/quick-start-guide.md
  content/integrate/redis-data-integration/release-notes/rdi-1-4-0.md
Labels: rdi

#825 DEV: fix link on Bloom data structure page
  content/develop/data-types/probabilistic/bloom-filter.md
Labels: bug, dev

#827 OP: change version in Redis Stack relnotes heading
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisstack/_index.md
Labels: bug

#810 Create v.2.60.0.md for Redis Insight
  content/develop/connect/insight/release-notes/v.2.60.0.md
Labels: do not merge yet, ri

#733 RS: Add rebalance database shards REST API reference
  content/operate/rs/references/rest-api/requests/bdbs/actions/_index.md
  content/operate/rs/references/rest-api/requests/bdbs/actions/rebalance.md
Labels: rs

#826 K8s: update CSV and add note about replacements
  content/operate/kubernetes/release-notes/6-4-2-releases/6-4-2-8-oct24.md
  content/operate/kubernetes/release-notes/7-2-4-releases/7-2-4-12-10-24.md
  content/operate/kubernetes/release-notes/7-4-6-releases/7-4-6-2-october24.md
Labels: k8s
