Repository redis/docs, pull requests merged in 2024-05, with the labels that each got.

#166 K8s: Titan - april to may change
  content/operate/kubernetes/release-notes/7-4-2-12.md
Labels: k8s

#138 K8s: REC naming notes
  content/operate/kubernetes/deployment/openshift/openshift-cli.md
  content/operate/kubernetes/deployment/openshift/openshift-operatorhub.md
  content/operate/kubernetes/deployment/quick-start.md
  content/operate/kubernetes/networking/_index.md
Labels: k8s

#139 RC: Active-Active with Search
  content/operate/rc/changelog/may-2024.md
  content/operate/rc/databases/configuration/advanced-capabilities.md
  content/operate/rc/databases/create-database/create-active-active-database.md
  static/images/rc/active-active-json-detail.png
  static/images/rc/active-active-memory-calculator.png
  static/images/rc/create-database-active-active.png
Labels: do not merge yet, rc

#148 K8s: New K8s diagrams
  content/operate/kubernetes/architecture/_index.md
  content/operate/kubernetes/architecture/operator.md
  content/operate/kubernetes/deployment/deployment-options.md
  static/images/k8s/k8-high-level-architecture-diagram-of-redis-enterprise.png
  static/images/k8s/k8s-deploy-cross-namespaces.png
  static/images/k8s/k8s-deploy-many-to-many.png
  static/images/k8s/k8s-deploy-multicluster-antipattern.png
  static/images/k8s/k8s-deploy-one-to-many.png
  static/images/k8s/k8s-deploy-one-to-one.png
  static/images/k8s/kubernetes-overview-layered-orchestration.png
  static/images/k8s/kubernetes-overview-multiple-services-per-pod.png
  static/images/k8s/kubernetes-overview-network-attached-persistent-storage.png
  static/images/k8s/kubernetes-overview-performance-improvements-read.png
  static/images/k8s/kubernetes-overview-performance-improvements-write.png
  static/images/k8s/kubernetes-overview-unified-deployment.png
  static/images/platforms/k8s-deploy-cross-namespaces.png
  static/images/platforms/k8s-deploy-many-to-many.png
  static/images/platforms/k8s-deploy-multicluster-antipattern.png
  static/images/platforms/k8s-deploy-one-to-many.png
  static/images/platforms/k8s-deploy-one-to-one.png
Labels: k8s

#175 Fix TS.ALTER syntax
  content/commands/ts.alter/index.md
Labels: bug, dev

#177 DEV: add new RI installation page, cross links, and change order
  content/develop/connect/insight/_index.md
  content/operate/redisinsight/_index.md
  content/operate/redisinsight/install/_index.md
  content/operate/redisinsight/install/env-variables.md
  content/operate/redisinsight/install/install-on-aws.md
  content/operate/redisinsight/install/install-on-desktop.md
  content/operate/redisinsight/install/install-on-k8s.md
Labels: dev

#171 K8s: code block bug - replace note with subsection
  content/operate/kubernetes/active-active/_index.md
  content/operate/kubernetes/active-active/prepare-clusters.md
Labels: bug, k8s

#168 Update nav to put Commands and APIs at the top of menu on all pages
  layouts/home.html
  layouts/partials/docs-nav-collapsed.html
  layouts/partials/docs-nav.html
Labels: ui

#186 DEV: add logging and configuration info for Redis Insight
  content/develop/connect/insight/_index.md
  content/operate/redisinsight/install/configuration.md
Labels: dev

#187 Add session expiration note
  content/operate/rc/security/_index.md
Labels: rc

#191 DEV: fix issue #176
  content/operate/redisinsight/install/install-on-k8s.md
Labels: dev

#165 K8s: expand PVC
  content/operate/kubernetes/re-clusters/expand-pvc.md
Labels: k8s

#196 DOC-3747 RDI doc bug fixes
  content/integrate/redis-data-integration/installation/install-k8s.md
Labels: bug, documentation

#190 RC: Replace memory calculator image with new text
  content/operate/rc/databases/create-database/create-active-active-database.md
  static/images/rc/active-active-memory-calculator.png
Labels: do not merge yet, rc

#181 RS: 6.4.2 May maintenance release
  content/operate/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-110.md
Labels: do not merge yet

#189 RS: 7.2.4 May maintenance release
  content/operate/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-109.md
Labels: do not merge yet

#239 DOC-3809 fixed headings on client lib pages
  content/develop/connect/clients/dotnet.md
  content/develop/connect/clients/java/jedis.md
  content/develop/connect/clients/java/lettuce.md
  content/develop/connect/clients/nodejs.md
  content/develop/connect/clients/python.md
Labels: documentation

#244 Update time series documentation
  content/commands/ts.add/index.md
  content/commands/ts.decrby/index.md
  content/commands/ts.incrby/index.md
Labels: dev

#250 DEV: fix bug in sentinel ACL docs
  content/operate/oss_and_stack/management/sentinel.md
Labels: bug, dev

#248 DEV: update RESP3 replies for SINTER and SMEMBERS
  data/resp2_replies.json
  data/resp3_replies.json
Labels: bug, dev

#254 Update README.md file
  README.md
Labels: documentation

#256 Unit of measurement style fixes
  content/operate/rc/changelog/april-2024.md
  content/operate/rc/changelog/november-2023.md
  content/operate/rc/databases/configuration/clustering.md
  content/operate/rc/databases/configuration/high-availability.md
Labels: bug

#222 K8s: troubleshooting cmds, weight change
  content/operate/kubernetes/re-clusters/expand-pvc.md
Labels: k8s

#215 K8s: add reaadb migration limitation
  content/operate/kubernetes/active-active/_index.md
Labels: k8s

#266 DEV: fix return values for CLIENT UNBLOCK command
  data/resp2_replies.json
  data/resp3_replies.json
Labels: bug

#258 Create Redis Insight v.2.50.0 release notes
  content/develop/connect/insight/release-notes/v.2.50.0.md
Labels: do not merge yet

#272 K8s: fix broken link
  content/operate/kubernetes/faqs/_index.md
Labels: k8s
