Repository redis/docs, pull requests merged in 2024-07, with the labels that each got.

#387 Improve RAG+REDIS quickstart guide
  content/develop/get-started/rag.md
Labels: documentation, dev

#344 RS: 7.4.2 Fuji June maintenance release docs
  content/operate/rs/references/rest-api/objects/bdb/backup_location.md
  content/operate/rs/references/rest-api/objects/bdb/dataset_import_sources.md
  content/operate/rs/release-notes/rs-7-4-2-releases/_index.md
  content/operate/rs/release-notes/rs-7-4-2-releases/rs-7-4-2-216.md
Labels: release-branch, rs

#388 DEV: fix a couple of issues related to HTTL and INFO
  content/commands/hpttl/index.md
  content/commands/httl/index.md
  content/commands/info/index.md
Labels: bug, dev

#364 K8s: Upgrade with OLM
  content/operate/kubernetes/deployment/openshift/openshift-cli.md
  content/operate/kubernetes/upgrade/upgrade-olm.md
Labels: k8s

#403 DOC-3830 fixed links to Jedis/Lettuce
  content/operate/rs/references/client_references/_index.md
Labels: bug

#404 DOC-2766 removed Performance and Scalability section altogether
  content/integrate/redis-data-integration/_index.md
Labels: bug, rdi

#408 Doc 3909 improve tag query syntax docs
  content/develop/interact/search-and-query/advanced-concepts/escaping.md
  content/develop/interact/search-and-query/advanced-concepts/query_syntax.md
  content/develop/interact/search-and-query/advanced-concepts/tags.md
Labels: bug

#405 DOC-2055 added links/info about dialects based on feedback
  content/commands/ft.create/index.md
  content/commands/ft.search/index.md
  content/develop/interact/search-and-query/advanced-concepts/dialects.md
  content/develop/interact/search-and-query/advanced-concepts/query_syntax.md
  content/develop/interact/search-and-query/advanced-concepts/vectors.md
  content/develop/interact/search-and-query/basic-constructs/configuration-parameters.md
Labels: bug

#406 DOC-3957 update RDI nesting config example
  content/integrate/redis-data-integration/ingest/data-pipelines/data-denormalization.md
Labels: rdi

#414 Doc 3961 secret setting info
  content/integrate/redis-data-integration/ingest/data-pipelines/data-pipelines.md
Labels: rdi

#407 clarified double quote usage for TAG
  content/develop/interact/search-and-query/query/exact-match.md
Labels: dev

#411 address issues in DOC-3935
  content/develop/interact/search-and-query/advanced-concepts/tags.md
  content/develop/interact/search-and-query/indexing/_index.md
Labels: dev

#412 add content for INDEXMISSING and INDEXEMPTY
  content/develop/interact/search-and-query/indexing/_index.md
Labels: dev

#410 remove references to dialect 5
  content/develop/interact/search-and-query/advanced-concepts/dialects.md
  content/develop/interact/search-and-query/basic-constructs/field-and-type-options.md
Labels: dev, dependencies

#417 DEV: fix remaining occurrences of DIALECT 5
  content/develop/interact/search-and-query/query/exact-match.md
Labels: bug

#418 DEV: add warning shortcode to FT.CREATERULE command page
  content/commands/ts.createrule/index.md
Labels: dev

#420 DEV: remove outdated key expiration info
  content/commands/expire/index.md
Labels: bug, dev

#421 K8s: Create database edits
  content/operate/kubernetes/re-databases/db-controller.md
Labels: k8s

#362 RC: Re-do Active-Active creation to follow the whole process
  content/embeds/rc-create-db-first-steps.md
  content/operate/rc/databases/configuration/active-active-redis.md
  content/operate/rc/databases/create-database/create-active-active-database.md
  content/operate/rc/databases/create-database/create-essentials-database.md
  content/operate/rc/databases/create-database/create-pro-database-existing.md
  content/operate/rc/databases/create-database/create-pro-database-new.md
  static/images/rc/active-active-json-detail.png
  static/images/rc/active-active-throughput-detail.png
  static/images/rc/create-pro-aa-review.png
  static/images/rc/create-sub-active-active-cidr.png
Labels: rc

#415 RC: Update Subscriptions landing page
  content/operate/rc/subscriptions/_index.md
Labels: rc

#416 RC: Move 7.4 preview to July changelog and collapse 2023 changelogs
  content/operate/rc/changelog/2023/_index.md
  content/operate/rc/changelog/2023/april-2023.md
  content/operate/rc/changelog/2023/august-2023.md
  content/operate/rc/changelog/2023/december-2023.md
  content/operate/rc/changelog/2023/february-2023.md
  content/operate/rc/changelog/2023/january-2023.md
  content/operate/rc/changelog/2023/july-2023.md
  content/operate/rc/changelog/2023/june-2023.md
  content/operate/rc/changelog/2023/march-2023.md
  content/operate/rc/changelog/2023/may-2023.md
  content/operate/rc/changelog/2023/november-2023.md
  content/operate/rc/changelog/2023/october-2023.md
  content/operate/rc/changelog/2023/september-2023.md
  content/operate/rc/changelog/july-2024.md
  content/operate/rc/changelog/june-2024.md
Labels: rc

#419 OP: remove more 404s related to RedisGears
  content/develop/connect/insight/release-notes/v2.0.md
  content/operate/oss_and_stack/stack-with-enterprise/gears-v1/_index.md
  content/operate/oss_and_stack/stack-with-enterprise/gears-v1/jvm/classes/gearsbuilder/config-get.md
  content/operate/oss_and_stack/stack-with-enterprise/gears-v1/jvm/classes/readers/commandoverrider.md
  content/operate/oss_and_stack/stack-with-enterprise/gears-v1/jvm/commands/_index.md
  content/operate/oss_and_stack/stack-with-enterprise/gears-v1/jvm/recipes/write-behind.md
  content/operate/oss_and_stack/stack-with-enterprise/gears-v1/python/_index.md
  content/operate/oss_and_stack/stack-with-enterprise/gears-v1/python/quickstart.md
  content/operate/oss_and_stack/stack-with-enterprise/gears-v1/register-events.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisgears/redisgears-1.0-release-notes.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisgears/redisgears-1.2-release-notes.md
Labels: bug

#422 DEV: remove occurrences of FT.ADD
  content/develop/interact/search-and-query/administration/design.md
  content/develop/interact/search-and-query/administration/overview.md
  content/develop/interact/search-and-query/advanced-concepts/chinese.md
  content/develop/interact/search-and-query/deprecated/payloads.md
Labels: bug, dev

#381 RS/RC: MEMORY HELP and MEMORY USAGE not supported for scripts in Redis v6
  content/operate/rs/references/compatibility/commands/server.md
Labels: rs

#393 RS: Add missing description of connecting to S3-compatible storage
  content/operate/rs/databases/import-export/export-data.md
  content/operate/rs/databases/import-export/import-data.md
  content/operate/rs/databases/import-export/schedule-backups.md
Labels: rs

#426 Add frontmatter patch for modules-api-ref.md
  content/develop/reference/modules/modules-api-ref-frontmatter.patch
Labels: docops

#428 DEV: document the OPTOUT option for CSC
  content/develop/use/client-side-caching.md
Labels: dev

#430 RS: Revert OSS Cluster API name change
  content/embeds/oss-cluster-api-intro.md
  content/operate/rs/clusters/optimize/oss-cluster-api.md
  content/operate/rs/databases/active-active/_index.md
  content/operate/rs/databases/configure/oss-cluster-api.md
  content/operate/rs/references/compatibility/_index.md
Labels: rs

#432 DEV: fix dev list page link squish bug
  content/develop/connect/insight/_index.md
  layouts/develop/list.html
Labels: bug, dev

#433 DEV/OP: clean up a couple of Hugo warnings
  content/commands/client-no-evict/index.md
  content/operate/kubernetes/re-databases/db-controller.md
Labels: bug

#425 update tags.md
  content/operate/rs/references/rest-api/objects/bdb/_index.md
Labels: rs

#370 RS: Add /bdbs/actions/recover REST API reference
  content/operate/rs/references/rest-api/permissions.md
  content/operate/rs/references/rest-api/requests/bdbs/actions/_index.md
  content/operate/rs/references/rest-api/requests/bdbs/actions/recover.md
Labels: rs

#441 Remove/replace H1 elements in article body
  content/commands/expire/index.md
  content/develop/data-types/json/developer.md
  content/develop/data-types/probabilistic/bloom-filter.md
  content/develop/data-types/probabilistic/count-min-sketch.md
  content/develop/data-types/probabilistic/cuckoo-filter.md
  content/develop/interact/search-and-query/administration/design.md
  content/develop/interact/search-and-query/administration/extensions.md
  content/develop/interact/search-and-query/administration/gc.md
  content/develop/interact/search-and-query/administration/overview.md
  content/develop/interact/search-and-query/advanced-concepts/chinese.md
  content/develop/interact/search-and-query/advanced-concepts/highlight.md
  content/develop/interact/search-and-query/advanced-concepts/phonetic_matching.md
  content/develop/interact/search-and-query/advanced-concepts/scoring.md
  content/develop/interact/search-and-query/advanced-concepts/sorting.md
  content/develop/interact/search-and-query/advanced-concepts/spellcheck.md
  content/develop/interact/search-and-query/advanced-concepts/stemming.md
  content/develop/interact/search-and-query/advanced-concepts/stopwords.md
  content/develop/interact/search-and-query/advanced-concepts/synonyms.md
  content/develop/interact/search-and-query/deprecated/development.md
  content/develop/interact/search-and-query/deprecated/payloads.md
  content/develop/reference/modules/_index.md
  content/integrate/redis-data-integration/write-behind/installation/install-redis-gears.md
  content/integrate/redis-data-integration/write-behind/reference/config-yaml-reference.md
  content/operate/oss_and_stack/management/optimization/benchmarks/index.md
  content/operate/oss_and_stack/reference/internals/rdd.md
  content/operate/oss_and_stack/stack-with-enterprise/deprecated-features/triggers-and-functions/Configuration.md
  content/operate/redisinsight/proxy.md
Labels: bug

#443 Replaced links to grafana dashboards from grafana repo to observability repo
  content/integrate/prometheus-with-redis-cloud/_index.md
  content/integrate/prometheus-with-redis-enterprise/_index.md
Labels: bug

#445 DEV: add NOVALUES flag to HSCAN reply information
  data/resp2_replies.json
  data/resp3_replies.json
Labels: bug, dev

#439 DEV: add RI debugging information
  content/develop/connect/insight/debugging.md
Labels: dev, ri

#449 DEV: modify instances of 7.4 RC1 to 7.4
  content/commands/client-list/index.md
  content/commands/eval/index.md
  content/commands/info/index.md
  content/commands/memory-stats/index.md
  content/commands/sort/index.md
  content/commands/xread/index.md
  content/develop/interact/programmability/lua-api.md
Labels: bug, dev

#452 update favicon
  static/images/favicons/android-chrome-192x192.png
  static/images/favicons/android-chrome-512x512.png
  static/images/favicons/apple-touch-icon-114x114.png
  static/images/favicons/apple-touch-icon-120x120.png
  static/images/favicons/apple-touch-icon-144x144.png
  static/images/favicons/apple-touch-icon-152x152.png
  static/images/favicons/apple-touch-icon-167x167.png
  static/images/favicons/apple-touch-icon-180x180.png
  static/images/favicons/apple-touch-icon-57x57.png
  static/images/favicons/apple-touch-icon-60x60.png
  static/images/favicons/apple-touch-icon-72x72.png
  static/images/favicons/apple-touch-icon-76x76.png
  static/images/favicons/favicon-128x128.png
  static/images/favicons/favicon-16x16.png
  static/images/favicons/favicon-196x196.png
  static/images/favicons/favicon-32x32.png
  static/images/favicons/favicon-96x96.png
  static/images/favicons/mstile-144x144.png
  static/images/favicons/mstile-150x150.png
  static/images/favicons/mstile-310x150.png
  static/images/favicons/mstile-310x310.png
  static/images/favicons/mstile-70x70.png
Labels: ui

#288 RC: Develop Resilient Applications draft
  content/operate/rc/databases/configuration/data-persistence.md
  content/operate/rc/resilient-apps.md
Labels: rc

#444 DEV: flesh out FT.INFO page
  content/commands/ft.info/index.md
Labels: enhancement, dev

#456 RC: Add new Google Cloud regions
  content/operate/rc/supported-regions.md
Labels: rc

#457 Doc 3479 json obtain redis stack
  content/develop/data-types/json/_index.md
  content/develop/data-types/probabilistic/_index.md
  content/develop/data-types/timeseries/_index.md
  content/develop/interact/search-and-query/_index.md
Labels: dev, rs

#458 Update REST API password documentation
  content/operate/rs/references/rest-api/objects/user.md
Labels: rs

#455 RC: Default maintenance windows for Essentials databases
  content/operate/rc/resilient-apps.md
  content/operate/rc/subscriptions/maintenance/_index.md
  content/operate/rc/subscriptions/maintenance/set-maintenance-windows.md
Labels: rc

#473 RC: Update GCP marketplace listing name and screenshot
  content/operate/rc/cloud-integrations/gcp-marketplace/_index.md
  static/images/rc/gcp-marketplace-rc-payg-plan.png
Labels: bug, rc

#454 DOC-3704 updated start/stop and next steps
  content/operate/oss_and_stack/install/install-redis/install-redis-on-linux.md
  content/operate/oss_and_stack/install/install-redis/install-redis-on-mac-os.md
  content/operate/oss_and_stack/install/install-redis/install-redis-on-windows.md
  content/operate/oss_and_stack/install/install-stack/linux.md
  content/operate/oss_and_stack/install/install-stack/mac-os.md
Labels: dev

#477 RS: Update EOL policy by 6 months
  content/operate/rs/installing-upgrading/product-lifecycle.md
Labels: rs

#462 RS: Change title from Log security to Manage logs
  content/operate/rs/clusters/logging/log-security.md
Labels: rs

#476 OP: fix a few Hugo warnings
  content/operate/rc/resilient-apps.md
Labels: bug

#434 Rewrite and restructure vector reference docs
  content/develop/interact/search-and-query/advanced-concepts/vectors.md
Labels: enhancement, dev

#483 RS: Copy product lifecycle updates from PR #399 to 7.4.2 release notes index
  content/operate/rs/release-notes/rs-7-4-2-releases/_index.md
Labels: rs

#338 chore: add observability section
  content/develop/connect/clients/go.md
Labels: do not merge yet, dev

#487 RC: Moved link to resilient apps in the maintenance docs
  content/operate/rc/subscriptions/maintenance/_index.md
Labels: rc

#489 DOC-4011 added note about min RS version for RDI database
  content/integrate/redis-data-integration/ingest/installation/_index.md
  content/integrate/redis-data-integration/ingest/quick-start-guide.md
Labels: rdi

#490 OP: update module relnotes
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisbloom/redisbloom-2.6-release-notes.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisbloom/redisbloom-2.8-release-notes.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.10-release-notes.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.6-release-notes.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.8-release-notes.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisgears/redisgears-1.2-release-notes.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisjson/redisjson-2.8-release-notes.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redistimeseries/redistimeseries-1.12-release-notes.md
Labels: enhancement

#468 Update _index.md
  content/integrate/riot/_index.md
Labels: do not merge yet

#467 Update install.md for RIOT 4.x
  content/integrate/riot/install.md
Labels: do not merge yet

#466 Removed outdated sections
  content/integrate/riot/quick-start.md
Labels: do not merge yet

#493 INT: remove superfluous RIOT files
  content/integrate/riot/_index.md
  content/integrate/riot/architecture.md
  content/integrate/riot/databases.md
  content/integrate/riot/docs.md
  content/integrate/riot/faq.md
  content/integrate/riot/files.md
  content/integrate/riot/generators.md
  content/integrate/riot/images/architecture.png
  content/integrate/riot/images/architecture.svg
  content/integrate/riot/images/dump-and-restore.svg
  content/integrate/riot/images/mapping.png
  content/integrate/riot/images/reader-architecture.svg
  content/integrate/riot/images/replication.png
  content/integrate/riot/install.md
  content/integrate/riot/misc-topics.md
  content/integrate/riot/quick-start.md
  content/integrate/riot/replication.md
Labels: dev

#463 RC: Query Performance Factor
  content/operate/rc/changelog/2023/_index.md
  content/operate/rc/changelog/2023/april-2023.md
  content/operate/rc/changelog/2023/august-2023.md
  content/operate/rc/changelog/2023/december-2023.md
  content/operate/rc/changelog/2023/february-2023.md
  content/operate/rc/changelog/2023/january-2023.md
  content/operate/rc/changelog/2023/july-2023.md
  content/operate/rc/changelog/2023/june-2023.md
  content/operate/rc/changelog/2023/march-2023.md
  content/operate/rc/changelog/2023/may-2023.md
  content/operate/rc/changelog/2023/november-2023.md
  content/operate/rc/changelog/2023/october-2023.md
  content/operate/rc/changelog/2023/september-2023.md
  content/operate/rc/changelog/july-2024.md
  content/operate/rc/databases/configuration/advanced-capabilities.md
  content/operate/rc/databases/create-database/create-essentials-database.md
  content/operate/rc/databases/create-database/create-pro-database-existing.md
  content/operate/rc/databases/create-database/create-pro-database-new.md
  static/images/rc/create-database-essentials-cloud-vendor.png
  static/images/rc/essentials-74-preview.png
  static/images/rc/flexible-add-database-basic.png
Labels: do not merge yet, rc

#497 Terraform get started edits
  content/integrate/terraform-provider-for-redis-cloud/get-started.md
Labels: rc

#464 RS: Add prereq to avoid cluster management operations during cluster upgrade
  content/operate/rs/installing-upgrading/upgrading/upgrade-cluster.md
Labels: rs

#498 DEV: update module API for 7.4 GA
  content/develop/reference/modules/modules-api-ref.md
Labels: CE 7.4

#349 RS: Access control doc improvements
  content/operate/kubernetes/security/ldap.md
  content/operate/kubernetes/security/manage-rec-credentials.md
  content/operate/rs/_index.md
  content/operate/rs/databases/active-active/create.md
  content/operate/rs/databases/configure/_index.md
  content/operate/rs/installing-upgrading/_index.md
  content/operate/rs/installing-upgrading/install/_index.md
  content/operate/rs/installing-upgrading/install/install-on-linux.md
  content/operate/rs/references/rest-api/objects/redis_acl.md
  content/operate/rs/references/rest-api/permissions.md
  content/operate/rs/release-notes/legacy-release-notes/rs-5-4-2-april-2019.md
  content/operate/rs/release-notes/rs-6-0-20-april-2021.md
  content/operate/rs/release-notes/rs-6-0-may-2020.md
  content/operate/rs/security/_index.md
  content/operate/rs/security/access-control/_index.md
  content/operate/rs/security/access-control/create-cluster-roles.md
  content/operate/rs/security/access-control/create-combined-roles.md
  content/operate/rs/security/access-control/create-db-roles.md
  content/operate/rs/security/access-control/create-users.md
  content/operate/rs/security/access-control/database-access.md
  content/operate/rs/security/access-control/manage-passwords/_index.md
  content/operate/rs/security/access-control/manage-passwords/rotate-passwords.md
  content/operate/rs/security/access-control/manage-users/_index.md
  content/operate/rs/security/access-control/manage-users/add-users.md
  content/operate/rs/security/access-control/manage-users/default-user.md
  content/operate/rs/security/access-control/rbac/_index.md
  content/operate/rs/security/access-control/rbac/assign-user-role.md
  content/operate/rs/security/access-control/rbac/create-roles.md
  content/operate/rs/security/access-control/redis-acl-overview.md
  content/operate/rs/security/admin-console-security/_index.md
  content/operate/rs/security/recommended-security-practices.md
  static/images/rs/rbac-diagram.png
  static/images/rs/screenshots/access-control/access-control-role-databases.png
  static/images/rs/screenshots/access-control/rbac-create-combined-role-select-cm-role.png
  static/images/rs/screenshots/access-control/rbac-create-role-cluster-only.png
  static/images/rs/screenshots/access-control/rbac-save-combined-role.png
Labels: do not merge yet, rs

#484 RS: 7.4.6 July release docs
  content/operate/rs/installing-upgrading/upgrading/upgrade-cluster.md
  content/operate/rs/references/rest-api/requests/bdbs/actions/optimize_shards_placement.md
  content/operate/rs/references/rest-api/requests/bdbs/actions/recover.md
  content/operate/rs/release-notes/rs-7-4-2-releases/_index.md
  content/operate/rs/release-notes/rs-7-4-2-releases/rs-7-4-6-22.md
Labels: rs

#495 DEV: support both redis-py and redisvl in TCEs
  build/components/example.py
  config.toml
  content/develop/connect/clients/python/_index.md
  content/develop/connect/clients/python/redis-py.md
  content/develop/connect/clients/python/redis-vl.md
  data/components/index.json
  data/components/redis_vl.json
  layouts/partials/tabbed-clients-example.html
  layouts/partials/tabs/wrapper.html
Labels: enhancement, dev

#502 SITE: eliminate more double-slashes
  content/develop/get-started/vector-database.md
  content/operate/kubernetes/reference/supported_k8s_distributions.md
  content/operate/rc/changelog/2023/march-2023.md
  content/operate/rs/references/compatibility/commands/cluster.md
  content/operate/rs/references/compatibility/commands/connection.md
  content/operate/rs/references/compatibility/commands/generic.md
  content/operate/rs/references/compatibility/commands/pub-sub.md
  content/operate/rs/references/compatibility/commands/scripting.md
  content/operate/rs/references/compatibility/commands/server.md
  content/operate/rs/references/compatibility/commands/transactions.md
Labels: bug
