Repository redis/docs, pull requests merged in 2024-09, with the labels that each got.

#619 RS: Copy LDAP URI validation change to version changes section of 7.4.6-22 release notes
  content/operate/rs/release-notes/rs-7-4-2-releases/rs-7-4-6-22.md
Labels: rs

#625 RS: Remove /new from CM UI URLs
  content/operate/rs/clusters/add-node.md
  content/operate/rs/clusters/new-cluster-setup.md
  content/operate/rs/databases/auto-tiering/quickstart.md
  content/operate/rs/databases/create.md
Labels: rs

#608 RS: Clarify limitation for mixed RAM/flash A-A clusters
  content/operate/rs/databases/active-active/create.md
  content/operate/rs/databases/active-active/manage.md
  content/operate/rs/databases/active-active/planning.md
Labels: rs

#596 RS: DB config doc fixes that apply to 7.4.x
  content/operate/rs/databases/configure/_index.md
  content/operate/rs/databases/configure/db-defaults.md
Labels: rs

#631 DOC-4214 added troubleshooting page
  content/integrate/redis-data-integration/ingest/architecture.md
  content/integrate/redis-data-integration/ingest/installation/_index.md
  content/integrate/redis-data-integration/ingest/observability.md
  content/integrate/redis-data-integration/ingest/troubleshooting.md
Labels: rdi

#635 RS: Clarify master_persistence is in addition to replica persistence
  content/operate/rs/references/cli-utilities/rladmin/tune.md
  content/operate/rs/references/rest-api/objects/bdb/_index.md
Labels: rs

#634 RS: Clarify export DB and import DB instructions
  content/operate/rs/databases/import-export/export-data.md
  content/operate/rs/databases/import-export/import-data.md
Labels: rs

#626 RC: Add "Easy create" to Create pro
  content/operate/rc/cloud-integrations/vercel.md
  content/operate/rc/databases/create-database/create-pro-database-new.md
  static/images/rc/create-database-subscription-essentials.png
  static/images/rc/create-database-subscription-pro-new.png
  static/images/rc/create-pro-db-settings.png
  static/images/rc/pro-easy-create-edit-icon.png
  static/images/rc/pro-easy-create-optimal-settings.png
  static/images/rc/pro-easy-create-payment.png
  static/images/rc/pro-easy-create-vendor.png
Labels: rc

#638 RS: Fix broken link in legacy release notes
  content/operate/rs/release-notes/legacy-release-notes/rs-5-6-0-april-2020.md
Labels: rs

#637 RC: Replace app.redislabs.com/new links
  content/operate/rc/security/access-control/social-login.md
Labels: bug, rc

#641 DOC-4222 added warning about previous RS installation
  content/integrate/redis-data-integration/ingest/installation/_index.md
Labels: rdi

#624 RC: Add limitation sentence for essentials plans
  content/operate/rc/subscriptions/view-essentials-subscription/essentials-plan-details.md
Labels: rc

#633 RS: Fix role_uids description in user REST API reference
  content/operate/rs/references/rest-api/objects/user.md
Labels: rs

#560 RS: Update DB config docs with CM UI changes
  content/operate/rs/databases/active-active/create.md
  content/operate/rs/databases/active-active/get-started.md
  content/operate/rs/databases/auto-tiering/quickstart.md
  content/operate/rs/databases/configure/_index.md
  content/operate/rs/databases/configure/database-persistence.md
  content/operate/rs/databases/configure/oss-cluster-api.md
  content/operate/rs/databases/configure/proxy-policy.md
  content/operate/rs/databases/configure/replica-ha.md
  content/operate/rs/databases/import-export/schedule-backups.md
  content/operate/rs/installing-upgrading/quickstarts/redis-enterprise-software-quickstart.md
  static/images/rs/screenshots/databases/active-active-databases/quickstart-ha-turn-off-replication.png
  static/images/rs/screenshots/databases/config-clustering-oss-cluster-api.png
  static/images/rs/screenshots/databases/config-replica-ha-enabled.png
  static/images/rs/screenshots/databases/quick-db-flash.png
  static/images/rs/screenshots/databases/quick-db.png
Labels: rs

#647 Fix typo in cidr-whitelist.md
  content/operate/rc/security/cidr-whitelist.md
Labels: bug, rc

#646 K8s: fixed 404 errors
  content/operate/kubernetes/re-clusters/connect-prometheus-operator.md
  content/operate/kubernetes/recommendations/node-selection.md
  content/operate/kubernetes/release-notes/previous-releases/k8s-5-4-10-8.md
  content/operate/kubernetes/release-notes/previous-releases/k8s-6-0-12-5.md
  content/operate/kubernetes/release-notes/previous-releases/k8s-6-0-8-1.md
  content/operate/kubernetes/release-notes/previous-releases/k8s-6-0-8-20.md
Labels: bug, k8s

#613 Update _index.md reinforcing that the example is a TOML file.
  content/integrate/redis-data-integration/ingest/installation/_index.md
Labels: rdi

#652 K8s: fix relref
  content/operate/kubernetes/recommendations/node-selection.md
Labels: bug

#649 RS: Remove /new from CM UI URL in embeds
  content/embeds/cluster-setup.md
Labels: rs

#600 Create v.2.56.0.md
  content/develop/connect/insight/release-notes/v.2.56.0.md
Labels: do not merge yet, ri

#549 DEV: Redis in VS Code docs
  content/develop/connect/redis-for-vscode/_index.md
  content/develop/connect/redis-for-vscode/release-notes/_index.md
  content/develop/connect/redis-for-vscode/release-notes/v1.0.0.md
  static/images/dev/connect/vscode/vscode-add-menu.png
  static/images/dev/connect/vscode/vscode-cli.png
  static/images/dev/connect/vscode/vscode-cnx-tools.png
  static/images/dev/connect/vscode/vscode-cnx-view.png
  static/images/dev/connect/vscode/vscode-edit-add.png
  static/images/dev/connect/vscode/vscode-edit-del.png
  static/images/dev/connect/vscode/vscode-edit-name.png
  static/images/dev/connect/vscode/vscode-edit-ttl.png
  static/images/dev/connect/vscode/vscode-edit-value-formatters.png
  static/images/dev/connect/vscode/vscode-initial.png
  static/images/dev/connect/vscode/vscode-install1.png
  static/images/dev/connect/vscode/vscode-install2.png
  static/images/dev/connect/vscode/vscode-key-view-w-wo-keys.png
  static/images/dev/connect/vscode/vscode-key-view.png
  static/images/dev/connect/vscode/vscode-menu.png
  static/images/dev/connect/vscode/vscode-recycle-before-after.png
  static/images/dev/connect/vscode/vscode-settings.png
Labels: do not merge yet, ri

#607 DEV: Add TCEs to select command pages
  content/commands/del/index.md
  content/commands/expire/index.md
  content/commands/hget/index.md
  content/commands/hset/index.md
  content/commands/incr/index.md
  content/commands/scan/index.md
  content/commands/ttl/index.md
  content/commands/zadd/index.md
  content/commands/zrange/index.md
Labels: do not merge yet, dev

#653 DOC-4255: update RediSearch release notes for 2.10.7
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.10-release-notes.md
Labels: dev

#648 RS: Add maintenance_snapshot to /nodes/status REST API reference
  content/operate/rs/references/rest-api/requests/nodes/status.md
Labels: rs

#636 RS: Add change_master to /cluster/actions REST API reference
  content/operate/rs/references/rest-api/requests/cluster/actions.md
Labels: rs

#644 DEV: add TCEs to query > exact match page
  content/develop/interact/search-and-query/query/exact-match.md
Labels: dev

#650 DEV: add TCEs to query > range page
  content/develop/interact/search-and-query/query/range.md
Labels: dev

#655 DEV: add TCEs to query > full-text page
  content/develop/interact/search-and-query/query/full-text.md
Labels: do not merge yet, dev

#660 DEV: add TCEs to query > geospatial page
  content/develop/interact/search-and-query/query/geo-spatial.md
Labels: do not merge yet, dev

#561 RS: Edit module config for existing DB in the CM UI
  content/operate/oss_and_stack/stack-with-enterprise/bloom/config.md
  content/operate/oss_and_stack/stack-with-enterprise/search/config.md
  content/operate/oss_and_stack/stack-with-enterprise/timeseries/config.md
  content/operate/rs/databases/configure/_index.md
  static/images/rs/screenshots/databases/rs-config-search-params.png
Labels: rs

#546 RS: 3 feature sets and module API changes and deprecations
  content/operate/oss_and_stack/stack-with-enterprise/install/_index.md
  content/operate/oss_and_stack/stack-with-enterprise/install/add-module-to-cluster.md
  content/operate/oss_and_stack/stack-with-enterprise/install/upgrade-module.md
  content/operate/rs/installing-upgrading/upgrading/upgrade-active-active.md
  content/operate/rs/installing-upgrading/upgrading/upgrade-database.md
  content/operate/rs/references/cli-utilities/rladmin/status.md
  content/operate/rs/references/cli-utilities/rladmin/upgrade.md
  content/operate/rs/references/rest-api/objects/bdb/_index.md
  content/operate/rs/references/rest-api/objects/module.md
  content/operate/rs/references/rest-api/requests/bdbs/upgrade.md
  content/operate/rs/references/rest-api/requests/modules/upgrade.md
  static/images/rs/screenshots/databases/quick-db-capabilities.png
Labels: rs

#504 RS: Consolidate and update logged alerts and events
  content/operate/rs/clusters/logging/alerts-events.md
  content/operate/rs/clusters/logging/rsyslog-logging/_index.md
  content/operate/rs/clusters/logging/rsyslog-logging/bdb-events.md
  content/operate/rs/clusters/logging/rsyslog-logging/cluster-events.md
  content/operate/rs/clusters/logging/rsyslog-logging/node-events.md
  content/operate/rs/clusters/logging/rsyslog-logging/user-events.md
Labels: rs

#550 RS and RC: Client-side caching and compatibility
  content/operate/rc/compatibility.md
  content/operate/rs/databases/memory-performance/_index.md
  content/operate/rs/references/cli-utilities/rladmin/tune.md
  content/operate/rs/references/compatibility/_index.md
  content/operate/rs/references/compatibility/client-side-caching.md
  content/operate/rs/references/compatibility/config-settings.md
  content/operate/rs/references/rest-api/objects/bdb/_index.md
  content/operate/rs/references/rest-api/objects/cluster_settings.md
Labels: rc, rs

#676 DOC-4285 added info about iptables versions
  content/integrate/redis-data-integration/installation/_index.md
Labels: rdi

#675 DEV: add TCEs to query > vector page
  content/develop/interact/search-and-query/query/vector-search.md
Labels: dev

#682 RC: Mark eu-west-1 as supported for essentials
  content/operate/rc/supported-regions.md
Labels: bug

#684 K8s: changed wording of SCC note
  content/operate/kubernetes/deployment/openshift/openshift-operatorhub.md
Labels: enhancement, k8s

#683 DOC-4289 fix issues with TCE tabs
  layouts/partials/tabs/wrapper.html
Labels: bug

#664 DOC-4275 updated dataflow diagram
  content/integrate/redis-data-integration/data-pipelines/data-pipelines.md
  content/integrate/redis-data-integration/observability.md
  static/images/rdi/RDIPipeDataflow.drawio.svg
Labels: rdi

#691 Fix Ingest and Write-behind link 404s on home page
  layouts/home.html
Labels: bug

#685 RS & RC support CLIENT TRACKING & CLIENT TRACKINGINFO commands
  content/operate/rs/references/compatibility/commands/connection.md
Labels: rc, rs

#380 RS: Add GET shards and migrate shards REST API references
  content/operate/rs/databases/migrate-shards.md
  content/operate/rs/references/cli-utilities/rladmin/migrate.md
  content/operate/rs/references/rest-api/objects/statistics/_index.md
  content/operate/rs/references/rest-api/requests/bdbs/shards.md
  content/operate/rs/references/rest-api/requests/shards/_index.md
  content/operate/rs/references/rest-api/requests/shards/actions/_index.md
  content/operate/rs/references/rest-api/requests/shards/actions/migrate.md
  content/operate/rs/references/rest-api/requests/shards/stats/_index.md
  content/operate/rs/references/rest-api/requests/shards/stats/last.md
Labels: rs

#667 RC: Add password length requirements
  content/operate/rc/security/access-control/data-access-control/create-assign-users.md
  content/operate/rc/security/access-control/data-access-control/default-user.md
Labels: rc

#693 K8s: 7.4.6-2 Oct release notes
  content/operate/kubernetes/release-notes/7-4-6-releases/7-4-6-2-oct24.md
  content/operate/kubernetes/release-notes/7-4-6-releases/7-4-6-2.md
  content/operate/kubernetes/release-notes/7-4-6-releases/_index.md
Labels: k8s

#697 DEV: update indexing limitations per eng
  content/develop/interact/search-and-query/indexing/_index.md
Labels: bug, dev

#698 INF: add new command to update command pages from commands_core.json
  build/components/markdown.py
  build/update_cmds.py
Labels: infrastructure

#554 RS: Node actions in the CM UI
  content/operate/rs/clusters/add-node.md
  content/operate/rs/clusters/change-node-role.md
  content/operate/rs/clusters/remove-node.md
  static/images/rs/screenshots/nodes/confirm-node-removal-selected.png
  static/images/rs/screenshots/nodes/primary-node-more-actions.png
  static/images/rs/screenshots/nodes/primary-node-set-as-secondary-dialog.png
  static/images/rs/screenshots/nodes/secondary-nodes-more-actions.png
  static/images/rs/screenshots/nodes/tmp.txt
Labels: rs

#679 RS: Add new syncer connection alert attributes to BDB object REST API reference
  content/operate/rs/references/rest-api/objects/bdb/_index.md
Labels: rs

#563 RS: Configure license expiration alert
  content/operate/rs/clusters/configure/license-keys.md
  content/operate/rs/references/rest-api/objects/cluster/alert_settings.md
  static/images/rs/screenshots/cluster/cluster-config-alert-settings-utilization.png
  static/images/rs/screenshots/cluster/cluster-license-expiration-alert.png
Labels: rs

#530 DOC-4037 Rework client-side caching content
  content/develop/connect/clients/client-side-caching.md
  content/develop/connect/clients/java/jedis.md
  content/develop/connect/clients/python/redis-py.md
  content/develop/reference/client-side-caching.md
  static/images/csc/CSCNoCache.drawio.svg
  static/images/csc/CSCSeqDiagram.drawio.svg
  static/images/csc/CSCWithCache.drawio.svg
Labels: do not merge yet

#713 RS: Fix typo in Prometheus integration description
  content/integrate/prometheus-with-redis-enterprise/_index.md
Labels: rs

#695 K8s: code block spacing fix
  content/embeds/k8s-642-redb-admission-webhook-name-change.md
  content/embeds/k8s-admission-webhook-cert.md
  content/operate/kubernetes/active-active/_index.md
  content/operate/kubernetes/deployment/openshift/openshift-cli.md
  content/operate/kubernetes/deployment/quick-start.md
  content/operate/kubernetes/upgrade/upgrade-redis-cluster.md
Labels: bug, k8s

#628 RS: 7.4.6 Sept maintenance release docs
  content/operate/rs/references/rest-api/objects/cluster_settings.md
  content/operate/rs/release-notes/rs-7-4-2-releases/_index.md
  content/operate/rs/release-notes/rs-7-4-2-releases/rs-7-4-6-77.md
Labels: do not merge yet, rs
