Repository redis/docs, pull requests merged in 2025-06, with the labels that each got.

#1638 K8s: add missing k8s terms to glossary page
  content/glossary/_index.md
Labels: k8s

#1651 DEV: add generic-ish tab control
  assets/css/index.css
  layouts/partials/components/generic-tabs.html
  layouts/partials/scripts.html
  layouts/shortcodes/multitabs.html
  static/js/generic-tabs.js
Labels: ui

#1644 RS: Added key/value size limits for flash storage
  content/operate/rs/databases/auto-tiering/_index.md
Labels: rs

#1643 RS: Clarified quorum loss check and warning when activating maintenance mode
  content/operate/rs/7.4/clusters/maintenance-mode.md
  content/operate/rs/7.8/clusters/maintenance-mode.md
  content/operate/rs/clusters/maintenance-mode.md
Labels: rs

#1610 RS: Prevent dnsmasq from using port 53
  content/embeds/port-53.md
Labels: rs

#1661 DOC-5306 updated Jedis and Lettuce versions and added node-redis CSC
  content/develop/clients/client-side-caching.md
  content/develop/clients/jedis/_index.md
  content/develop/clients/lettuce/_index.md
Labels: clients

#1633 DOC-5281 added Oracle XMLTYPE config section
  content/integrate/redis-data-integration/data-pipelines/prepare-dbs/oracle.md
  static/images/rdi/ingest/xmltype-example.webp
Labels: rdi

#1657 K8s: fix broken links
  content/operate/kubernetes/re-clusters/connect-prometheus-operator.md
Labels: bug, k8s

#1658 K8s: update example to use 7.22.0-7
  content/operate/kubernetes/deployment/container-images.md
Labels: k8s

#1605 DOC-4990 AMR connection page for Go
  content/develop/clients/go/amr.md
  content/develop/clients/go/connect.md
  content/develop/clients/go/produsage.md
  content/develop/clients/go/queryjson.md
  content/develop/clients/go/transpipe.md
  content/develop/clients/go/vecsearch.md
Labels: clients

#1668 DOC-5311 fixed filename in Helm install examples
  content/integrate/redis-data-integration/installation/install-k8s.md
Labels: rdi

#1656 K8s: sys_resource revision
  content/operate/kubernetes/deployment/helm.md
  content/operate/kubernetes/deployment/openshift/openshift-cli.md
  content/operate/kubernetes/deployment/openshift/openshift-operatorhub.md
  content/operate/kubernetes/deployment/quick-start.md
  content/operate/kubernetes/security/allow-resource-adjustment.md
  content/operate/kubernetes/security/enable-privileged-mode.md
Labels: k8s

#1602 RS 7.8.6 May maintenance release notes
  content/operate/rs/release-notes/rs-7-8-releases/_index.md
  content/operate/rs/release-notes/rs-7-8-releases/rs-7-8-6-95.md
Labels: rs

#1676 RS: Fixed broken link to diagnostic logging API reference
  content/operate/rs/clusters/logging/diagnostic-logging.md
Labels: rs

#1677 RS: Fixed link anchor for diagnostic logging API reference
  content/operate/rs/clusters/logging/diagnostic-logging.md
Labels: rs

#1665 K8s: xwing maint release notes
  content/operate/kubernetes/release-notes/7-22-0-releases/7-22-0-11-june2025.md
  content/operate/kubernetes/release-notes/7-22-0-releases/7-22-0-7-april2025.md
  content/operate/kubernetes/release-notes/7-22-0-releases/_index.md
Labels: k8s

#1670 K8s: OSS Cluster API limitation
  content/operate/kubernetes/networking/_index.md
Labels: bug, k8s

#1699 DOC-5337 added warning about /var mounted with noexec
  content/integrate/redis-data-integration/installation/install-vm.md
Labels: rdi

#1705 K8s: 7.2.4-12 june maint
  content/operate/kubernetes/release-notes/7-2-4-releases/7-2-4-12-june25.md
  content/operate/kubernetes/release-notes/7-2-4-releases/7-2-4-12-mar25.md
Labels: k8s

#1688 RS: 7.4.6 June maintenance release notes
  content/operate/rs/release-notes/rs-7-4-2-releases/_index.md
  content/operate/rs/release-notes/rs-7-4-2-releases/rs-7-4-6-268.md
Labels: rs

#1715 DEV: add RESP2/3 return information to the Bloom filter commands
  content/commands/bf.add.md
  content/commands/bf.card.md
  content/commands/bf.exists.md
  content/commands/bf.info.md
  content/commands/bf.insert.md
  content/commands/bf.loadchunk.md
  content/commands/bf.madd.md
  content/commands/bf.mexists.md
  content/commands/bf.reserve.md
  content/commands/bf.scandump.md
Labels: dev

#1720 Add RESP2/3 return information to the Cuckoo filter commands
  content/commands/cf.add.md
  content/commands/cf.addnx.md
  content/commands/cf.count.md
  content/commands/cf.del.md
  content/commands/cf.exists.md
  content/commands/cf.info.md
  content/commands/cf.insert.md
  content/commands/cf.insertnx.md
  content/commands/cf.loadchunk.md
  content/commands/cf.mexists.md
  content/commands/cf.reserve.md
  content/commands/cf.scandump.md
Labels: dev

#1722 DEV: add deprecation notice for NOSTOPWORDS
  content/commands/ft.search.md
Labels: dev

#1721 OP: add RediSearch v2.10.19 release notes
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.10-release-notes.md
Labels: op

#1723 DOC-5347 fixed links broken by RDI restructure
  content/develop/tools/insight/rdi-connector.md
  content/integrate/redis-data-integration/data-pipelines/prepare-dbs/oracle.md
  content/integrate/redis-data-integration/installation/install-k8s.md
  content/integrate/redis-data-integration/installation/install-vm.md
  content/integrate/redis-data-integration/observability.md
  content/integrate/redis-data-integration/quick-start-guide.md
Labels: rdi

#1726 DOC-5226 C# probabilistic data type examples
  content/develop/clients/dotnet/prob.md
Labels: clients

#1729 K8s: unicorn maint 5 release notes
  content/operate/kubernetes/release-notes/7-4-6-releases/7-4-6-6-june25.md
  content/operate/kubernetes/release-notes/7-4-6-releases/7-4-6-6-mar25.md
Labels: k8s

#1728 DOC-5229 Go probabilistic data type examples
  content/develop/clients/go/prob.md
Labels: clients

#1735 DEV: fix bug on indexing page
  content/develop/interact/search-and-query/indexing/_index.md
Labels: bug, dev

#1736 DEV: add RediSearch release notes
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.10-release-notes.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.6-release-notes.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.8-release-notes.md
Labels: dev

#1739 DEV: add RESP2/3 return information to the CMS commands
  content/commands/cms.incrby.md
  content/commands/cms.info.md
  content/commands/cms.initbydim.md
  content/commands/cms.initbyprob.md
  content/commands/cms.merge.md
  content/commands/cms.query.md
Labels: dev

#1747 DEV: add RESP2/3 info to the top-k commands
  content/commands/topk.add.md
  content/commands/topk.count.md
  content/commands/topk.incrby.md
  content/commands/topk.info.md
  content/commands/topk.list.md
  content/commands/topk.query.md
  content/commands/topk.reserve.md
Labels: dev

#1754 DEV: add RESP2/3 return information to the t-digest commands
  content/commands/tdigest.add.md
  content/commands/tdigest.byrank.md
  content/commands/tdigest.byrevrank.md
  content/commands/tdigest.cdf.md
  content/commands/tdigest.create.md
  content/commands/tdigest.info.md
  content/commands/tdigest.max.md
  content/commands/tdigest.merge.md
  content/commands/tdigest.min.md
  content/commands/tdigest.quantile.md
  content/commands/tdigest.rank.md
  content/commands/tdigest.reset.md
  content/commands/tdigest.revrank.md
  content/commands/tdigest.trimmed_mean.md
Labels: dev

#1741 RS 7.2.4 June maintenance release notes
  content/operate/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-132.md
Labels: rs

#1765 DOC-5368: update VSIM command page for ROS8.2
  content/commands/vsim.md
Labels: dev, ros 8.2

#1759 DOC-5367: update bitmap docs for ROS8.2
  content/commands/bitop.md
  content/develop/data-types/bitmaps.md
Labels: dev, ros 8.2

#1768 DEV: update INFO command page with keysizes section info
  content/commands/info.md
Labels: dev

#1701 DOC-5338: RDI enchance observability page with more metrics information
  content/integrate/redis-data-integration/observability.md
Labels: rdi

#1771 DOC-4638 DOC-5396 TCE box improvements
  assets/css/index.css
  layouts/partials/tabbed-clients-example.html
Labels: clients

#1772 DOC-5397 added release notes for RDI v1.12.1
  config.toml
  content/integrate/redis-data-integration/release-notes/rdi-1-12-1.md
Labels: rdi

#1767 K8s: Wisconsin maint 4
  content/operate/kubernetes/release-notes/7-8-6-releases/7-8-6-2-june2025.md
  content/operate/kubernetes/release-notes/7-8-6-releases/7-8-6-3-june2025.md
  content/operate/kubernetes/release-notes/7-8-6-releases/_index.md
Labels: k8s

#1702 RS 7.22.0 June maintenance release docs
  content/embeds/rs-prometheus-metrics-v2.md
  content/operate/rs/references/rest-api/requests/users/password.md
  content/operate/rs/release-notes/rs-7-22-releases/rs-7-22-0-216.md
  content/operate/rs/security/access-control/manage-passwords/rotate-passwords.md
Labels: rs
