Repository redis/docs, pull requests merged in 2025-08, with the labels that each got.

#1917 DEV: add RESP2/3 return information to the remaining commands
  content/commands/client-no-evict.md
  content/commands/client-no-touch.md
  content/commands/memory-malloc-stats.md
Labels: dev, cmds

#1884 Redis Open Source 8.2 docs
  content/commands/bitop.md
  content/commands/cluster-slot-stats.md
  content/commands/ft.aggregate.md
  content/commands/info.md
  content/commands/vismember.md
  content/commands/vrem.md
  content/commands/vsim.md
  content/commands/xackdel.md
  content/commands/xadd.md
  content/commands/xdelex.md
  content/commands/xtrim.md
  content/develop/ai/search-and-query/advanced-concepts/aggregations.md
  content/develop/ai/search-and-query/indexing/field-and-type-options.md
  content/develop/ai/search-and-query/vectors.md
  content/develop/data-types/bitmaps.md
  content/develop/data-types/streams.md
  content/develop/data-types/vector-sets/_index.md
  content/develop/pubsub/keyspace-notifications.md
  content/develop/reference/modules/modules-api-ref.md
  static/resources/redisuniversity.yaml
Labels: do not merge yet, ros 8.2

#1923 DEV: fix image links on AI landing page
  content/develop/ai/_index.md
  layouts/shortcodes/image-card.html
Labels: bug, dev

#1907 RS: Added connection rate throttling metrics
  content/embeds/rs-prometheus-metrics-v2.md
Labels: rs

#1925 RS: Added S3 compatible storage info to REST API DB import/export sources references
  content/operate/rs/7.4/references/rest-api/objects/bdb/backup_location.md
  content/operate/rs/7.4/references/rest-api/objects/bdb/dataset_import_sources.md
  content/operate/rs/7.8/references/rest-api/objects/bdb/backup_location.md
  content/operate/rs/7.8/references/rest-api/objects/bdb/dataset_import_sources.md
  content/operate/rs/references/rest-api/objects/bdb/backup_location.md
  content/operate/rs/references/rest-api/objects/bdb/dataset_import_sources.md
Labels: rs

#1939 DOC-5544 enable PHP tabbed code examples
  config.toml
  data/components/index.json
  data/components/php.json
  layouts/partials/tabs/wrapper.html
  local_examples/php/DtStringTest.php
Labels: clients

#1924 RS: Adjusted span tags with break-all style to improve readability of v2 metric names in tables
  content/embeds/rs-prometheus-metrics-v2.md
Labels: rs

#1941 RC: SAML linking must be performed by same user
  content/operate/rc/security/access-control/saml-sso/_index.md
Labels: rc

#1945 DOC-5543 deleted redundant C# examples
  local_examples/temp/PipeTransExample.cs
  local_examples/temp/prob/HomeProbExample.cs
  local_examples/temp/time_series/TimeSeriesTutorial.cs
Labels: clients

#1949 RS: Added that 7.22.0 uses RHEL 9.6 to the RHEL version vs. Redis Enterprise version table
  content/embeds/supported-platforms-embed.md
Labels: rs

#1950 K8s: yellow sub maint 1
  content/operate/kubernetes/release-notes/7-22-0-releases/7-22-0-11-june2025.md
  content/operate/kubernetes/release-notes/7-22-0-releases/7-22-0-15-july2025.md
  content/operate/kubernetes/release-notes/7-22-0-releases/7-22-0-16-august2025.md
  content/operate/kubernetes/release-notes/7-22-0-releases/_index.md
Labels: k8s

#1843 RS 7.8.6 July maintenance release notes
  content/operate/rs/release-notes/rs-7-8-releases/rs-7-8-6-152.md
Labels: rs

#1956 RS: Fixed typo in has_quorum v2 metric name
  content/embeds/rs-prometheus-metrics-v2.md
  content/operate/rs/7.8/references/metrics/prometheus-metrics-v2.md
Labels: rs

#1954 DOC-5533 Go vector set embeddings example
  content/develop/clients/go/vecsearch.md
  content/develop/clients/go/vecsets.md
  local_examples/client-specific/home_query_vec.go
  local_examples/client-specific/home_vecsets.go
Labels: clients

#1955 RS: Added crdb-cli and REST API examples to enable TLS after Active-Active database creation
  content/operate/rs/7.8/security/encryption/tls/enable-tls.md
  content/operate/rs/security/encryption/tls/enable-tls.md
Labels: rs

#1966 K8s: RZA limitation
  content/operate/kubernetes/recommendations/node-selection.md
Labels: k8s

#1973 fix-content
  content/develop/reference/modules/_index.md
Labels: dev

#1961 RS: Added generate_self_signed_certs.sh options table to create certificates
  content/operate/rs/security/certificates/create-certificates.md
Labels: rs

#1977 INT: update Redis OM Node.js page per #1952
  content/integrate/redisom-for-node-js/_index.md
Labels: integrate

#1981 DEV: FP32 (vectorsets) should explicitly document endianness
  content/commands/vadd.md
  content/commands/vemb.md
  content/commands/vlinks.md
  content/commands/vsim.md
  content/develop/data-types/vector-sets/_index.md
Labels: dev

#1974 RDSC-3962: document minimal necessary Oracle LogMinor permissions
  content/integrate/redis-data-integration/data-pipelines/prepare-dbs/oracle.md
Labels: enhancement, rdi

#1979 DEV: update search memory info
  content/commands/info.md
Labels: dev

#1993 DOC-5585 fix node-redis reconnection details
  content/develop/clients/nodejs/connect.md
  content/develop/clients/nodejs/migration.md
Labels: clients

#1994 DOC-5557 Lettuce vector index/query page
  content/develop/clients/lettuce/vecsearch.md
  local_examples/client-specific/lettuce-async/HomeQueryVecExample.java
  local_examples/client-specific/lettuce-reactive/HomeQueryVecExample.java
Labels: clients

#1989 RS: Fixed docker exec redis-cli command example in Docker quickstart
  content/operate/rs/7.4/installing-upgrading/quickstarts/docker-quickstart.md
  content/operate/rs/7.8/installing-upgrading/quickstarts/docker-quickstart.md
  content/operate/rs/installing-upgrading/quickstarts/docker-quickstart.md
Labels: rs

#1986 RS: Added missing module_list field to CRDB REST API references
  content/operate/rs/7.4/references/rest-api/objects/crdb/database_config.md
  content/operate/rs/7.8/references/rest-api/objects/crdb/database_config.md
  content/operate/rs/references/rest-api/objects/crdb/database_config.md
Labels: rs

#2007 OP: add Redis Open Source 8.2.1 release notes
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisce/redisos-8.2-release-notes.md
Labels: op

#2000 K8s: add info on default PVC size
  content/operate/kubernetes/re-clusters/expand-pvc.md
Labels: k8s

#2004 RDSC-3972: RDI now supports Google Spanner public docs
  content/embeds/rdi-supported-source-versions.md
  content/integrate/redis-data-integration/data-pipelines/prepare-dbs/spanner.md
  content/integrate/redis-data-integration/installation/install-k8s.md
Labels: rdi

#2017 fix the LEANVEC_DIM to REDUCE _index.md
  content/develop/ai/search-and-query/vectors/_index.md
Labels: dev

#2018 RS: Added missing fields to cluster_settings REST API object reference
  content/operate/rs/7.4/references/rest-api/objects/cluster_settings.md
  content/operate/rs/7.8/references/rest-api/objects/cluster_settings.md
  content/operate/rs/references/rest-api/objects/cluster_settings.md
Labels: rs

#2021 DEV: remove interactive example from XACKDEL command page
  content/commands/xackdel.md
Labels: bug, dev

#2016 refactor focus on feature not the techniques svs-compression.md
  content/develop/ai/search-and-query/vectors/_index.md
  content/develop/ai/search-and-query/vectors/svs-compression.md
Labels: dev

#2014 DEV: enhance TAG docs per GH issues
  content/develop/ai/search-and-query/advanced-concepts/tags.md
  content/develop/ai/search-and-query/indexing/_index.md
Labels: do not merge yet, dev

#2037 Update ubuntu-jammy.md
  content/operate/oss_and_stack/install/build-stack/ubuntu-jammy.md
Labels: dev

#1980 RS: 7.22.0 August maintenance release notes
  content/operate/rs/release-notes/rs-7-22-releases/rs-7-22-0-250.md
Labels: rs

#2047 K8s: relref fix
  content/operate/kubernetes/security/configuration-secrets.md
Labels: bug, k8s

#2038 RC: Add active-active throughput formula and examples
  content/operate/rc/databases/create-database/create-active-active-database.md
Labels: rc

#2052 DOC-5661 updated Jedis install version
  content/develop/clients/jedis/_index.md
Labels: clients

#2057 K8s: api aliases
  content/operate/kubernetes/reference/api/redis_enterprise_active_active_database_api.md
  content/operate/kubernetes/reference/api/redis_enterprise_cluster_api.md
  content/operate/kubernetes/reference/api/redis_enterprise_database_api.md
  content/operate/kubernetes/reference/api/redis_enterprise_remote_cluster_api.md
Labels: bug, k8s

#2062 OP: add new RediSearch release notes
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.10-release-notes.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.6-release-notes.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.8-release-notes.md
Labels: op
