Repository redis/docs, pull requests merged in 2025-01, with the labels that each got.

#1014 Create v.2.64.1.md
  content/develop/tools/insight/release-notes/v.2.64.1.md
Labels: ri

#1020 async io threads
  content/commands/client-list/index.md
  content/commands/info/index.md
Labels: do not merge yet, CE 8.0

#1018 K8s: Viking maint 1 release notes
  content/operate/kubernetes/release-notes/7-8-2-releases/7-8-2-6-jan25.md
Labels: k8s

#1016 DEV: fix code example
  content/operate/oss_and_stack/stack-with-enterprise/gears-v1/python/quickstart.md
Labels: bug, dev

#1023 DEV: correct Redis Insight on K8s instructions
  content/operate/redisinsight/install/install-on-k8s.md
Labels: bug, ri

#1009 CAPI: Small changes to get started section
  content/operate/rc/api/get-started/_index.md
  content/operate/rc/api/get-started/enable-the-api.md
  content/operate/rc/api/get-started/manage-api-keys.md
  content/operate/rc/api/get-started/manage-tasks.md
  content/operate/rc/api/get-started/process-lifecycle.md
  static/images/rc/access-management-api-keys-tab.png
  static/images/rc/access-management-create-user-key.png
  static/images/rc/access-management-user-key-add.png
Labels: rc

#1027 RC: Update Essentials region availability
  content/operate/rc/supported-regions.md
Labels: bug, rc

#1028 RC: Specify that QPF is available on 7.2 and later only
  content/operate/rc/changelog/july-2024.md
  content/operate/rc/databases/configuration/advanced-capabilities.md
  content/operate/rc/databases/create-database/create-pro-database-existing.md
  content/operate/rc/databases/create-database/create-pro-database-new.md
Labels: rc

#1029 OP: add RedisJSON release notes
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisjson/redisjson-2.4-release-notes.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisjson/redisjson-2.6-release-notes.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisjson/redisjson-2.8-release-notes.md
Labels: dev

#1021 Removed Graph, T&F
  content/operate/oss_and_stack/stack-with-enterprise/enterprise-capabilities.md
Labels: dev

#1030 OP: add relnotes for search, bloom, and time series
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisbloom/redisbloom-2.4-release-notes.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisbloom/redisbloom-2.6-release-notes.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisbloom/redisbloom-2.8-release-notes.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.10-release-notes.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.6-release-notes.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.8-release-notes.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redistimeseries/redistimeseries-1.10-release-notes.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redistimeseries/redistimeseries-1.12-release-notes.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redistimeseries/redistimeseries-1.8-release-notes.md
Labels: dev

#1004 INT: improve K8s secret setting page
  content/integrate/redis-data-integration/data-pipelines/deploy.md
Labels: do not merge yet, dev, rdi

#1022 Update quick-start.md
  content/operate/kubernetes/deployment/quick-start.md
Labels: k8s

#1035 RC: Specify internal IP standard for Prometheus on Redis Cloud
  content/integrate/prometheus-with-redis-cloud/_index.md
Labels: rc

#932 DOC-4603 added missing sink HA properties
  content/integrate/redis-data-integration/data-pipelines/data-pipelines.md
Labels: rdi

#1045 DEV: add details to RI supported platforms page
  content/operate/redisinsight/install/install-on-desktop.md
Labels: ri

#1053 RS: Fix typo in search code example
  content/operate/oss_and_stack/stack-with-enterprise/search/scalable-query-best-practices.md
Labels: bug, rs

#1051 RC API: Minor fixes to least-viewed example pages
  content/operate/rc/api/examples/audit-system-logs.md
  content/operate/rc/api/examples/back-up-and-import-data.md
  content/operate/rc/api/examples/dryrun-cost-estimates.md
Labels: rc

#1047 INT: remove RedisVL docs and point to new RTD site
  content/develop/ai/index.md
  content/integrate/redisvl/_index.md
  content/integrate/redisvl/api/_index.md
  content/integrate/redisvl/api/cache.md
  content/integrate/redisvl/api/filter.md
  content/integrate/redisvl/api/query.md
  content/integrate/redisvl/api/schema.md
  content/integrate/redisvl/api/searchindex.md
  content/integrate/redisvl/api/vectorizer.md
  content/integrate/redisvl/docs.md
  content/integrate/redisvl/install.md
  content/integrate/redisvl/overview/_index.md
  content/integrate/redisvl/overview/cli.md
  content/integrate/redisvl/overview/install.md
  content/integrate/redisvl/user-guide/_index.md
  content/integrate/redisvl/user-guide/get-started.md
  content/integrate/redisvl/user-guide/json-v-hashes.md
  content/integrate/redisvl/user-guide/query-filter.md
  content/integrate/redisvl/user-guide/semantic-caching.md
  content/integrate/redisvl/user-guide/vectorizers.md
Labels: dev

#1056 DEV: fix code example on INCRBYFLOAT command page
  content/commands/incrbyfloat/index.md
Labels: bug, dev

#1052 DEV: add query performance tuning page
  content/develop/interact/search-and-query/best-practices/_index.md
  content/develop/interact/search-and-query/best-practices/scalable-query-best-practices.md
Labels: dev

#1057 Update forget docs for ban-list propagation
  content/commands/cluster-forget/index.md
Labels: dev

#1061 DOC-4737 RDI release notes for v1.4.4
  content/integrate/redis-data-integration/release-notes/rdi-1-4-4.md
Labels: rdi

#1024 RS: Add REST API examples for creating & associating roles and ACLs with databases
  content/operate/rs/security/access-control/create-cluster-roles.md
  content/operate/rs/security/access-control/create-combined-roles.md
  content/operate/rs/security/access-control/create-db-roles.md
Labels: rs

#1063 INT+RS: fix a few bugs
  content/integrate/datadog-with-redis-cloud/_index.md
  content/integrate/datadog-with-redis-enterprise/_index.md
  content/operate/rs/installing-upgrading/install/plan-deployment/supported-platforms.md
Labels: bug, rs

#570 RC: RDI in the cloud
  content/operate/rc/databases/rdi/_index.md
  content/operate/rc/databases/rdi/define.md
  content/operate/rc/databases/rdi/setup.md
  content/operate/rc/databases/rdi/view-edit.md
  static/images/rc/rdi/pipeline-status-error.png
  static/images/rc/rdi/pipeline-status-initial-sync.png
  static/images/rc/rdi/pipeline-status-stopped.png
  static/images/rc/rdi/pipeline-status-streaming.png
  static/images/rc/rdi/rdi-add-schema.png
  static/images/rc/rdi/rdi-complete-setup.png
  static/images/rc/rdi/rdi-configure-new-pipeline.png
  static/images/rc/rdi/rdi-continue-button.png
  static/images/rc/rdi/rdi-create-data-pipeline.png
  static/images/rc/rdi/rdi-define-connectivity.png
  static/images/rc/rdi/rdi-define-pipeline-cidr.png
  static/images/rc/rdi/rdi-define-source-database.png
  static/images/rc/rdi/rdi-delete-schema.png
  static/images/rc/rdi/rdi-edit-button.png
  static/images/rc/rdi/rdi-missing-unique-constraint.png
  static/images/rc/rdi/rdi-pipeline-setup-in-progress.png
  static/images/rc/rdi/rdi-select-columns.png
  static/images/rc/rdi/rdi-select-constraints.png
  static/images/rc/rdi/rdi-select-source-data.png
  static/images/rc/rdi/rdi-select-source-db.png
  static/images/rc/rdi/rdi-setup-connectivity-arn.png
  static/images/rc/rdi/rdi-source-dataset-size.png
  static/images/rc/rdi/rdi-start-ingest.png
  static/images/rc/rdi/rdi-start-pipeline-setup.png
  static/images/rc/rdi/rdi-status-metrics-tables.png
Labels: do not merge yet, rc

#1067 DEV: add BFLOAT16 and FLOAT16 vector examples
  content/develop/interact/search-and-query/advanced-concepts/vectors.md
Labels: dev

#1062 DEV: add RQE dev to prod page
  content/develop/interact/search-and-query/best-practices/dev-to-prod-best-practices.md
Labels: do not merge yet, dev

#1037 DOC-4423: add TCEs for various command pages
  content/commands/auth/index.md
  content/commands/flushall/index.md
  content/commands/hgetall/index.md
  content/commands/hvals/index.md
  content/commands/info/index.md
  content/commands/llen/index.md
  content/commands/lpop/index.md
  content/commands/lpush/index.md
  content/commands/lrange/index.md
  content/commands/rpop/index.md
  content/commands/rpush/index.md
  content/commands/sadd/index.md
  content/commands/smembers/index.md
Labels: dev

#1001 RS: Add rolling upgrade method for RS without OS upgrade
  content/operate/rs/installing-upgrading/upgrading/_index.md
  content/operate/rs/installing-upgrading/upgrading/upgrade-cluster.md
Labels: rs

#1060 DOC-4732 added TCE markup to geo index page
  content/develop/interact/search-and-query/indexing/geoindex.md
Labels: do not merge yet

#1079 DEV: fix typo on cluster spec page
  content/operate/oss_and_stack/reference/cluster-spec.md
Labels: bug, dev

#1080 DOC-4744 added updated SQL Server prep instructions
  content/integrate/redis-data-integration/data-pipelines/prepare-dbs/sql-server.md
Labels: rdi

#1087 Revert "DEV: fix code example on INCRBYFLOAT command page"
  content/commands/incrbyfloat/index.md
Labels: dev

#1081 Change "Scalability" section to "Performance" section
  content/operate/rc/databases/configuration/clustering.md
  content/operate/rc/databases/create-database/create-pro-database-existing.md
  content/operate/rc/databases/view-edit-database.md
  static/images/rc/database-details-configuration-tab-scalability-flexible.png
  static/images/rc/database-new-flexible-scalability.png
Labels: rc

#1043 RC: Enhance throughput section
  content/operate/rc/changelog/may-2024.md
  content/operate/rc/databases/configuration/clustering.md
  content/operate/rc/databases/configuration/sizing.md
  content/operate/rc/databases/create-database/create-active-active-database.md
  content/operate/rc/databases/create-database/create-pro-database-existing.md
  content/operate/rc/databases/create-database/create-pro-database-new.md
  content/operate/rc/databases/view-edit-database.md
  static/images/rc/database-details-configuration-tab-scalability-flexible.png
  static/images/rc/database-new-flexible-scalability.png
Labels: rc

#1078 Update hardware-requirements-embed.md
  content/embeds/hardware-requirements-embed.md
Labels: rs

#1068 RS: 7.4.6 January maintenance release notes
  content/operate/rs/release-notes/rs-7-4-2-releases/rs-7-4-6-188.md
Labels: do not merge yet, rs

#1094 JSON.SET - clarify return value; more examples
  content/commands/json.set/index.md
Labels: dev

#1088 RS: Fix RedisGears dependencies path for offline install for later RS versions
  content/operate/oss_and_stack/stack-with-enterprise/gears-v1/installing-redisgears.md
Labels: rs

#1099 K8s: Roosevelt maint 4 release notes
  content/operate/kubernetes/release-notes/7-2-4-releases/7-2-4-12-jan25.md
Labels: k8s

#1101 RC: Fix bug on Clustering Redis Databases page
  content/operate/rc/databases/configuration/clustering.md
Labels: bug, rc

#1095 fix: top nav subnav spacing and footer overlay
  layouts/partials/footer.html
  layouts/partials/header/products-dropdown.html
  layouts/partials/header/resources-dropdown.html
Labels: bug, ui

#1098 DOC-4772 added latest RDI version variable and updated a command line
  config.toml
  content/integrate/redis-data-integration/installation/install-vm.md
Labels: rdi

#1102 RS: Fix potentially misleading entries in supported upgrade paths table
  content/embeds/rs-upgrade-paths.md
  content/operate/rs/installing-upgrading/upgrading/upgrade-database.md
Labels: rs

#1084 RS: Port 53 must be available for RS installation on any OS
  content/embeds/port-53.md
  content/operate/rs/7.4/installing-upgrading/install/prepare-install/port-availability.md
  content/operate/rs/7.4/installing-upgrading/quickstarts/redis-enterprise-software-quickstart.md
  content/operate/rs/7.4/networking/port-configurations.md
  content/operate/rs/installing-upgrading/install/prepare-install/port-availability.md
  content/operate/rs/installing-upgrading/quickstarts/redis-enterprise-software-quickstart.md
  content/operate/rs/networking/port-configurations.md
Labels: rs

#1083 RS: Fix module prerequisites for OS upgrade
  content/operate/rs/installing-upgrading/upgrading/upgrade-os.md
Labels: rs
