Repository redis/docs, pull requests merged in 2025-05, with the labels that each got.

#1486 DOC-5161 updated RDI requirement details
  content/embeds/rdi-db-reqs.md
  content/embeds/rdi-k8s-reqs.md
  content/embeds/rdi-os-reqs.md
  content/embeds/rdi-vm-reqs.md
  content/integrate/redis-data-integration/data-pipelines/prepare-dbs/_index.md
  content/integrate/redis-data-integration/installation/install-k8s.md
  content/integrate/redis-data-integration/installation/install-vm.md
  content/integrate/redis-data-integration/installation/reqsummary.md
  content/integrate/redis-data-integration/installation/upgrade.md
  content/integrate/redis-data-integration/quick-start-guide.md
Labels: rdi

#1488 SITE: remove licensing blurb from README.md
  README.md
Labels: bug

#1497 Update Debian installation instructions
  content/operate/oss_and_stack/install/install-stack/apt.md
Labels: dev, CE 8.0

#1496 Update rpm installation instructions
  content/operate/oss_and_stack/install/install-stack/rpm.md
Labels: dev, CE 8.0

#1498 DEV: complete installation pages
  content/operate/oss_and_stack/install/install-stack/binaries.md
Labels: CE 8.0, op

#1499 Fixed support and download center links in RS module docs
  content/operate/oss_and_stack/stack-with-enterprise/install/add-module-to-cluster.md
  content/operate/rs/references/rest-api/requests/modules/_index.md
Labels: rs

#1505 DEV: add Redis 8 rel. notes and update configuration pages
  content/operate/oss_and_stack/management/config-file.md
  content/operate/oss_and_stack/management/config.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisce/redisce-7.4-release-notes.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisce/redisos-8.0.0-release-notes.md
Labels: dev, CE 8.0

#1500 K8s: Wisconsin maint 2 release notes
  content/operate/kubernetes/release-notes/7-8-6-releases/7-8-6-1-may2025.md
Labels: k8s

#1504 DOC-5201 added release notes for RDI v1.6.7
  config.toml
  content/integrate/redis-data-integration/installation/install-k8s.md
  content/integrate/redis-data-integration/installation/install-vm.md
  content/integrate/redis-data-integration/installation/upgrade.md
  content/integrate/redis-data-integration/release-notes/rdi-1-6-7.md
Labels: rdi

#1513 DOC-5197 remove mentions of Debezium `application.config` in RDI config docs
  content/integrate/redis-data-integration/data-pipelines/data-denormalization.md
  content/integrate/redis-data-integration/data-pipelines/data-pipelines.md
Labels: rdi

#1512 RS: Emphasize upgrade prerequisites
  content/operate/rs/installing-upgrading/upgrading/_index.md
  content/operate/rs/installing-upgrading/upgrading/upgrade-cluster.md
  content/operate/rs/installing-upgrading/upgrading/upgrade-database.md
  content/operate/rs/installing-upgrading/upgrading/upgrade-os.md
Labels: rs

#1517 K8s: relref fixes
  content/operate/kubernetes/active-active/_index.md
  content/operate/kubernetes/active-active/create-aa-crdb-cli.md
  content/operate/kubernetes/active-active/create-reaadb.md
  content/operate/kubernetes/active-active/edit-clusters.md
  content/operate/kubernetes/active-active/global-db-secret.md
  content/operate/kubernetes/active-active/prepare-clusters.md
  content/operate/kubernetes/architecture/_index.md
  content/operate/kubernetes/architecture/deployment-options.md
  content/operate/kubernetes/deployment/container-images.md
  content/operate/kubernetes/deployment/helm.md
  content/operate/kubernetes/deployment/openshift/_index.md
  content/operate/kubernetes/deployment/quick-start.md
  content/operate/kubernetes/networking/_index.md
  content/operate/kubernetes/networking/ingress.md
  content/operate/kubernetes/networking/ingressorroutespec.md
  content/operate/kubernetes/networking/istio-ingress.md
  content/operate/kubernetes/re-clusters/cluster-recovery.md
  content/operate/kubernetes/re-clusters/connect-prometheus-operator.md
  content/operate/kubernetes/re-clusters/multi-namespace.md
  content/operate/kubernetes/re-databases/db-controller.md
  content/operate/kubernetes/recommendations/persistent-volumes.md
  content/operate/kubernetes/recommendations/sizing-on-kubernetes.md
  content/operate/kubernetes/upgrade/_index.md
Labels: bug, k8s

#1527 RS: Added bigstore_enabled to node REST API reference
  content/operate/rs/references/rest-api/objects/node.md
Labels: rs

#1518 K8s: add alias for link used in redis.io blog
  content/operate/kubernetes/architecture/_index.md
Labels: bug, k8s

#1501 K8s: x86 vs ARM note
  content/operate/kubernetes/reference/supported_k8s_distributions.md
Labels: k8s

#1485 Correct .zshrc path
  content/operate/oss_and_stack/install/install-stack/homebrew.md
Labels: bug, dev, needs CLA

#1492 RC RDI: Update screenshots and add specific steps for RDS/Aurora
  content/operate/rc/databases/rdi/define.md
  content/operate/rc/databases/rdi/setup.md
  content/operate/rc/databases/rdi/view-edit.md
  static/images/rc/rdi/pipeline-status-error.png
  static/images/rc/rdi/pipeline-status-initial-sync.png
  static/images/rc/rdi/pipeline-status-stopped.png
  static/images/rc/rdi/pipeline-status-streaming.png
  static/images/rc/rdi/rdi-add-schema.png
  static/images/rc/rdi/rdi-apply-changes.png
  static/images/rc/rdi/rdi-complete-setup.png
  static/images/rc/rdi/rdi-configure-new-pipeline.png
  static/images/rc/rdi/rdi-continue-button.png
  static/images/rc/rdi/rdi-create-data-pipeline.png
  static/images/rc/rdi/rdi-define-connectivity.png
  static/images/rc/rdi/rdi-define-pipeline-cidr.png
  static/images/rc/rdi/rdi-define-source-database.png
  static/images/rc/rdi/rdi-delete-schema.png
  static/images/rc/rdi/rdi-edit-button.png
  static/images/rc/rdi/rdi-missing-unique-constraint.png
  static/images/rc/rdi/rdi-pipeline-setup-in-progress.png
  static/images/rc/rdi/rdi-select-colummns.png
  static/images/rc/rdi/rdi-select-constraints.png
  static/images/rc/rdi/rdi-select-source-data.png.png
  static/images/rc/rdi/rdi-select-source-db.png
  static/images/rc/rdi/rdi-setup-diagram-aurora.png
  static/images/rc/rdi/rdi-setup-diagram-ec2.png
  static/images/rc/rdi/rdi-source-dataset-size.png
  static/images/rc/rdi/rdi-start-ingest.png
  static/images/rc/rdi/rdi-update-preferences.png
Labels: rc

#1420 RC: Account address separation
  content/embeds/rc-credit-card-add.md
  content/operate/rc/accounts/account-settings.md
  content/operate/rc/billing-and-payments.md
  content/operate/rc/changelog/may-2025.md
  content/operate/rc/databases/create-database/create-active-active-database.md
  content/operate/rc/databases/create-database/create-essentials-database.md
  content/operate/rc/databases/create-database/create-flex-database.md
  content/operate/rc/databases/create-database/create-pro-database-new.md
  static/images/rc/account-settings-account-tab.png
  static/images/rc/account-settings-change-business-info.png
  static/images/rc/billing-add-credit-card.png
  static/images/rc/billing-add-first-card.png
  static/images/rc/subscription-new-flexible-cardlist.png
Labels: do not merge yet, rc

#1546 Update aws-console.md
  content/operate/rc/subscriptions/bring-your-own-cloud/cloud-account-settings.md
  content/operate/rc/subscriptions/bring-your-own-cloud/iam-resources/_index.md
  content/operate/rc/subscriptions/bring-your-own-cloud/iam-resources/aws-console.md
  content/operate/rc/subscriptions/bring-your-own-cloud/iam-resources/cloudformation.md
  content/operate/rc/subscriptions/bring-your-own-cloud/iam-resources/terraform.md
  content/operate/rc/subscriptions/bring-your-own-cloud/subscription-whitelist.md
Labels: rc

#1374 RC: Version managment phase B
  content/operate/_index.md
  content/operate/rc/changelog/april-2025.md
  content/operate/rc/changelog/may-2025.md
  content/operate/rc/databases/create-database/create-active-active-database.md
  content/operate/rc/databases/create-database/create-pro-database-existing.md
  content/operate/rc/databases/create-database/create-pro-database-new.md
  content/operate/rc/databases/upgrade-version.md
  content/operate/rc/databases/view-edit-database.md
  content/operate/rc/subscriptions/view-pro-subscription.md
  static/images/rc/button-upgrade.png
  static/images/rc/create-database-active-active.png
  static/images/rc/database-new-flexible.png
  static/images/rc/database-version-upgrade.png
  static/images/rc/databases-more-actions-menu.png
  static/images/rc/flexible-add-database-basic.png
Labels: do not merge yet, rc

#1549 DOC-5223 RDI release notes for v1.8.0
  config.toml
  content/integrate/redis-data-integration/installation/install-k8s.md
  content/integrate/redis-data-integration/installation/install-vm.md
  content/integrate/redis-data-integration/installation/upgrade.md
  content/integrate/redis-data-integration/release-notes/rdi-1-8-0.md
  layouts/shortcodes/rdi-version.html
Labels: rdi

#1553 DEV: update RESP2/3 annotation
  content/develop/reference/protocol-spec.md
Labels: dev

#1555 OP: add annotation re. cluster upgrade and RQE
  content/operate/oss_and_stack/install/upgrade/cluster.md
Labels: op

#1556 OP: add ROS 8.0.1 release notes
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisce/redisos-8.0.1-release-notes.md
Labels: op

#1560 RS: Added shard migration status resolved issue to the RS 7.8.6-60 release notes
  content/operate/rs/release-notes/rs-7-8-releases/rs-7-8-6-60.md
Labels: rs

#1544 RC RDI: Add more setup databases pages
  content/integrate/redis-data-integration/data-pipelines/prepare-dbs/aws-aur-pgsql.md
  content/integrate/redis-data-integration/data-pipelines/prepare-dbs/aws-aurora-rds/_index.md
  content/integrate/redis-data-integration/data-pipelines/prepare-dbs/aws-aurora-rds/aws-aur-mysql.md
  content/integrate/redis-data-integration/data-pipelines/prepare-dbs/aws-aurora-rds/aws-aur-pgsql.md
  content/integrate/redis-data-integration/data-pipelines/prepare-dbs/aws-aurora-rds/aws-rds-sqlserver.md
  content/operate/rc/databases/rdi/setup.md
Labels: do not merge yet

#1558 DEV: beginning of Develop landing page redesign
  content/develop/_index.md
  layouts/develop/list.html
  layouts/develop/single.html
Labels: do not merge yet, dev

#1568 DEV: isolate CLI widget to primary list page only
  layouts/develop/list.html
Labels: bug, dev

#1563 RC: Active-Active Limitations and High Availability changes
  content/operate/rc/databases/configuration/active-active-redis.md
  content/operate/rc/databases/configuration/high-availability.md
  content/operate/rc/databases/create-database/create-active-active-database.md
Labels: bug

#1559 RS: Added more details about bigstore_enabled to REST API reference
  content/operate/rs/references/rest-api/objects/bootstrap/node_identity.md
  content/operate/rs/references/rest-api/objects/cluster/_index.md
  content/operate/rs/references/rest-api/objects/node.md
  content/operate/rs/references/rest-api/requests/bootstrap/_index.md
Labels: rs

#1572 DEV: isolate CLI widget to primary list page (re-open)
  layouts/develop/list.html
Labels: bug, dev

#1571 RS: Added DNS record update step to cluster and OS upgrade instructions
  content/operate/rs/installing-upgrading/upgrading/upgrade-cluster.md
  content/operate/rs/installing-upgrading/upgrading/upgrade-os.md
Labels: rs

#1545 RS: Added REST API examples to import databases
  content/operate/rs/databases/import-export/import-data.md
Labels: rs

#1552 RS: All nodes in a cluster should use the same user/group during install
  content/operate/rs/installing-upgrading/install/customize-user-and-group.md
Labels: rs

#1564 RS: Fixed outdated password rotation and authorize user docs
  content/operate/rs/references/rest-api/requests/users/authorize.md
  content/operate/rs/references/rest-api/requests/users/password.md
  content/operate/rs/release-notes/rs-7-8-releases/_index.md
  content/operate/rs/release-notes/rs-7-8-releases/rs-7-8-2-34.md
  content/operate/rs/security/access-control/manage-passwords/rotate-passwords.md
Labels: rs

#1166 DOC-4816 added Jedis AMR connection page
  content/develop/clients/jedis/amr.md
Labels: do not merge yet

#1169 DOC-4819 added Lettuce AMR example
  content/develop/clients/lettuce/amr.md
Labels: do not merge yet

#1567 DOC-5131 first attempt at links/formatting for develop landing page
  content/develop/_index.md
  layouts/develop/list.html
  static/images/icon_logo/icon-data-structures-32-midnight.png
  static/images/icon_logo/icon-developers-32-midnight.png
  static/images/icon_logo/icon-text-search-32-midnight.png
Labels: enhancement, dev

#1583 7.22-rn-alon.md
  content/operate/rs/release-notes/rs-7-22-releases/_index.md
  content/operate/rs/release-notes/rs-7-22-releases/rs-7-22-0-95.md
Labels: rs

#1584 DEV/OP: make is possible to hide in-page TOC with frontmatter
  layouts/develop/single.html
  layouts/integration/list.html
  layouts/integration/single.html
  layouts/operate/list.html
  layouts/operate/single.html
Labels: dev, ui, op

#1586 DEV: leave TOC intact
  content/develop/_index.md
Labels: bug, dev

#1588 RC: New pricing images phase 1
  static/images/rc/create-database-subscription-essentials.png
  static/images/rc/create-database-subscription-flex.png
  static/images/rc/create-database-subscription-pro-new.png
  static/images/rc/subscription-new-fixed-tiers.png
Labels: do not merge yet, rc

#1594 Update sorted-sets.md
  content/develop/data-types/sorted-sets.md
Labels: bug, dev

#1595 DEV: fix bug on list datatype page
  content/develop/data-types/lists.md
Labels: bug, dev

#1596 RS: Added known issue and workaround for import RDB file in RHEL 8/9 to RS 7.8.4 release notes
  content/operate/rs/release-notes/rs-7-8-releases/_index.md
  content/operate/rs/release-notes/rs-7-8-releases/rs-7-8-4-18.md
  content/operate/rs/release-notes/rs-7-8-releases/rs-7-8-4-66.md
  content/operate/rs/release-notes/rs-7-8-releases/rs-7-8-4-95.md
  content/operate/rs/release-notes/rs-7-8-releases/rs-7-8-6-13.md
  content/operate/rs/release-notes/rs-7-8-releases/rs-7-8-6-36.md
Labels: rs

#1600 DEV: swap out graphics on landing page
  content/develop/_index.md
  static/images/dev/icons/icon-redis-code-64-duotone.png
  static/images/dev/icons/icon-redis-insight-64-duotone.png
Labels: dev

#1579 RDSC-3434: Add documentation for MongoDB
  content/embeds/rdi-supported-source-versions.md
  content/integrate/redis-data-integration/data-pipelines/prepare-dbs/mongodb.md
Labels: documentation, rdi

#1609 K8s: remove preview/GA message for REAADB
  content/operate/kubernetes/7.4.6/active-active/create-reaadb.md
  content/operate/kubernetes/7.4.6/active-active/global-config.md
  content/operate/kubernetes/7.4.6/active-active/global-db-secret.md
  content/operate/kubernetes/7.4.6/active-active/prepare-clusters.md
  content/operate/kubernetes/7.8.4/active-active/create-reaadb.md
  content/operate/kubernetes/7.8.4/active-active/global-config.md
  content/operate/kubernetes/7.8.4/active-active/global-db-secret.md
  content/operate/kubernetes/7.8.4/active-active/prepare-clusters.md
  content/operate/kubernetes/7.8.6/active-active/create-reaadb.md
  content/operate/kubernetes/7.8.6/active-active/global-config.md
  content/operate/kubernetes/7.8.6/active-active/global-db-secret.md
  content/operate/kubernetes/7.8.6/active-active/prepare-clusters.md
  content/operate/kubernetes/active-active/create-reaadb.md
  content/operate/kubernetes/active-active/global-config.md
  content/operate/kubernetes/active-active/global-db-secret.md
  content/operate/kubernetes/active-active/prepare-clusters.md
Labels: k8s

#1611 RS: Fixed instances typo in auto tiering docs
  content/operate/rs/7.4/databases/auto-tiering/_index.md
  content/operate/rs/7.8/databases/auto-tiering/_index.md
  content/operate/rs/databases/auto-tiering/_index.md
Labels: rs

#1621 OP: add release notes for Redis 7.4.3, 7.4.4, and 8.0.2
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisce/redisce-7.4-release-notes.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisce/redisos-8.0-release-notes.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisce/redisos-8.0.1-release-notes.md
Labels: op

#1637 Update db-availability.md
  content/operate/rs/monitoring/db-availability.md
Labels: rs

#1645 DEV: simplify commands list layout
  layouts/commands/list.html
Labels: dev
