Repository redis/docs, pull requests merged in 2025-02, with the labels that each got.

#1120 Clarify tested dists for homebrew
  content/operate/oss_and_stack/install/install-redis/install-redis-on-mac-os.md
Labels: dev

#1123 RS: Removed port 36380 from reserved ports
  content/operate/rs/networking/port-configurations.md
Labels: rs

#1109 K8s: DOC-4785 typo
  content/operate/kubernetes/upgrade/openshift-cli.md
  content/operate/kubernetes/upgrade/upgrade-olm.md
  content/operate/kubernetes/upgrade/upgrade-redis-cluster.md
Labels: bug, k8s

#1108 K8s: docs issue 1105
  content/operate/kubernetes/security/manage-rec-credentials.md
Labels: bug, k8s

#1110 K8s: DOC-4696 fix
  content/operate/kubernetes/re-databases/replica-redb.md
Labels: bug, k8s

#1128 RS: Fix 404 for old Docker quick start path
  content/operate/rs/7.4/installing-upgrading/quickstarts/docker-quickstart.md
  content/operate/rs/installing-upgrading/quickstarts/docker-quickstart.md
Labels: rs

#1064 DEV: add index lifecycle page
  content/develop/interact/search-and-query/best-practices/index-mgmt-best-practices.md
Labels: dev

#1134 RS: Edit Active-Active description on durability and HA index page
  content/operate/rs/databases/durability-ha/_index.md
Labels: rs

#1138 DEV: fix memory stat description in the INFO command
  content/commands/info/index.md
Labels: bug, dev

#1137 RS: Fix misleading note about sharded pub/sub & RESP3
  content/operate/rs/references/compatibility/resp.md
Labels: rs

#1121 Update repo for compatibility with recent hugo versions
  README.md
  content/develop/data-types/hashes.md
  content/integrate/redis-data-integration/_index.md
  content/operate/rs/7.4/databases/memory-performance/memory-limit.md
  content/operate/rs/databases/memory-performance/memory-limit.md
  layouts/commands/single.html
  layouts/develop/list.html
  layouts/develop/single.html
  layouts/glossary/list.html
  layouts/glossary/single.html
  layouts/integrate/single.html
  layouts/integration/list.html
  layouts/integration/single.html
  layouts/operate/list.html
  layouts/operate/single.html
  layouts/partials/css.html
  layouts/shortcodes/table-csv.html
Labels: infrastructure

#1086 DOC-4549 improve RDI config reference
  content/integrate/redis-data-integration/data-pipelines/data-pipelines.md
  content/integrate/redis-data-integration/reference/config-yaml-reference.md
Labels: rdi

#1089 DOC-4753 added RDI upgrade guide
  content/integrate/redis-data-integration/installation/_index.md
  content/integrate/redis-data-integration/installation/upgrade.md
Labels: do not merge yet, rdi

#1114 DOC-4787 RDI release notes v1.6.0
  config.toml
  content/integrate/redis-data-integration/reference/data-transformation/lookup.md
  content/integrate/redis-data-integration/release-notes/rdi-1-6-0.md
Labels: do not merge yet, rdi

#1143 OP: add RediSearch v2.8.23, v2.10.12, and v2.6.26 release notes
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.10-release-notes.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.6-release-notes.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.8-release-notes.md
Labels: op

#1144 DEV: quick fix to TOC for index mgmt page
  content/develop/interact/search-and-query/best-practices/index-mgmt-best-practices.md
Labels: bug, dev

#1154 DEV: correct SMOVE return info
  content/commands/smove/index.md
Labels: bug, dev

#1133 RC: Pico billing unit
  content/embeds/rc-pro-use-cases-billing-units.md
  content/operate/rc/changelog/february-2025.md
Labels: do not merge yet, rc

#1130 RS: Add archived docs links to RS index page
  content/operate/rs/7.4/_index.md
  content/operate/rs/_index.md
Labels: rs

#963 RS: New procedure for change socket file location without rlutil
  content/operate/rs/installing-upgrading/configuring/change-location-socket-files.md
Labels: rs

#1146 K8s: add container runtime note
  content/operate/kubernetes/reference/supported_k8s_distributions.md
Labels: k8s

#1129 RS: Add DB config options and example to crdb-cli crdb update reference
  content/operate/rs/references/cli-utilities/crdb-cli/crdb/update.md
  content/operate/rs/references/rest-api/objects/crdb/database_config.md
Labels: rs

#1157 DEV+INT: update INFO command and Prometheus v2 metrics for search
  content/commands/info/index.md
  content/integrate/prometheus-with-redis-enterprise/prometheus-metrics-definitions.md
Labels: dev, integrate

#1162 OP: add known limitations notes to search release notes
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.10-release-notes.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.6-release-notes.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.8-release-notes.md
Labels: op

#1145 K8s: 7.8.4-8 release notes
  content/operate/kubernetes/release-notes/7-8-2-releases/7-8-2-6-jan25.md
  content/operate/kubernetes/release-notes/7-8-2-releases/7-8-2-6-nov24.md
  content/operate/kubernetes/release-notes/7-8-4-releases/7-8-4-8-feb25.md
  content/operate/kubernetes/release-notes/7-8-4-releases/_index.md
Labels: k8s, release-branch

#1168 DOC-4858 fixed broken link to CRDB page
  content/integrate/redis-data-integration/_index.md
Labels: rdi

#1165 DEV: update ACL categories for search commands
  content/commands/ft._list/index.md
  content/commands/ft.aliasadd/index.md
  content/commands/ft.aliasdel/index.md
  content/commands/ft.aliasupdate/index.md
  content/commands/ft.alter/index.md
  content/commands/ft.config-get/index.md
  content/commands/ft.config-help/index.md
  content/commands/ft.config-set/index.md
  content/commands/ft.create/index.md
  content/commands/ft.cursor-del/index.md
  content/commands/ft.cursor-read/index.md
  content/commands/ft.dictadd/index.md
  content/commands/ft.dictdel/index.md
  content/commands/ft.dictdump/index.md
  content/commands/ft.dropindex/index.md
  content/commands/ft.explain/index.md
  content/commands/ft.explaincli/index.md
  content/commands/ft.info/index.md
  content/commands/ft.profile/index.md
  content/commands/ft.search/index.md
  content/commands/ft.spellcheck/index.md
  content/commands/ft.sugadd/index.md
  content/commands/ft.sugdel/index.md
  content/commands/ft.sugget/index.md
  content/commands/ft.suglen/index.md
  content/commands/ft.syndump/index.md
  content/commands/ft.synupdate/index.md
  content/commands/ft.tagvals/index.md
Labels: dev, CE 8.0

#1171 RC: Add links to develop quick starts to cloud quick start
  content/operate/rc/rc-quickstart.md
Labels: rc

#1174 DOC-4863 update config.yaml example
  content/integrate/redis-data-integration/data-pipelines/data-pipelines.md
Labels: rdi

#1163 RS: Add missing optional services to services config REST API object
  content/operate/rs/7.4/references/rest-api/objects/services_configuration/_index.md
  content/operate/rs/7.4/references/rest-api/objects/services_configuration/alert_mgr.md
  content/operate/rs/references/rest-api/objects/services_configuration/_index.md
  content/operate/rs/references/rest-api/objects/services_configuration/alert_mgr.md
  content/operate/rs/references/rest-api/objects/services_configuration/entraid_agent_mgr.md
  content/operate/rs/references/rest-api/objects/services_configuration/ldap_agent_mgr.md
Labels: rs

#1177 RS: Add Active-Passive alias to Replica Of index
  content/operate/rs/databases/import-export/replica-of/_index.md
Labels: rs

#1170 DEV+OP: add CE8 changes to INFO cmd & Prometheus for RS pages
  content/commands/info/index.md
  content/integrate/prometheus-with-redis-enterprise/prometheus-metrics-definitions.md
Labels: dev, CE 8.0, op

#1180 DEV: collapse cmd categories and remove Stack from layouts and cmd pages
  layouts/commands/list.html
  layouts/commands/single.html
Labels: dev, CE 8.0

#1181 K8s: add resource quota warning
  content/operate/kubernetes/re-clusters/expand-pvc.md
Labels: k8s

#1189 UI: provide for level indents in right side TOC
  assets/css/index.css
  layouts/partials/docs-toc.html
Labels: ui

#1187 DOC-4876 added info about how to set eviction policy and data persistence
  content/integrate/redis-data-integration/installation/install-k8s.md
  content/integrate/redis-data-integration/installation/install-vm.md
  content/integrate/redis-data-integration/quick-start-guide.md
Labels: rdi

#1193 DOC-4884 clarified step in AWS Aurora prep instructions
  content/integrate/redis-data-integration/data-pipelines/prepare-dbs/aws-aur-pgsql.md
Labels: rdi

#1195 COMPACTION_POLICY - added warning
  content/develop/data-types/timeseries/configuration.md
Labels: dev

#1196 DOC-4884 RDI: clarify Aurora AWS prep instructions
  content/integrate/redis-data-integration/data-pipelines/prepare-dbs/aws-aur-pgsql.md
Labels: rdi

#1197 DEV: deprecate dialogs 1, 3, and 4; config. changes
  content/develop/interact/search-and-query/administration/configuration.md
  content/develop/interact/search-and-query/advanced-concepts/dialects.md
Labels: dev, CE 8.0

#1199 RS: Fix create DB REST API path for proxy policy example
  content/operate/rs/databases/configure/proxy-policy.md
Labels: rs

#1190 DOC-4852 added RDI heartbeat mechanism info
  content/integrate/redis-data-integration/reference/config-yaml-reference.md
Labels: rdi

#1202 DOC-4887 added detail about RDI password for upgrade script
  content/integrate/redis-data-integration/installation/upgrade.md
Labels: rdi

#1192 RS: Change localhost to name/IP in the Cluster Manager UI URL in quick starts
  content/embeds/cluster-setup.md
Labels: rs

#1191 RS: Add extra output field names and descriptions to rladmin status reference
  content/operate/rs/references/cli-utilities/rladmin/status.md
Labels: rs

#1198 RS: Add prerequisite to upgrade to a supported DB version before upgrading the cluster version
  content/operate/rs/installing-upgrading/upgrading/upgrade-cluster.md
  content/operate/rs/installing-upgrading/upgrading/upgrade-database.md
Labels: rs

#1182 K8s: upgrade article fixes
  content/operate/kubernetes/release-notes/7-8-4-releases/7-8-4-8-feb25.md
  content/operate/kubernetes/upgrade/_index.md
  content/operate/kubernetes/upgrade/openshift-cli.md
  content/operate/kubernetes/upgrade/upgrade-olm.md
Labels: bug, k8s

#1206 DEV: quick fixes to key-specs page
  content/develop/reference/key-specs.md
Labels: bug, dev

#1204 DEV: add new HFE commands
  content/commands/hgetdel/index.md
  content/commands/hgetdel/syntax.svg
  content/commands/hgetex/index.md
  content/commands/hgetex/syntax.svg
  content/commands/hsetex/index.md
  content/commands/hsetex/syntax.svg
  data/resp2_replies.json
  data/resp3_replies.json
Labels: dev, CE 8.0

#1211 DEV: some corrections for the previous merge...
  content/commands/hgetex/index.md
  content/commands/hsetex/index.md
  data/resp2_replies.json
  data/resp3_replies.json
Labels: dev, CE 8.0

#1212 OP: add new Bloom and Search release notes
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisbloom/redisbloom-2.4-release-notes.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisbloom/redisbloom-2.6-release-notes.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.10-release-notes.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.6-release-notes.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.8-release-notes.md
Labels: op

#1213 RC: Remove Use cases selection
  content/embeds/rc-pro-billing-units.md
  content/integrate/amazon-bedrock/set-up-redis.md
  content/operate/rc/databases/back-up-data.md
  content/operate/rc/databases/create-database/create-active-active-database.md
  content/operate/rc/databases/create-database/create-essentials-database.md
  content/operate/rc/databases/create-database/create-flex-database.md
  content/operate/rc/databases/create-database/create-pro-database-existing.md
  content/operate/rc/databases/create-database/create-pro-database-new.md
  content/operate/rc/databases/view-edit-database.md
  content/operate/rc/security/access-control/data-access-control/default-user.md
  content/operate/rc/security/database-security/tls-ssl.md
  content/operate/rc/subscriptions/upgrade-essentials-pro.md
  content/operate/rc/subscriptions/view-pro-subscription.md
  static/images/rc/button-add-new-to-pro.png
  static/images/rc/button-database-edit.png
  static/images/rc/create-database-subscription-essentials.png
  static/images/rc/create-database-subscription-flex.png
  static/images/rc/create-database-subscription-pro-existing.png
  static/images/rc/create-database-subscription-pro-new.png
  static/images/rc/database-details-configuration-tab-general-flexible.png
  static/images/rc/pro-easy-create-vendor.png
  static/images/rc/subscription-flexible-databases-tab-pending.png
  static/images/rc/subscription-list-select.png
Labels: bug, rc

#1203 DOC-4833 updated deploy instructions for K8s
  content/integrate/redis-data-integration/data-pipelines/deploy.md
  content/integrate/redis-data-integration/installation/install-k8s.md
Labels: rdi

#1234 DEV: document Unicode limitations
  content/develop/interact/search-and-query/basic-constructs/field-and-type-options.md
  content/develop/interact/search-and-query/query/full-text.md
Labels: bug, dev

#1232 Remove duplicate descriptions from CLI commands
  content/integrate/redis-data-integration/reference/cli/redis-di-add-context.md
  content/integrate/redis-data-integration/reference/cli/redis-di-configure-rdi.md
  content/integrate/redis-data-integration/reference/cli/redis-di-create.md
  content/integrate/redis-data-integration/reference/cli/redis-di-delete-all-contexts.md
  content/integrate/redis-data-integration/reference/cli/redis-di-delete-context.md
  content/integrate/redis-data-integration/reference/cli/redis-di-deploy.md
  content/integrate/redis-data-integration/reference/cli/redis-di-describe-job.md
  content/integrate/redis-data-integration/reference/cli/redis-di-dump-support-package.md
  content/integrate/redis-data-integration/reference/cli/redis-di-get-rejected.md
  content/integrate/redis-data-integration/reference/cli/redis-di-install.md
  content/integrate/redis-data-integration/reference/cli/redis-di-list-contexts.md
  content/integrate/redis-data-integration/reference/cli/redis-di-list-jobs.md
  content/integrate/redis-data-integration/reference/cli/redis-di-monitor.md
  content/integrate/redis-data-integration/reference/cli/redis-di-reset.md
  content/integrate/redis-data-integration/reference/cli/redis-di-scaffold.md
  content/integrate/redis-data-integration/reference/cli/redis-di-set-context.md
  content/integrate/redis-data-integration/reference/cli/redis-di-set-secret.md
  content/integrate/redis-data-integration/reference/cli/redis-di-start.md
  content/integrate/redis-data-integration/reference/cli/redis-di-status.md
  content/integrate/redis-data-integration/reference/cli/redis-di-stop.md
  content/integrate/redis-data-integration/reference/cli/redis-di-trace.md
  content/integrate/redis-data-integration/reference/cli/redis-di-upgrade.md
  content/integrate/redis-data-integration/reference/cli/redis-di.md
Labels: bug, rdi

#1235 DOC-4912 fix broken link to RDI configure command
  content/integrate/redis-data-integration/observability.md
Labels: rdi

#1164 RS: Add services REST API reference
  content/operate/rs/references/rest-api/requests/services/_index.md
Labels: rs

#1239 DEV: remove deprecation notice from FT.SUGADD and FT.SUGGET
  content/commands/ft.sugadd/index.md
  content/commands/ft.sugget/index.md
Labels: bug, dev
