Repository redis/docs, pull requests merged in 2025-07, with the labels that each got.

#1783 RDSC-3785: Document known issue for RDI upgrade from < 1.8.0 to >= 1.8.0
  content/integrate/redis-data-integration/installation/upgrade.md
  content/integrate/redis-data-integration/release-notes/rdi-1-8-0.md
Labels: rdi

#1787 update glossary
  content/glossary/_index.md
Labels: enhancement

#1785 K8s: alt role/rolebinding approach for multi-ns
  content/operate/kubernetes/re-clusters/multi-namespace.md
Labels: enhancement, k8s

#1789 DOC-5412: update KSN page for ROS8.2
  content/develop/use/keyspace-notifications.md
Labels: dev, ros 8.2

#1791 K8s: private images - mention admission controller
  content/operate/kubernetes/deployment/container-images.md
Labels: enhancement

#1753 Improve rack-awareness documentation for Kubernetes
  content/operate/kubernetes/recommendations/node-selection.md
Labels: k8s

#1650 RS: Added DB port access requirement for Replica Of between different RS clusters
  content/operate/rs/7.4/databases/import-export/replica-of/create.md
  content/operate/rs/7.8/databases/import-export/replica-of/create.md
  content/operate/rs/databases/import-export/replica-of/create.md
Labels: rs

#1804 K8s: alias fix - add leading slash
  content/operate/kubernetes/architecture/_index.md
Labels: bug, k8s

#1814 DEV: add 8.0.3 and 8.2-RC1 release notes
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisce/redisos-8.0-release-notes.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisce/redisos-8.2-release-notes.md
Labels: dev, ros 8.2

#1806 K8s: add call home client to downloads
  content/operate/kubernetes/release-notes/7-22-0-releases/7-22-0-11-june2025.md
  content/operate/kubernetes/release-notes/7-22-0-releases/7-22-0-7-april2025.md
Labels: k8s

#1774 RC: Prepare 2024 changelog folder before July releases
  content/operate/rc/changelog/2023/august-2023.md
  content/operate/rc/changelog/2024/_index.md
  content/operate/rc/changelog/2024/april-2024.md
  content/operate/rc/changelog/2024/december-2024.md
  content/operate/rc/changelog/2024/february-2024.md
  content/operate/rc/changelog/2024/january-2024.md
  content/operate/rc/changelog/2024/july-2024.md
  content/operate/rc/changelog/2024/june-2024.md
  content/operate/rc/changelog/2024/march-2024.md
  content/operate/rc/changelog/2024/may-2024.md
  content/operate/rc/changelog/2024/november-2024.md
  content/operate/rc/changelog/2024/october-2024.md
  content/operate/rc/changelog/april-2025.md
  content/operate/rc/changelog/february-2025.md
  content/operate/rc/changelog/june-2025.md
  content/operate/rc/changelog/march-2025.md
  content/operate/rc/changelog/may-2025.md
  content/operate/rc/changelog/version-release-notes/_index.md
Labels: do not merge yet

#1816 OP: add Redis 7.4.5 release notes
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisce/redisce-7.4-release-notes.md
Labels: op

#1803 Fix docs about the A param of KSN config
  content/develop/pubsub/keyspace-notifications.md
Labels: do not merge yet, dev, ros 8.2

#1824 DEV: fix 8.2-RC1 release notes section title
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisce/redisos-8.0-release-notes.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisce/redisos-8.2-release-notes.md
Labels: bug, dev

#1578 DOC-5254 starter docs for Redis MCP
  content/integrate/redis-mcp/_index.md
  content/integrate/redis-mcp/client-conf.md
  content/integrate/redis-mcp/install.md
Labels: do not merge yet

#1724 DOC-5348 RDI: info about at-least-once delivery and checkpointing
  content/integrate/redis-data-integration/architecture.md
Labels: rdi

#1831 DOC-5225 enabled testable Python prob examples
  content/develop/clients/redis-py/prob.md
Labels: clients

#1827 Update upgrade-cluster.md
  content/operate/rs/installing-upgrading/upgrading/upgrade-cluster.md
Labels: rs

#1822 DOC-5457: add the new SVS-VAMANA vector algorithm type
  content/develop/ai/search-and-query/indexing/field-and-type-options.md
  content/develop/ai/search-and-query/vectors.md
  static/resources/redisuniversity.yaml
Labels: dev, ros 8.2

#1833 DOC-5464 RS: Fixed role_uids type in LDAP mapping REST API examples
  content/operate/rs/7.4/references/rest-api/requests/ldap_mappings/_index.md
  content/operate/rs/7.8/references/rest-api/requests/ldap_mappings/_index.md
  content/operate/rs/references/rest-api/requests/ldap_mappings/_index.md
Labels: rs

#1830 DOC-5424 time series updates
  content/develop/data-types/timeseries/_index.md
  content/develop/data-types/timeseries/clients.md
  content/develop/data-types/timeseries/development.md
  content/develop/data-types/timeseries/out-of-order_performance_considerations.md
  content/develop/data-types/timeseries/quickstart.md
  content/develop/data-types/timeseries/reference/_index.md
  content/develop/data-types/timeseries/reference/out-of-order_performance_considerations/images/compressed-out-of-order-overhead-table.png
  content/develop/data-types/timeseries/reference/out-of-order_performance_considerations/images/compressed-overall-ops-sec-vs-out-of-order-percentage.png
  content/develop/data-types/timeseries/reference/out-of-order_performance_considerations/images/compressed-overall-p50-lat-vs-out-of-order-percentage.png
  content/develop/data-types/timeseries/reference/out-of-order_performance_considerations/images/uncompressed-out-of-order-overhead-table.png
  content/develop/data-types/timeseries/reference/out-of-order_performance_considerations/images/uncompressed-overall-ops-sec-vs-out-of-order-percentage.png
  content/develop/data-types/timeseries/reference/out-of-order_performance_considerations/images/uncompressed-overall-p50-lat-vs-out-of-order-percentage.png
  static/images/timeseries/compressed-out-of-order-overhead-table.webp
  static/images/timeseries/compressed-overall-ops-sec-vs-out-of-order-percentage.webp
  static/images/timeseries/compressed-overall-p50-lat-vs-out-of-order-percentage.webp
  static/images/timeseries/uncompressed-out-of-order-overhead-table.webp
  static/images/timeseries/uncompressed-overall-ops-sec-vs-out-of-order-percentage.webp
  static/images/timeseries/uncompressed-overall-p50-lat-vs-out-of-order-percentage.webp
Labels: do not merge yet, clients

#1842 DEV: fix example bug on TS.RANGE page
  content/commands/ts.range.md
Labels: bug, dev

#1832 Create v.2.70.1.md
  content/develop/tools/insight/release-notes/v.2.70.1.md
Labels: ri

#1856 DOC-5424 enabled TCEs in time series page
  content/develop/data-types/timeseries/_index.md
Labels: clients

#1760 RC: 8.0 in Essentials
  content/develop/whats-new/8-0.md
  content/embeds/redis8-breaking-changes-acl.md
  content/embeds/redis8-breaking-changes-rqe.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisce/redisos-8.0-release-notes.md
  content/operate/rc/changelog/july-2025.md
  content/operate/rc/changelog/version-release-notes/7-2.md
  content/operate/rc/changelog/version-release-notes/7-4.md
  content/operate/rc/changelog/version-release-notes/8-0.md
  content/operate/rc/databases/create-database/create-essentials-database.md
  static/images/rc/create-database-essentials-cloud-vendor.png
Labels: do not merge yet

#1868 DEV: patch node_redis.json branch to match repo
  data/components/node_redis.json
Labels: dev, docops

#1862 DEV: update RQE tags doc
  content/develop/ai/search-and-query/advanced-concepts/tags.md
Labels: dev

#1869 DOC-5491: add new CASE function and also augment the SVS_VAMANA chang…
  content/commands/ft.aggregate.md
  content/develop/ai/search-and-query/advanced-concepts/aggregations.md
  content/develop/ai/search-and-query/vectors.md
Labels: dev, ros 8.2

#1877 Quick .gitignore update
  .gitignore
Labels: docops

#1874 DEV: add RESP2/3 return information to the RQE commands
  content/commands/cf.exists.md
  content/commands/cms.info.md
  content/commands/cms.query.md
  content/commands/ft._list.md
  content/commands/ft.aggregate.md
  content/commands/ft.aliasadd.md
  content/commands/ft.aliasdel.md
  content/commands/ft.aliasupdate.md
  content/commands/ft.alter.md
  content/commands/ft.config-get.md
  content/commands/ft.config-help.md
  content/commands/ft.config-set.md
  content/commands/ft.create.md
  content/commands/ft.cursor-del.md
  content/commands/ft.cursor-read.md
  content/commands/ft.dictadd.md
  content/commands/ft.dictdel.md
  content/commands/ft.dictdump.md
  content/commands/ft.dropindex.md
  content/commands/ft.explain.md
  content/commands/ft.explaincli.md
  content/commands/ft.info.md
  content/commands/ft.profile.md
  content/commands/ft.search.md
  content/commands/ft.spellcheck.md
  content/commands/ft.sugadd.md
  content/commands/ft.sugdel.md
  content/commands/ft.sugget.md
  content/commands/ft.suglen.md
  content/commands/ft.syndump.md
  content/commands/ft.synupdate.md
  content/commands/ft.tagvals.md
Labels: dev

#1880 DOC-5501 temporary non-TCE examples
  content/develop/clients/dotnet/prob.md
  content/develop/clients/dotnet/transpipe.md
  content/develop/clients/jedis/prob.md
  content/develop/clients/redis-py/prob.md
Labels: clients

#1875 DOC-5495: modify vector set docs for 8.2 (initial commit)
  content/commands/vismember.md
  content/commands/vrem.md
  content/commands/vsim.md
  content/develop/data-types/vector-sets/_index.md
Labels: dev, ros 8.2

#1878 DEV: add RESP2/3 return information to the JSON commands
  content/commands/json.arrappend.md
  content/commands/json.arrindex.md
  content/commands/json.arrinsert.md
  content/commands/json.arrlen.md
  content/commands/json.arrpop.md
  content/commands/json.arrtrim.md
  content/commands/json.clear.md
  content/commands/json.debug-help.md
  content/commands/json.debug-memory.md
  content/commands/json.del.md
  content/commands/json.get.md
  content/commands/json.merge.md
  content/commands/json.mget.md
  content/commands/json.mset.md
  content/commands/json.numincrby.md
  content/commands/json.nummultby.md
  content/commands/json.objkeys.md
  content/commands/json.objlen.md
  content/commands/json.resp.md
  content/commands/json.set.md
  content/commands/json.strappend.md
  content/commands/json.strlen.md
  content/commands/json.toggle.md
  content/commands/json.type.md
Labels: dev

#1790 RS: Clarified formula and examples for disk sizing for heavy write scenarios
  content/operate/rs/clusters/optimize/disk-sizing-heavy-write-scenarios.md
Labels: rs

#1844 RS 7.22.0 July maintenance release notes
  content/operate/rs/release-notes/rs-7-22-releases/rs-7-22-0-241.md
Labels: rs

#1896 RS: Added key size metrics to v2 Prometheus metrics
  content/embeds/rs-prometheus-metrics-v2.md
Labels: rs

#1905 OP: update RediSearch release notes
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.10-release-notes.md
Labels: op

#1902 K8s: PVC expansion-RoF limitation
  content/operate/kubernetes/re-clusters/auto-tiering.md
  content/operate/kubernetes/re-clusters/expand-pvc.md
  content/operate/kubernetes/release-notes/7-22-0-releases/_index.md
  content/operate/kubernetes/release-notes/7-4-2-releases/7-4-2-12.md
  content/operate/kubernetes/release-notes/7-4-6-releases/7-4-6-2.md
  content/operate/kubernetes/release-notes/7-8-2-releases/7-8-2-6-nov24.md
Labels: bug, k8s

#1913 Removed duplicate entry for redis_server_expired_keys metric
  content/embeds/rs-prometheus-metrics-v2.md
  content/operate/rs/7.8/references/metrics/prometheus-metrics-v2.md
Labels: rs

#1912 DOC-5526 removed redundant local JS examples
  local_examples/temp/dt-vec-set.js
  local_examples/temp/time_series/dt-time-series.js
Labels: clients
