Repository redis/docs, pull requests merged in 2025-09, with the labels that each got.

#2065 DOC-5670 added PHP hash examples
  local_examples/php/DtHashTest.php
Labels: clients

#2066 DOC-5671 added PHP sets examples
  local_examples/php/DtSetsTest.php
Labels: clients

#2070 OP: add new RedisGears release notes
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisgears/redisgears-1.2-release-notes.md
Labels: op

#2074 DOC-5376 DOC-5375 temp Lettuce reactive hash and set examples
  local_examples/tmp/lettuce-reactive/HashExample.java
  local_examples/tmp/lettuce-reactive/SetExample.java
Labels: clients

#2075 DOC-5378 DOC-4758 Lettuce JSON examples
  local_examples/tmp/lettuce-async/JsonExample.java
  local_examples/tmp/lettuce-reactive/JsonExample.java
Labels: clients

#2078 K8s: Add username password formatting note
  content/operate/kubernetes/active-active/prepare-clusters.md
Labels: k8s

#2080 RS: Fixed quote characters
  content/embeds/json-active-active-conflict-resolution.md
  content/embeds/rs-observability.md
  content/operate/rs/7.4/databases/active-active/develop/_index.md
  content/operate/rs/7.4/databases/active-active/develop/data-types/hashes.md
  content/operate/rs/7.4/databases/active-active/develop/data-types/lists.md
  content/operate/rs/7.4/databases/active-active/develop/data-types/sets.md
  content/operate/rs/7.4/databases/active-active/develop/data-types/strings.md
  content/operate/rs/7.4/databases/auto-tiering/_index.md
  content/operate/rs/7.4/installing-upgrading/product-lifecycle.md
  content/operate/rs/7.4/networking/cluster-lba-setup.md
  content/operate/rs/7.4/references/rest-api/requests/bdbs/modules/config.md
  content/operate/rs/7.4/references/rest-api/requests/modules/config.md
  content/operate/rs/7.4/references/rest-api/requests/ocsp/test.md
  content/operate/rs/7.4/security/access-control/ldap/update-database-acls.md
  content/operate/rs/7.4/security/encryption/internode-encryption.md
  content/operate/rs/7.8/databases/active-active/develop/_index.md
  content/operate/rs/7.8/databases/active-active/develop/data-types/hashes.md
  content/operate/rs/7.8/databases/active-active/develop/data-types/lists.md
  content/operate/rs/7.8/databases/active-active/develop/data-types/sets.md
  content/operate/rs/7.8/databases/active-active/develop/data-types/strings.md
  content/operate/rs/7.8/databases/auto-tiering/_index.md
  content/operate/rs/7.8/installing-upgrading/product-lifecycle.md
  content/operate/rs/7.8/networking/cluster-lba-setup.md
  content/operate/rs/7.8/references/rest-api/requests/bdbs/modules/config.md
  content/operate/rs/7.8/references/rest-api/requests/modules/config.md
  content/operate/rs/7.8/references/rest-api/requests/ocsp/test.md
  content/operate/rs/7.8/security/access-control/ldap/update-database-acls.md
  content/operate/rs/7.8/security/encryption/internode-encryption.md
  content/operate/rs/databases/active-active/develop/_index.md
  content/operate/rs/databases/active-active/develop/data-types/hashes.md
  content/operate/rs/databases/active-active/develop/data-types/lists.md
  content/operate/rs/databases/active-active/develop/data-types/sets.md
  content/operate/rs/databases/active-active/develop/data-types/strings.md
  content/operate/rs/databases/auto-tiering/_index.md
  content/operate/rs/installing-upgrading/product-lifecycle.md
  content/operate/rs/networking/cluster-lba-setup.md
  content/operate/rs/references/rest-api/requests/bdbs/modules/config.md
  content/operate/rs/references/rest-api/requests/modules/config.md
  content/operate/rs/references/rest-api/requests/ocsp/test.md
  content/operate/rs/release-notes/legacy-release-notes/rs-5-2-2-august-2018.md
  content/operate/rs/release-notes/legacy-release-notes/rs-5-6-0-april-2020.md
  content/operate/rs/release-notes/rs-6-0-12-january-2021.md
  content/operate/rs/release-notes/rs-6-0-20-april-2021.md
  content/operate/rs/release-notes/rs-6-2-12.md
  content/operate/rs/release-notes/rs-6-2-18-releases/rs-6-2-18-43.md
  content/operate/rs/release-notes/rs-6-2-18-releases/rs-6-2-18-58.md
  content/operate/rs/release-notes/rs-6-2-8-october-2021.md
  content/operate/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-30.md
  content/operate/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-94.md
  content/operate/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-52.md
  content/operate/rs/release-notes/rs-7-4-2-releases/rs-7-4-2-104.md
  content/operate/rs/security/access-control/ldap/update-database-acls.md
  content/operate/rs/security/encryption/internode-encryption.md
Labels: rs

#2081 RC: check and update Unicode quotes to ASCII
  content/operate/rc/cloud-integrations/gcp-marketplace/team-management.md
  content/operate/rc/databases/configuration/clustering.md
  content/operate/rc/databases/create-database/create-flex-database.md
Labels: rc

#2083 DOC-5675 added PHP vector set examples
  local_examples/php/DtVecSetsTest.php
Labels: clients

#2098 DOC-5690 DOC-5689 DOC-5691 DOC-5692 DOC-5693 DOC-5694 DOC-5695 DOC-5696 PHP list and set cmd examples
  local_examples/php/CmdListTest.php
  local_examples/php/CmdSetTest.php
Labels: clients

#2101 DOC-5698 corrected info about Redis Cloud MCP
  content/integrate/redis-mcp/install.md
Labels: MCP

#2111 DOC-5709 fixed dodgy note formatting
  content/integrate/redis-data-integration/data-pipelines/deploy.md
Labels: rdi

#2112 RS: Copied storage engine description/link fixes to 7.8 and 7.4 versions
  content/operate/rs/7.4/databases/auto-tiering/storage-engine.md
  content/operate/rs/7.8/databases/auto-tiering/storage-engine.md
Labels: rs

#2010 RS: Customer-managed certificates for internode encryption
  assets/css/index.css
  content/operate/rs/security/certificates/_index.md
  content/operate/rs/security/certificates/updating-certificates.md
  content/operate/rs/security/encryption/internode-encryption.md
  static/js/index.js
Labels: rs

#2133 OP: update RediSearch release notes (multiple)
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.10-release-notes.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.8-release-notes.md
Labels: op

#2072 DOC-5665 Jedis failover docs
  content/develop/clients/jedis/failover.md
  content/develop/clients/jedis/produsage.md
  static/images/failover/failover-client-failback.svg
  static/images/failover/failover-client-reconnect.svg
  static/images/failover/failover-sliding-window.svg
Labels: clients

#2138 RS: Fixed outdated rladmin commands for shard placement
  content/operate/rs/7.8/databases/configure/shard-placement.md
  content/operate/rs/7.8/references/cli-utilities/rladmin/placement.md
  content/operate/rs/7.8/references/cli-utilities/rladmin/tune.md
  content/operate/rs/databases/configure/shard-placement.md
  content/operate/rs/references/cli-utilities/rladmin/placement.md
  content/operate/rs/references/cli-utilities/rladmin/tune.md
Labels: rs

#2139 RS: Fixed CLIENT CACHING & CLIENT REPLY support in compatibility table
  content/operate/rs/7.4/references/compatibility/commands/connection.md
  content/operate/rs/7.8/references/compatibility/commands/connection.md
  content/operate/rs/references/compatibility/commands/connection.md
Labels: rs

#2140 RS: Clarified RS install prereq for Auto Tiering and removed confusing circular link
  content/operate/rs/7.4/installing-upgrading/install/install-on-linux.md
  content/operate/rs/7.8/installing-upgrading/install/install-on-linux.md
  content/operate/rs/installing-upgrading/install/install-on-linux.md
Labels: rs

#2132 RS 7.4.6-272 maintenance release notes
  content/operate/rs/release-notes/rs-7-4-2-releases/rs-7-4-6-272.md
Labels: rs

#2149 RS: Auto-recovery rladmin doc updates
  content/operate/rs/7.8/databases/recover.md
  content/operate/rs/7.8/references/cli-utilities/rladmin/tune.md
  content/operate/rs/databases/recover.md
  content/operate/rs/references/cli-utilities/rladmin/tune.md
Labels: rs

#2152 RS: Added troubleshooting index with links to knowledge base
  content/operate/rs/security/encryption/tls/_index.md
  content/operate/rs/troubleshooting.md
Labels: rs

#2168 DEV: fix keyspace notifications typo
  content/develop/pubsub/keyspace-notifications.md
Labels: bug, dev

#2144 RS: Added rladmin commands to change node roles
  assets/css/index.css
  content/operate/rs/7.8/clusters/change-node-role.md
  content/operate/rs/clusters/change-node-role.md
  static/js/index.js
Labels: rs

#2174 OP: add Redisbloom release notes
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisbloom/redisbloom-2.8-release-notes.md
Labels: op

#2176 RS: Added RS162972 as a resolved issue in the 7.22.2-14 release notes
  content/operate/rs/release-notes/rs-7-22-releases/rs-7-22-2-14.md
Labels: rs

#2156 DOC-5750 clearer pointers about using RDI in Redis Insight
  content/integrate/redis-data-integration/installation/install-k8s.md
  content/integrate/redis-data-integration/installation/install-vm.md
Labels: rdi

#2169 DOC-5760 started doc support for Rust
  build/components/example.py
  build/local_examples.py
  config.toml
  content/develop/clients/_index.md
  content/develop/clients/hiredis/_index.md
  content/develop/clients/rust/_index.md
  data/components/index.json
  data/components/redis_rs_async.json
  data/components/redis_rs_sync.json
  local_examples/client-specific/rust-async/landing.rs
  local_examples/client-specific/rust-sync/landing.rs
Labels: do not merge yet, clients

#2181 RC: Add Heroku mention to RC docs
  content/embeds/rc-heroku-add-on.md
  content/integrate/heroku-redis/_index.md
  content/operate/rc/_index.md
  content/operate/rc/cloud-integrations/heroku.md
Labels: rc

#2188 DOC-5769 C# async TCE support
  build/components/example.py
  build/local_examples.py
  config.toml
  content/develop/clients/dotnet/_index.md
  content/develop/clients/dotnet/prob.md
  content/develop/clients/dotnet/transpipe.md
  content/develop/clients/dotnet/vecsets.md
  data/components/index.json
  data/components/nredisstack_async.json
  data/components/nredisstack_sync.json
  local_examples/client-specific/dotnet-async/AsyncLandingExample.cs
  local_examples/client-specific/dotnet-sync/HomeVecSetsExample.cs
  local_examples/client-specific/dotnet-sync/SyncLandingExample.cs
Labels: clients

#2190 RS: Added link to update/renew INE certs
  content/operate/rs/security/encryption/internode-encryption.md
Labels: rs

#2193 RS: Added deprecation note to old module config REST API endpoints
  content/operate/rs/7.8/references/rest-api/requests/bdbs/modules/config.md
  content/operate/rs/7.8/references/rest-api/requests/modules/config.md
  content/operate/rs/references/rest-api/requests/bdbs/modules/config.md
  content/operate/rs/references/rest-api/requests/modules/config.md
Labels: rs
