Repository redis/docs, pull requests merged in 2025-03, with the labels that each got.

#1222 RS: 7.2.4 Feb/March maintenance release
  content/operate/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-122.md
Labels: do not merge yet, rs

#1221 RS: 7.4.6 Feb/March maintenance release
  content/operate/rs/release-notes/rs-7-4-2-releases/rs-7-4-6-232.md
Labels: do not merge yet, rs

#1244 DEV: add new autocomplete page
  content/develop/interact/search-and-query/advanced-concepts/autocomplete.md
  layouts/commands/list.html
Labels: dev

#1220 RS: 7.8.4 Feb/March maintenance release docs
  content/operate/rs/release-notes/rs-7-8-releases/rs-7-8-4-95.md
Labels: rs

#1243 RC: Selecting use external endpoint blocks private endpoint
  content/operate/rc/databases/configuration/clustering.md
  content/operate/rc/databases/create-database/create-pro-database-existing.md
Labels: rc

#1245 DEV: correct autocomplete usage on tech. overview page
  content/develop/interact/search-and-query/administration/overview.md
Labels: dev

#1249 DEV: enhance tokenization docs with more references
  content/develop/interact/search-and-query/advanced-concepts/escaping.md
Labels: bug, dev

#1255 RC: Remove pricing link
  content/embeds/rc-pro-billing-units.md
Labels: bug, rc

#1256 K8s: Roosevelt maintenance release 5
  content/operate/kubernetes/release-notes/7-2-4-releases/7-2-4-12-mar25.md
Labels: do not merge yet, k8s

#1262 K8s: fix weight
  content/operate/kubernetes/release-notes/7-2-4-releases/7-2-4-12-mar25.md
Labels: bug, k8s

#1261 release.1.6-update-autogenerated-docs: Auto generated
  content/integrate/redis-data-integration/reference/api-reference/openapi.json
  content/integrate/redis-data-integration/reference/cli/redis-di-delete-all-contexts.md
  content/integrate/redis-data-integration/reference/cli/redis-di-delete-context.md
  content/integrate/redis-data-integration/reference/cli/redis-di-get-rejected.md
  content/integrate/redis-data-integration/reference/cli/redis-di-reset.md
  content/integrate/redis-data-integration/reference/cli/redis-di-upgrade.md
  content/integrate/redis-data-integration/reference/config-yaml-reference.md
Labels: rdi

#1254 DOC-4944 added release notes for v1.6.1
  config.toml
  content/integrate/redis-data-integration/release-notes/rdi-1-6-1.md
Labels: do not merge yet

#1263 DEV: fix a couple of redis-py links
  content/develop/clients/redis-py/_index.md
Labels: bug, dev

#1258 RS: Add external listener examples to audit connection events
  content/operate/rs/security/audit-events.md
Labels: rs

#1200 RS: Add REST API method to enable OSS Cluster API & rladmin tune db command to change preferred IP type
  content/operate/rs/databases/configure/oss-cluster-api.md
Labels: rs

#1271 RS: Promote the first new node during rolling upgrade
  content/operate/rs/installing-upgrading/upgrading/upgrade-cluster.md
Labels: rs

#1103 Update optimize_shards_placement.md
  content/operate/rs/references/rest-api/requests/bdbs/actions/optimize_shards_placement.md
Labels: rs

#1272 K8s: 7.4.6-6 unicorn maint 3 release notes
  content/operate/kubernetes/release-notes/7-4-6-releases/7-4-6-2-oct24.md
  content/operate/kubernetes/release-notes/7-4-6-releases/7-4-6-2-october24.md
  content/operate/kubernetes/release-notes/7-4-6-releases/7-4-6-2.md
  content/operate/kubernetes/release-notes/7-4-6-releases/7-4-6-6-dec24.md
  content/operate/kubernetes/release-notes/7-4-6-releases/7-4-6-6-mar25.md
  content/operate/kubernetes/release-notes/7-4-6-releases/_index.md
Labels: k8s

#1276 K8s: 7.8.4-9 viking maint 3
  content/operate/kubernetes/reference/supported_k8s_distributions.md
  content/operate/kubernetes/release-notes/7-8-4-releases/7-8-4-8-mar25.md
Labels: k8s

#1274 DEV: change DIALECT 4 to DIALECT 2 on adv. vector search page
  content/develop/interact/search-and-query/advanced-concepts/geo.md
  content/develop/interact/search-and-query/advanced-concepts/vectors.md
  content/develop/interact/search-and-query/basic-constructs/field-and-type-options.md
  content/develop/interact/search-and-query/indexing/geoindex.md
Labels: bug, dev

#1279 DEV: fix 404 error on Bloom filter page
  content/develop/data-types/probabilistic/bloom-filter.md
Labels: bug, dev

#1280 RC: Change "Requester CIDR" to "Redis CIDR" in VPC peering docs
  content/operate/rc/security/vpc-peering.md
Labels: bug, rc

#1281 Fix typo error of the word streams
  content/commands/xadd/index.md
Labels: bug, dev

#1284 DOC-4982 updated supported Ubuntu versions
  content/integrate/redis-data-integration/installation/install-vm.md
  content/integrate/redis-data-integration/quick-start-guide.md
Labels: rdi

#1288 RC: Some wording fixes
  content/operate/rc/databases/configuration/advanced-capabilities.md
  content/operate/rc/databases/create-database/create-pro-database-new.md
Labels: rc

#1290 DOC-4985 added section about restricting privileges
  content/integrate/redis-data-integration/data-pipelines/prepare-dbs/oracle.md
Labels: rdi

#1292 OP: add RediSearch v2.10.14 release notes
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.10-release-notes.md
Labels: op

#1294 DEV/OP: fix a few broken links (warnings)
  content/develop/interact/search-and-query/advanced-concepts/query_syntax.md
  content/develop/interact/search-and-query/advanced-concepts/stemming.md
  content/operate/oss_and_stack/stack-with-enterprise/deprecated-features/graph/graph-quickstart.md
  content/operate/oss_and_stack/stack-with-enterprise/deprecated-features/triggers-and-functions/Debugging.md
  content/operate/oss_and_stack/stack-with-enterprise/deprecated-features/triggers-and-functions/concepts/Cluster_Support.md
Labels: bug, dev, op

#1167 RC: Redis Insight Cloud
  content/operate/rc/changelog/march-2025.md
  content/operate/rc/databases/connect/_index.md
  content/operate/rc/databases/connect/insight-cloud.md
  content/operate/rc/rc-quickstart.md
  static/images/rc/rc-ri-browser-group.png
  static/images/rc/rc-ri-browser-view.png
  static/images/rc/rc-ri-cli.png
  static/images/rc/rc-ri-explore-button.png
  static/images/rc/rc-ri-explore-icon.png
  static/images/rc/rc-ri-load-data.png
  static/images/rc/rc-ri-open.png
  static/images/rc/rc-ri-wizard-launch.png
  static/images/rc/rc-ri-workbench.png
Labels: do not merge yet, rc

#1296 K8s: fix relref
  content/operate/kubernetes/release-notes/7-4-6-releases/7-4-6-6-mar25.md
Labels: bug, k8s

#1297 DEV: add new Redis versions docs
  content/develop/whats-new/6-2.md
  content/develop/whats-new/7-2.md
  content/develop/whats-new/7-4.md
  content/develop/whats-new/redis-feature-sets.md
Labels: dev

#1307 OP: add 'about' links to main Redis CE/Stack installation page
  content/operate/oss_and_stack/install/_index.md
Labels: op

#1312 DOC-5009: Create RDI release notes 1.6.2
  content/integrate/redis-data-integration/release-notes/rdi-1-6-2.md
Labels: rdi

#1316 DOC-5011 improved download links
  config.toml
  content/integrate/redis-data-integration/installation/install-k8s.md
  content/integrate/redis-data-integration/installation/install-vm.md
Labels: rdi

#1320 RC: Create Pro database changes
  content/operate/rc/databases/create-database/create-pro-database-new.md
  static/images/rc/flexible-add-database-advanced.png
  static/images/rc/flexible-add-database-basic.png
Labels: bug

#1257 RS: Add fields and descriptions returned by /v1/actions to REST API reference
  content/operate/rs/references/rest-api/requests/actions/_index.md
Labels: rs

#1324 DOC-5040 add release notes for v1.6.3
  config.toml
  content/integrate/redis-data-integration/installation/install-k8s.md
  content/integrate/redis-data-integration/installation/install-vm.md
  content/integrate/redis-data-integration/installation/upgrade.md
  content/integrate/redis-data-integration/release-notes/rdi-1-6-3.md
Labels: rdi

#1295 RS: 7.8.6 release docs
  assets/css/index.css
  content/operate/rs/monitoring/metrics_stream_engine.md
  content/operate/rs/references/cli-utilities/rladmin/cluster/change_password_hashing_algorithm.md
  content/operate/rs/references/rest-api/requests/cluster/change_password_hashing_algorithm.md
  content/operate/rs/references/rest-api/requests/roles/_index.md
  content/operate/rs/references/rest-api/requests/users/_index.md
  content/operate/rs/release-notes/rs-7-8-releases/rs-7-8-6-13.md
  content/operate/rs/security/access-control/manage-passwords/_index.md
  content/operate/rs/security/access-control/manage-passwords/password-hashing-algorithm.md
Labels: rs

#1328 K8s: remove rancher 1.29 and 1.30
  content/operate/kubernetes/reference/supported_k8s_distributions.md
  content/operate/kubernetes/release-notes/7-8-6-releases/7-8-6-1-march2025.md
Labels: bug, k8s

#1333 RS: Added missing networking docs back to 7.4 version
  content/operate/rs/7.4/databases/configure/proxy-policy.md
  content/operate/rs/7.4/networking/configuring-aws-route53-dns-redis-enterprise.md
  content/operate/rs/7.4/networking/mdns.md
  content/operate/rs/7.4/networking/multi-ip-ipv6.md
  content/operate/rs/7.4/networking/private-public-endpoints.md
Labels: rs
