Repository redis/docs, pull requests merged in 2025-04, with the labels that each got.

#1139 RC: Redis hashing policy
  content/operate/rc/changelog/february-2025.md
  content/operate/rc/changelog/march-2025.md
  content/operate/rc/databases/configuration/clustering.md
  content/operate/rc/databases/create-database/create-pro-database-new.md
  static/images/rc/database-details-configuration-tab-scalability-flexible.png
  static/images/rc/database-new-flexible-scalability.png
  static/images/rc/flexible-add-database-advanced.png
  static/images/rc/flexible-add-database-basic.png
Labels: do not merge yet, rc

#1337 RS: Fixed DHE/ECDHE ciphers support note
  content/operate/rs/7.4/security/encryption/tls/ciphers.md
  content/operate/rs/security/encryption/tls/ciphers.md
Labels: rs

#1338 RC Rebrand phase 1: Default User, Access management, MFA
  content/operate/rc/security/access-control/access-management.md
  content/operate/rc/security/access-control/multi-factor-authentication.md
  static/images/rc/access-management-delete-user-dialog.png
  static/images/rc/access-management-team-tab.png
  static/images/rc/access-mgmt-add-user-dialog.png
  static/images/rc/access-mgmt-edit-user-dialog.png
  static/images/rc/button-access-management-add.png
  static/images/rc/button-database-edit.png
  static/images/rc/button-database-password-copy.png
  static/images/rc/button-database-save.png
  static/images/rc/database-fixed-configuration-security.png
  static/images/rc/icon-access-management-delete-user.png
  static/images/rc/icon-access-management-edit-user.png
  static/images/rc/icon-list-sort-asc.png
  static/images/rc/icon-list-sort-desc.png
  static/images/rc/multi-factor-authentication-force-all-users-on.png
  static/images/rc/multi-factor-authentication-user-dropdown.png
  static/images/rc/multi-factor-authentication-user-profile.png
Labels: rc

#1319 DEV: add build from source procedures
  content/operate/oss_and_stack/install/archive/_index.md
  content/operate/oss_and_stack/install/build-stack/_index.md
  content/operate/oss_and_stack/install/build-stack/almalinux-rocky-8.md
  content/operate/oss_and_stack/install/build-stack/almalinux-rocky-9.md
  content/operate/oss_and_stack/install/build-stack/debian-bookworm.md
  content/operate/oss_and_stack/install/build-stack/debian-bullseye.md
  content/operate/oss_and_stack/install/build-stack/macos-13-14.md
  content/operate/oss_and_stack/install/build-stack/macos-15.md
  content/operate/oss_and_stack/install/build-stack/ubuntu-focal.md
  content/operate/oss_and_stack/install/build-stack/ubuntu-jammy.md
  content/operate/oss_and_stack/install/build-stack/ubuntu-noble.md
  content/operate/oss_and_stack/install/install-stack/_index.md
Labels: do not merge yet, CE 8.0

#1325 RC Rebrand phase 1: All create databases pages
  content/operate/rc/databases/create-database/create-active-active-database.md
  content/operate/rc/databases/create-database/create-essentials-database.md
  content/operate/rc/databases/create-database/create-flex-database.md
  content/operate/rc/databases/create-database/create-pro-database-existing.md
  content/operate/rc/databases/create-database/create-pro-database-new.md
  static/images/rc/active-active-json-detail.png
  static/images/rc/active-active-throughput-detail.png
  static/images/rc/button-add-new-to-pro.png
  static/images/rc/button-configuration-save.png
  static/images/rc/button-create-db-confirm-pay.png
  static/images/rc/button-database-activate.png
  static/images/rc/button-database-new.png
  static/images/rc/button-subscription-continue.png
  static/images/rc/create-database-active-active.png
  static/images/rc/create-database-essentials-cloud-vendor.png
  static/images/rc/create-database-essentials-durability.png
  static/images/rc/create-database-subscription-essentials.png
  static/images/rc/create-database-subscription-flex.png
  static/images/rc/create-database-subscription-pro-existing.png
  static/images/rc/create-database-subscription-pro-new.png
  static/images/rc/create-flexible-sub-active-active-on.png
  static/images/rc/create-pro-aa-review.png
  static/images/rc/create-pro-db-settings-custom.png
  static/images/rc/create-pro-db-settings.png
  static/images/rc/create-sub-active-active-cidr.png
  static/images/rc/create-sub-active-active-regions.png
  static/images/rc/database-new-flexible-alerts.png
  static/images/rc/database-new-flexible-durability.png
  static/images/rc/database-new-flexible-scalability.png
  static/images/rc/database-new-flexible-security.png
  static/images/rc/database-new-flexible.png
  static/images/rc/flexible-add-database-advanced.png
  static/images/rc/flexible-add-database-basic.png
  static/images/rc/icon-add-credit-card.png
  static/images/rc/icon-add-database.png
  static/images/rc/icon-cidr-address-error.png
  static/images/rc/icon-cidr-address-ok.png
  static/images/rc/icon-database-delete.png
  static/images/rc/icon-database-edit.png
  static/images/rc/icon-region-delete.png
  static/images/rc/pro-easy-create-optimal-settings.png
  static/images/rc/pro-easy-create-size-throughput.png
  static/images/rc/pro-easy-create-vendor.png
  static/images/rc/subscription-new-fixed-tiers.png
  static/images/rc/subscription-new-flex-tiers.png
  static/images/rc/subscription-new-flexible-review.png
  static/images/rc/subscription-new-flexible-setup-advanced.png
  static/images/rc/subscription-new-flexible-setup-general.png
  static/images/rc/subscription-new-flexible-sizing-tab.png
  static/images/rc/subscription-new-flexible-tabs-setup.png
  static/images/rc/subscription-new-flexible-version-section.png
  static/images/rc/tags-button-add-additional-tag.png
  static/images/rc/tags-icon-delete.png
  static/images/rc/tags-new-tag.png
Labels: rc

#1348 K8s: removed mention of RED73626
  content/operate/kubernetes/release-notes/7-8-6-releases/7-8-6-1-march2025.md
Labels: bug, k8s

#1346 RC Terraform: Include PSC
  content/integrate/terraform-provider-for-redis-cloud/_index.md
Labels: rc

#1253 Adding information to presetup database connections in Redis Insight
  content/operate/redisinsight/configuration.md
Labels: do not merge yet, ri

#1286 Create release notes for Redis Insight 2.68.0
  content/develop/tools/insight/release-notes/v.2.68.0.md
Labels: do not merge yet, ri

#1349 RC Rebrand Phase 1: Import, Backup, Delete, Monitor, Tag
  content/operate/rc/databases/delete-database.md
  content/operate/rc/databases/import-data.md
  content/operate/rc/databases/monitor-performance.md
  static/images/rc/button-danger-zone-delete.png
  static/images/rc/button-database-backup-now.png
  static/images/rc/button-database-delete.png
  static/images/rc/database-configuration-import.png
  static/images/rc/database-delete-last-dialog.png
  static/images/rc/database-details-configuration-durability-backup.png
  static/images/rc/database-metrics-interval-scrollbar.png
  static/images/rc/database-metrics-tab.png
  static/images/rc/metrics-promote-graphs.png
  static/images/rc/tags-button-manage-tags.png
  static/images/rc/tags-button-save-tags.png
  static/images/rc/tags-database-list.png
  static/images/rc/tags-icon-manage-tags.png
  static/images/rc/tags-icon-more-actions.png
  static/images/rc/tags-tag-manager.png
Labels: rc

#1359 RC Rebrand Phase 2: TLS, Migrate, and Upgrade Essentials -> Pro
  content/operate/rc/databases/migrate-databases.md
  content/operate/rc/security/database-security/tls-ssl.md
  content/operate/rc/subscriptions/upgrade-essentials-pro.md
  static/images/rc/button-account-settings-security-ca-download.png
  static/images/rc/button-database-config-security-server-ca-download.png
  static/images/rc/button-database-uri-add.png
  static/images/rc/database-add-account-path-list.png
  static/images/rc/database-details-configuration-tab-security-tls-client-auth-certificate.png
  static/images/rc/database-details-configuration-tab-security-tls-toggle.png
  static/images/rc/icon-database-save-active-passive.png
  static/images/rc/migrate-data-active-passive-enable.png
  static/images/rc/migrate-data-add-active-passive.png
  static/images/rc/migrate-data-specify-source-uri.png
  static/images/rc/migrate-data-status-synced.png
  static/images/rc/migrate-data-target-edit.png
  static/images/rc/migrate-data-tls-client-cert.png
  static/images/rc/migrate-data-tls-server-cert.png
  static/images/rc/migrate-database-select-source.png
  static/images/rc/mtls-add-client-certificate.png
  static/images/rc/mtls-certificate-details.png
  static/images/rc/mtls-download-certificate.png
Labels: rc

#1357 RC Rebrand phase 2: Manage API Keys + Enable API
  content/operate/rc/api/get-started/manage-api-keys.md
  static/images/rc/access-management-api-keys-tab.png
  static/images/rc/access-management-api-user-key-delete.png
  static/images/rc/access-management-create-user-key.png
  static/images/rc/access-management-delete-api-secret-key.png
  static/images/rc/access-management-user-key-add.png
  static/images/rc/access-management-user-key-manage-cidr.png
  static/images/rc/button-access-management-api-key-copy.png
  static/images/rc/button-access-management-api-user-key-delete.png
  static/images/rc/button-access-management-cidr-rule-add.png
  static/images/rc/button-access-management-cidr-rule-delete.png
  static/images/rc/button-access-management-cidr-rule-edit.png
  static/images/rc/button-access-management-cidr-rule-save.png
  static/images/rc/button-access-management-enable-api.png
  static/images/rc/button-access-management-hide-key.png
  static/images/rc/button-access-management-show-key.png
  static/images/rc/button-access-management-user-key-create.png
Labels: rc

#1358 DEV: point to GitHub for source downloads
  content/operate/oss_and_stack/install/build-stack/almalinux-rocky-8.md
  content/operate/oss_and_stack/install/build-stack/almalinux-rocky-9.md
  content/operate/oss_and_stack/install/build-stack/debian-bookworm.md
  content/operate/oss_and_stack/install/build-stack/debian-bullseye.md
  content/operate/oss_and_stack/install/build-stack/macos-13-14.md
  content/operate/oss_and_stack/install/build-stack/macos-15.md
  content/operate/oss_and_stack/install/build-stack/ubuntu-focal.md
  content/operate/oss_and_stack/install/build-stack/ubuntu-jammy.md
  content/operate/oss_and_stack/install/build-stack/ubuntu-noble.md
Labels: do not merge yet, CE 8.0

#1365 DEV: add multi-add example to SADD command page
  content/commands/sadd/index.md
Labels: dev

#1369 RC Rebrand phase 2: Account settings/User Profile & Logs/Reports
  content/operate/rc/accounts/account-settings.md
  content/operate/rc/api/examples/audit-system-logs.md
  content/operate/rc/billing-and-payments.md
  content/operate/rc/logs-reports/system-logs.md
  static/images/rc/account-selector-single-account.png
  static/images/rc/account-selector-switch-account.png
  static/images/rc/account-settings-account-tab.png
  static/images/rc/account-settings-buttons-save-discard.png
  static/images/rc/account-settings-change-billing-address.png
  static/images/rc/account-settings-edit-address-button.png
  static/images/rc/billing-add-credit-card.png
  static/images/rc/billing-billing-history-tab.png
  static/images/rc/billing-change-mailing-address.png
  static/images/rc/billing-credit-card-options-menu.png
  static/images/rc/billing-payment-method-tab.png
  static/images/rc/billing-payments-credits-tab.png
  static/images/rc/billing-update-billing-address.png
  static/images/rc/button-billing-payments-apply.png
  static/images/rc/button-billing-save-card.png
  static/images/rc/button-cost-report-download.png
  static/images/rc/icon-billing-download.png
  static/images/rc/system-logs-export.png
  static/images/rc/system-logs-refresh.png
  static/images/rc/system-logs.png
  static/images/rc/usage-report-memory-usage.png
  static/images/rc/user-profile-settings.png
Labels: rc

#1370 RC Rebrand Phase 2: Advanced Capabilities and High Availability
  content/operate/rc/databases/configuration/advanced-capabilities.md
  content/operate/rc/databases/configuration/high-availability.md
  static/images/rc/availability-zones-aws-hosted-no-multi-az.png
  static/images/rc/availability-zones-multi-az.png
  static/images/rc/availability-zones-no-multi-az.png
  static/images/rc/database-details-modules-stack-free.png
  static/images/rc/database-details-query-performance-factor-pro.png
  static/images/rc/database-details-redis-module-select-flexible.png
  static/images/rc/new-database-general-type-free-stack.png
Labels: rc

#1373 K8s: Wisconsin maintenance 1 release notes
  content/operate/kubernetes/release-notes/7-8-6-releases/7-8-6-1-april2025.md
Labels: k8s

#1355 RS 7.8.6-36 April maintenance release notes
  content/operate/rs/release-notes/rs-7-8-releases/rs-7-8-6-36.md
Labels: rs

#1382 OP: remove AppImage installation instructions for CE8
  content/operate/oss_and_stack/install/install-stack/appimage.md
Labels: bug

#1383 DEV: remove superfluous RQE config. page
  content/develop/interact/search-and-query/basic-constructs/configuration-parameters.md
Labels: bug, dev

#1388 DOC-5083 added release notes for RDI v1.6.5
  config.toml
  content/integrate/redis-data-integration/installation/install-k8s.md
  content/integrate/redis-data-integration/installation/install-vm.md
  content/integrate/redis-data-integration/installation/upgrade.md
  content/integrate/redis-data-integration/release-notes/rdi-1-6-5.md
Labels: rdi

#1386 Update JSON _index.md
  content/develop/data-types/json/_index.md
Labels: dev

#1385 Add executeIsolated recommendation to node-redis docs
  content/develop/clients/nodejs/transpipe.md
Labels: dev

#1391 DEV: some quick touch ups on the Redis 8.0-RC1 page
  content/develop/whats-new/8-0-rc-1.md
Labels: dev

#1147 K8s: Simplify the update REC credential step
  content/operate/kubernetes/security/manage-rec-credentials.md
Labels: k8s

#1403 OP: add aliases for moved files
  content/operate/oss_and_stack/install/archive/install-redis/_index.md
  content/operate/oss_and_stack/install/archive/install-redis/install-redis-from-source.md
  content/operate/oss_and_stack/install/archive/install-redis/install-redis-on-linux.md
  content/operate/oss_and_stack/install/archive/install-redis/install-redis-on-mac-os.md
  content/operate/oss_and_stack/install/archive/install-redis/install-redis-on-windows.md
  content/operate/oss_and_stack/install/install-stack/homebrew.md
Labels: bug, op

#1401 RS: Added support package options for the CM UI
  content/operate/rs/installing-upgrading/creating-support-package.md
  static/images/rs/screenshots/create-support-package/generate-support-package-select-db.png
  static/images/rs/screenshots/create-support-package/generate-support-package-select-node.png
  static/images/rs/screenshots/create-support-package/support-package-created-alert.png
  static/images/rs/screenshots/create-support-package/support-package-dialog.png
Labels: rs

#1405 RS: Add rladmin cluster config s3_ca_cert step to import/export/backup DB
  content/operate/rs/databases/import-export/export-data.md
  content/operate/rs/databases/import-export/import-data.md
  content/operate/rs/databases/import-export/schedule-backups.md
  content/operate/rs/references/rest-api/objects/cluster/_index.md
Labels: rs

#1414 DOC-5093 RDI image update
  build/image_report.py
  build/pylibs/hugotools.py
  content/integrate/redis-data-integration/architecture.md
  content/integrate/redis-data-integration/data-pipelines/data-denormalization.md
  content/integrate/redis-data-integration/data-pipelines/data-pipelines.md
  content/integrate/redis-data-integration/data-pipelines/prepare-dbs/aws-aur-pgsql.md
  content/integrate/redis-data-integration/quick-start-guide.md
  static/images/rdi/ingest/RDIPipeDataflow.webp
  static/images/rdi/ingest/ingest-active-passive-vms.webp
  static/images/rdi/ingest/ingest-config-folders.webp
  static/images/rdi/ingest/ingest-control-plane.webp
  static/images/rdi/ingest/ingest-dataflow.webp
  static/images/rdi/ingest/ingest-qsg.webp
  static/images/rdi/ingest/nest-flow.webp
  static/images/rdi/ingest/prepsrc/aurora-pgsql/CreateDB6.webp
  static/images/rdi/ingest/prepsrc/aurora-pgsql/CreateParamGroup.webp
  static/images/rdi/ingest/prepsrc/aurora-pgsql/EditParamGroup.webp
Labels: rdi

#1260 DOC-4942 ioredis migration docs
  content/develop/clients/nodejs/connect.md
  content/develop/clients/nodejs/migration.md
  content/develop/clients/nodejs/transpipe.md
Labels: do not merge yet

#1410 K8s: privileged mode
  content/operate/kubernetes/deployment/openshift/old-getting-started-openshift-crdb.md
  content/operate/kubernetes/deployment/openshift/old-index.md
  content/operate/kubernetes/deployment/openshift/openshift-cli.md
  content/operate/kubernetes/deployment/openshift/openshift-operatorhub.md
  content/operate/kubernetes/security/enable-privileged-mode.md
  content/operate/kubernetes/upgrade/openshift-cli.md
  content/operate/kubernetes/upgrade/upgrade-olm.md
Labels: k8s

#1411 K8s: X-Wing release notes
  content/operate/kubernetes/reference/supported_k8s_distributions.md
  content/operate/kubernetes/release-notes/7-22-0-releases/7-22-0-7-april2025.md
  content/operate/kubernetes/release-notes/7-22-0-releases/_index.md
  content/operate/kubernetes/release-notes/7-8-6-releases/7-8-6-1-march2025.md
Labels: k8s

#1425 K8s: X-Wing - fix typo in API changes
  content/operate/kubernetes/release-notes/7-22-0-releases/7-22-0-7-april2025.md
Labels: bug, k8s

#1424 DEV: add upgrade instructions for Redis 8
  content/operate/oss_and_stack/install/_index.md
  content/operate/oss_and_stack/install/archive/_index.md
  content/operate/oss_and_stack/install/build-stack/_index.md
  content/operate/oss_and_stack/install/install-stack/windows.md
  content/operate/oss_and_stack/install/upgrade/_index.md
  content/operate/oss_and_stack/install/upgrade/cluster.md
  content/operate/oss_and_stack/install/upgrade/standalone.md
Labels: dev

#1432 DEV: fix typo on AI page
  content/develop/ai/index.md
Labels: bug, dev

#1433 DEV: add disclaimer to recently updated JSON memory usage page
  content/develop/data-types/json/ram.md
Labels: dev

#1434 DEV+OP: fix a few bad links reported by the SEO team
  content/develop/tools/insight/release-notes/v2.8.0.md
  content/operate/kubernetes/7.8.6/kubernetes-archive.md
  content/operate/kubernetes/kubernetes-archive.md
Labels: bug, k8s, dev

#1436 DEV: fix bug on list dt page
  content/develop/data-types/lists.md
Labels: bug, dev

#1304 RS: Fixed database metrics transition plan
  content/embeds/rs-prometheus-metrics-transition-plan.md
Labels: rs

#1428 RS: Added mtls_trusted_ca to the certificates table
  content/operate/rs/security/certificates/_index.md
Labels: rs

#1446 DEV: fix reply info for the HGETEX command page
  data/resp2_replies.json
  data/resp3_replies.json
Labels: bug, dev

#1438 K8s: Clarify REAADB upgrade databases section
  content/operate/kubernetes/release-notes/7-8-6-releases/7-8-6-1-april2025.md
  content/operate/kubernetes/upgrade/openshift-cli.md
  content/operate/kubernetes/upgrade/upgrade-olm.md
  content/operate/kubernetes/upgrade/upgrade-redis-cluster.md
Labels: bug, k8s

#1447 K8s: Add rancher 1.30 support
  content/operate/kubernetes/reference/supported_k8s_distributions.md
  content/operate/kubernetes/release-notes/7-22-0-releases/7-22-0-7-april2025.md
Labels: k8s

#1444 TLS now supported with I/O threading since Redis 8.0
  content/operate/oss_and_stack/management/security/encryption.md
Labels: documentation, dev

#1442 Time Series - Configuration.md - reorganized and added content
  content/develop/data-types/timeseries/configuration.md
Labels: documentation, dev

#1450 DEV: fix bug on RQE>Admin>Config page
  content/develop/interact/search-and-query/administration/configuration.md
Labels: bug, dev

#1456 OP: add RediSearch release notes
  content/operate/_index.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.10-release-notes.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.6-release-notes.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.8-release-notes.md
Labels: do not merge yet, op

#1423 RDSC-3487: Update RDI -> Deploy a pipeline documentation
  content/integrate/redis-data-integration/data-pipelines/deploy.md
Labels: do not merge yet, rdi

#1460 Reduction of 40 to a single PSC endpoint
  content/operate/rc/security/private-service-connect.md
Labels: rc

#1461 DEV: add vector set to the data type landing page
  content/develop/data-types/_index.md
Labels: dev, CE 8.0

#1462 DOC-5129 added RDI release notes for v1.6.6
  config.toml
  content/integrate/redis-data-integration/installation/install-k8s.md
  content/integrate/redis-data-integration/installation/install-vm.md
  content/integrate/redis-data-integration/installation/upgrade.md
  content/integrate/redis-data-integration/release-notes/rdi-1-6-6.md
Labels: rdi

#1467 DOC-5126 small fixes to RDI denormalisation page
  content/integrate/redis-data-integration/data-pipelines/data-denormalization.md
Labels: rdi

#1327 RC: Map multiple Redis accounts to marketplace accounts
  content/embeds/rc-marketplace-account-add.md
  content/operate/rc/billing-and-payments.md
  content/operate/rc/changelog/april-2025.md
  content/operate/rc/cloud-integrations/_index.md
  content/operate/rc/cloud-integrations/aws-marketplace/_index.md
  content/operate/rc/cloud-integrations/gcp-marketplace/_index.md
  static/images/rc/add-marketplace-account.png
  static/images/rc/aws-marketplace-map-account-dialog.png
  static/images/rc/billing-payment-method-tab.png
  static/images/rc/button-connect-account.png
  static/images/rc/button-marketplace-disconnect.png
  static/images/rc/gcp-marketplace-map-account-dialog.png
Labels: do not merge yet, rc

#1472 OP: add module release notes
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisbloom/redisbloom-2.4-release-notes.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisbloom/redisbloom-2.6-release-notes.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisbloom/redisbloom-2.8-release-notes.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisjson/redisjson-2.4-release-notes.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisjson/redisjson-2.6-release-notes.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisjson/redisjson-2.8-release-notes.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redistimeseries/redistimeseries-1.10-release-notes.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redistimeseries/redistimeseries-1.12-release-notes.md
  content/operate/oss_and_stack/stack-with-enterprise/release-notes/redistimeseries/redistimeseries-1.8-release-notes.md
Labels: op

#1481 RS 7.8.6 end of April maintenance release docs
  content/operate/rs/references/rest-api/objects/bootstrap/_index.md
  content/operate/rs/release-notes/rs-7-8-releases/_index.md
  content/operate/rs/release-notes/rs-7-8-releases/rs-7-8-6-60.md
Labels: do not merge yet, rs

#1483 RS: Added Ubuntu 22 checksum to 7.8.6 April maintenance release notes
  content/operate/rs/release-notes/rs-7-8-releases/rs-7-8-6-60.md
Labels: rs

#1474 RC: Add new supported regions to supported regions page
  content/operate/rc/supported-regions.md
Labels: rc
