Repository redis/docs, pull requests merged in 2025-10, with the labels that each got.

#2198 DOC-5785 added Rust examples in updated format
  build/components/example.py
  local_examples/client-specific/rust-async/landing.rs
  local_examples/client-specific/rust-sync/landing.rs
Labels: clients

#2205 DOC-5791 DOC-5792 Rust string and hash data type TCEs
  content/develop/data-types/strings.md
  local_examples/rust-async/dt-hash.rs
  local_examples/rust-async/dt-string.rs
  local_examples/rust-sync/dt-hash.rs
  local_examples/rust-sync/dt-string.rs
Labels: clients

#2206 DOC-5799: search: document procedure for building with Intel binaries
  content/develop/ai/search-and-query/vectors/svs-compression.md
Labels: dev, ros 8.4

#1987 Site: add agent gen code from AI week to PROD
  assets/css/index.css
  content/develop/ai/agent-builder/_index.md
  content/develop/ai/agent-builder/agent-concepts.md
  layouts/_default/baseof.html
  layouts/shortcodes/agent-builder.html
  static/code/agent-templates/python/conversational_agent.py
  static/code/agent-templates/python/recommendation_agent.py
  static/css/agent-builder.css
  static/images/ai_agent/ai-agent-architecture-diagram.svg
  static/images/ai_agent/simple-processing-cycle.svg
  static/js/agent-builder.js
Labels: do not merge yet

#2216 Update hsetex.md
  content/commands/hsetex.md
Labels: dev, cmds
